docs/FormattingConventions.md

The given URL is dead, changed it to a wayback machine URL for the file.

Fixed URL for FormattingConventions.doc

---

src/Fantomas.Tests/PatternMatchingTests.fs
src/Fantomas/CodeFormatter.fs
src/Fantomas/CodeFormatter.fsx
src/Fantomas/Fantomas.fsproj
src/Fantomas/FormatConfig.fs
src/Fantomas/SourceParser.fs
src/Fantomas/SourceTransformer.fs
src/Fantomas/TokenMatcher.fs
src/Fantomas/Utils.fs
src/fantomas.sln

Fix desugar patterns' bug exposed by FsCheck

---

src/Fantomas.Tests/RecordTests.fs
src/Fantomas/CodePrinter.fs

Fixes #194
Time to fix it: ~2h (indicative - for reference).
- Time to rebase, reunderstand the project, make a fix

Records with implementation visibility attribute

---

README.md

Because only that package contains both the executable and the library.

README: update FantomasCLI package link

---

src/Fantomas.Tests/StringTests.fs
src/Fantomas.Tests/UnionTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceTransformer.fs

Fixed #186 by adding `Case =` part in strict mode.
Also added test for uncommon literals in strict mode.

Add enum identifiers in strict mode (#186)

---

src/Fantomas.Tests/FunctionDefinitionTests.fs
src/Fantomas/CodePrinter.fs

Fix case: 
`let subtype (xs : seq<'t :> System.IDisposable>) = ()` 
-> 
`let subtype (xs : seq<'t when 't :> System.IDisposable>) = ()`, 
root cause of #126.

 Print single subtype constraint without "when". (Fix #126)

---

src/Fantomas.Tests/FunctionDefinitionTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceTransformer.fs

Fix #189.
+ some DRY refactoring around lookup functions.

 Use lookup for return type in extern definition. (Fix #189).

---

src/Fantomas.Tests/ClassTests.fs
src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas/CodePrinter.fs

Fix #225.
Refactor of "prepend type if expr is typed" pattern.
Remove spaces at end of line after `member`, and fix tests in that regard.

Fix type annotation in members with getter/setter (fix #225), fix space-at-end-of-line issues in members.

---

src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas.Tests/TypeProviderTests.fs
src/Fantomas/CodePrinter.fs

This would solve https://github.com/dungpa/fantomas/issues/131.
@jindraivanek any idea how this can be merged into the master branch?

Removed whitespaces around type provider arguments. #131

---

.paket/Paket.Restore.targets
RELEASE_NOTES.md
paket.dependencies
src/Fantomas.Cmd/AssemblyInfo.fs
src/Fantomas.Cmd/Fantomas.Cmd.fsproj
src/Fantomas.Cmd/paket.references
src/Fantomas.Tests/Fantomas.Tests.fsproj
src/Fantomas/AssemblyInfo.fs
src/Fantomas/Fantomas.fsproj

https://www.nuget.org/packages/FSharp.Compiler.Service/ has a dependency on FSharp.Core higher or equal than 4.1.8, this caused for a mismatch in the generated `dotnet-fantomas.deps.json` located at `C:\Users\name\.nuget\packages\.tools\dotnet-fantomas\2.7.1\netcoreapp2.0`.
Long story short, the cli tool needs a direct dependency on FSharp.Core in order for this file to be generated correctly. I already pushed the fix to https://www.nuget.org/packages/dotnet-fantomas/2.7.1, it works now.

Hotfix for runtime issue when executing dotnet-fantomas

---

README.md

Main motivation for this is that the link to AppVeyor contains an artifact of the build.
Useful for trying out early builds.

Add build image for AppVeyor

---

README.md

Hello, French Grammar Nazi here :) I would like to point out that _Fantômas_ is a proper noun and has no meaning of its own in French. The translation for _ghost_ is _fantôme_.

Fix "Fantômas" mistranslation in README

---

src/Fantomas.Tests/PreserveEOLTests.fs
src/Fantomas/TokenMatcher.fs

the code formatted with ```preserveEOL``` feature will be broken and cannot compile, that PR should fix related issues.
P.S: PR #271  have to be accepted before, because a part of changes is based upon.

Fix for preserve EOL feature

---

src/README.md

`fantomas.vssdk.sln`  is gone.

Remove obsolete README mention of fantomas.vssdk.sln

---

.gitignore
README.md
src/Fantomas.Tests/ModuleTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs

Provides a fix for issue #292.
Additionally, provides a fix for printing recursive modules with access modifier. `module internal rec Test =` was being rewritten as `module rec internal Test =` in v2.8.1.
I also added `.ionide` to the .gitignore.
Let me know if anything needs changed!

Fix recursive namespaces and fix recursive modules with access modifier

---

src/Fantomas.Tests/ClassTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/FormatConfig.fs
src/Fantomas/SourceTransformer.fs

Ensure parenthesis around multiline expression before dot - fix #246

---

src/Fantomas.Tests/Fantomas.Tests.fsproj
src/Fantomas.Tests/FormatAstTests.fs
src/Fantomas.Tests/FormattingPropertyTests.fs
src/Fantomas.Tests/TestHelpers.fs
src/Fantomas/CodeFormatterImpl.fs

Only wrap formatContext.Source with an option when there is a string present.
Also added a test for this and refactored some test code to be reusable.

Fix for 321

---

src/Fantomas.Cmd/Fantomas.Cmd.fsproj
src/Fantomas.Tests/Fantomas.Tests.fsproj
src/Fantomas/Fantomas.fsproj

I'm on a fresh Windows machine and it is no longer possible to download the developer pack for .NET 4.5.
[See list](https://www.microsoft.com/net/download/visual-studio-sdks).
4.5 is also end of life for a while now.

Upgrade to 452

---

build.fsx

Chessie is currently not building on CI.
Latest tag uses an old version of paket and is not an option.
Removing Chessie for now.

Removing chessie from projects to test.

---

src/Fantomas.Tests/ModuleTests.fs

Added regression test for #264.

---

src/Fantomas.Cmd/Program.fs

Sorry to bother you for such a trivial PR.
It just tries to add qualified name in matching values of `InputPath` and `OutputPath`, for example:
```
let outputPath = ref Notknown
```
becomes
```
let outputPath = ref OutputPath.Notknown
```
because I've learned from [here](https://www.ikriv.com/dev/misc/fsharp/fs_enums) that the compiler will not warn if there are ambiguities (it simply uses the most recent suitable value), so there would possibly exist ambiguities (in future, not now).
I'm still (re)learning F# and do not know much, so feel free to reject if you find anything inappropriate.
Many thanks.

Use qualified name for inputPath and outputPath

---

src/Fantomas/AssemblyInfo.fs
src/Fantomas/Fantomas.fsproj

In https://github.com/fsprojects/fantomas/pull/375 I removed the AssemblyInfo.fs file entirely and marked the internals visible in the fsproj.
I now regret that decision and changed it back.

Added back internals visible in code.

---

src/Fantomas.Tests/PatternMatchingTests.fs
src/Fantomas/CodePrinter.fs

Each pattern is on a newline.

---

src/Fantomas.Tests/PatternMatchingTests.fs
src/Fantomas/CodePrinter.fs

Fix for [#381](https://github.com/fsprojects/fantomas/pull/394/files#diff-67f2c980dd1bfa59fc7827b20d3ef350R296) made me realize that #381 could be fixed with `futureNlnCheck` .
This also resolves the limitation that the previous fix had.

Refactored fix for #383.

---

README.md

You need the `--framework` setting if you are on .NET Core 2.2 of higher.

Added --framework to install instructions.

---

src/Fantomas.Tests/RecordTests.fs
src/Fantomas.Tests/TestHelpers.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Context.fs
src/Fantomas/SourceParser.fs

Avoids exceptions when trying to format anon records and adds code printing for the new expressions and types.
Please note: printed anon records types may exceed desired line length with this implementation.

Add anon records formatting

---

src/Fantomas.Tests/AttributeTests.fs
src/Fantomas.Tests/ClassTests.fs
src/Fantomas.Tests/ComparisonTests.fs
src/Fantomas.Tests/ComputationExpressionTests.fs
src/Fantomas.Tests/ControlStructureTests.fs
src/Fantomas.Tests/DataStructureTests.fs
src/Fantomas.Tests/FormattingSelectionOnlyTests.fs
src/Fantomas.Tests/FormattingSelectionTests.fs
src/Fantomas.Tests/FunctionDefinitionTests.fs
src/Fantomas.Tests/NoTrailingSpacesTests.fs
src/Fantomas.Tests/OperatorTests.fs
src/Fantomas.Tests/PatternMatchingTests.fs
src/Fantomas.Tests/PipingTests.fs
src/Fantomas.Tests/QuotationTests.fs
src/Fantomas.Tests/RecordTests.fs
src/Fantomas.Tests/SignatureTests.fs
src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas.Tests/UnionTests.fs
src/Fantomas/FormatConfig.fs

A follow up for #432, as discussed with @nojaf and @jindraivanek.

Default config: PageWidth = 120

---

src/Fantomas.Tests/ClassTests.fs
src/Fantomas.Tests/ComputationExpressionTests.fs
src/Fantomas.Tests/ControlStructureTests.fs
src/Fantomas.Tests/DataStructureTests.fs
src/Fantomas.Tests/FormattingSelectionTests.fs
src/Fantomas.Tests/KeepNewlineAfterTests.fs
src/Fantomas.Tests/LetBindingTests.fs
src/Fantomas.Tests/OperatorTests.fs
src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Context.fs

Fix #456
Change globally all ranges `1..10` to `1 .. 10`. Based on official docs, I think it is correct formatting:
https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/loops-for-in-expression
https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/lists

Add spaces around ".." operator

---

.paket/Paket.Restore.targets
src/Fantomas.Tests/ClassTests.fs
src/Fantomas/CodePrinter.fs

Fixes an issue in an abstract member declaration where the only parameter is a non-tuple, non-function, optional param. Formatting was dropping the `?` on the parameter.
For example:
```fsharp
type A =
abstract B: ?p:float -> unit
```
would format to
```fsharp
type A =
abstract B: p:float -> unit
```
The issue was in the printer: the `_` wildcard case was not account for the `isOpt` boolean. When making the wildcard account for `isOpt`, I noticed all three matches were the same except for the `hasBracket` bool, so I moved only that bool to the matching statement and sent to the same printing code underneath.
Added some test cases that account for both the fix and the changed code. Members `B` and `C` exercise the `TTuple` case for optional parameters, and member `D` exercises the `TFun` …

Fix for abstract member declaration with optional param

---

src/Fantomas.Tests/RecordTests.fs
src/Fantomas/CodePrinter.fs

Fix: Print comment after '{' in Record signature.

---

src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Context.fs

Fix: Don't duplicate newline between recursive types

---

src/Fantomas.Tests/LetBindingTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/TriviaContext.fs

This seems to run the tests green and fix the minimal case of #513, it doesn't fix all the issues formatting the code that was submitted though, so additional cases needs to be identified, #527 is another issue encountered formatting https://github.com/knocte/geewallet codebase.

single line comment trivia treated same as new line trivia (partial fix for issue #513)

---

src/Fantomas/CodePrinter.fs

The word trivium is not used anywhere in the code base so it sounds a bit weird.
It makes more sense to me to use FCS version instead of F# release version.

Rephrased code comment

---

src/Fantomas.Tests/AppTests.fs
src/Fantomas/CodePrinter.fs

The indentation needs to be checked against the function expression start column in which case, prepend the "to be printed" expression with enough leading space.
fixes #545
Please let me know if the changes in implementation needs to be handled in a better way.

fix function application being formatted toward invalid syntax

---

src/Fantomas.CoreGlobalTool/Program.fs

All the other options had their default specified (when issuing --help
in the command line) except this one.

CoreGlobalTool: specify what's default for --keepNewlineAfter

---

src/Fantomas.CoreGlobalTool/Program.fs

Otherwise fantomas processes unwanted files:
```
...
./.fable/Fable.Elmish.Debugger.3.0.2/debugger.fs has been written.
./.fable/Fable.Elmish.Debugger.3.0.2/Fable.Import.RemoteDev.fs has been written.
...
./node_modules/fable-splitter/tests/allFiles/File1.fs has been written.
./node_modules/fable-splitter/tests/allFiles/File2.fs has been written.
```

Tool recursive - exclude .fable and node_modules dirs

---

src/Fantomas.Tests/ClassTests.fs
src/Fantomas/CodePrinter.fs

The pattern matching above uses nested `sepMember` function
to consider Trivia Content. The difference between those
pattern matching cases is that latter one matches on when
there are trailing non-multiline members.
There's some code duplication between those two now, which
I'm happy to refactor - feedback welcome.

Consider Trivia Content before multiline members - fixes #569

---

src/Fantomas.Tests/ClassTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs

Fixes all cases from #586 except from the `elif` one - wasn't able to trace it down, and as a workaround for now I switched to using pattern matching in my project.
I'll extract the `elif` case from #586 and make it a separate issue

Unwanted new line added - fixes #586

---

src/Fantomas.Tests/AttributeTests.fs
src/Fantomas/CodePrinter.fs

The same fix will probably be relevant [here](https://github.com/fsprojects/fantomas/blob/d5654e8b91596285ada392f4dff3873662b8c9d9/src/Fantomas/CodePrinter.fs#L2121).
Any idea @jindraivanek how to write a test to verify this?

Don't execute genTypeByLookup when StrictMode = true. Fixes #562.

---

RELEASE_NOTES.md
src/Fantomas.CoreGlobalTool/Fantomas.CoreGlobalTool.fsproj
src/Fantomas.Tests/Fantomas.Tests.fsproj
src/Fantomas.Tests/RecordTests.fs
src/Fantomas.Tests/StringTests.fs
src/Fantomas.Tests/TriviaTests.fs
src/Fantomas/Fantomas.fsproj
src/Fantomas/TokenParser.fs

Don't accept empty lines in trivia when part of multiline string.
Bump version to 3.1.1.

Preserve newlines within multiline strings.

---

src/Fantomas.Tests/RecordTests.fs
src/Fantomas/CodePrinter.fs

Fix duplicate newlines in object expression. 

---

src/Fantomas.CoreGlobalTool/Program.fs

It turns out we don't support `*.fsproj` files and that was at some point confusing while investigating #251.

Clarify what input from command line is supported

---

src/Fantomas.Tests/SpecialConstructsTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceTransformer.fs

Don't add space when array or list is used inside a chained accessor

---

src/Fantomas.Tests/UnionTests.fs
src/Fantomas/CodePrinter.fs

Add pipe before single case DU with no UnionCaseFields

---

src/Fantomas.CoreGlobalTool/Program.fs

This PR fixes the `--stdin` functionality which seemed to not work when the new version started using `Argu` for parsing the CLI arguments.
I have also preserved the original functionality where stdin input can only be read if redirected through a pipe:
```
$ echo 'open System;; let () = printf "Hello World"' | fantomas-tool.exe --stdin
open System
let () = printf "Hello World"
fantomas-tool.exe --stdin
Input path is missing...
```
Current master build:
```
$ echo 'open System;; let () = printf "Hello World"' | fantomas-tool.exe --stdin
ERROR: argument '--stdin' must be followed by <string>.
... omitted usage output
$ fantomas-tool.exe --stdin
ERROR: argument '--stdin' must be followed by <string>.
... omitted usage output
```
Fantomas.CoreGlobalTool 3.1.0:
```
$ echo 'open System;; let …
```

Restore --stdin flag functionality

---

src/Fantomas.CoreGlobalTool/Program.fs

My assumption that Arguments.Input is always required was wrong.
The change in #656 made that clear.
Now everything goes via Argu.

Removed workaround for version.

---

src/Fantomas.Tests/UnionTests.fs
src/Fantomas/AstTransformer.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs
src/Fantomas/Trivia.fs
src/Fantomas/TriviaHelpers.fs

Fixes #626 , I've modified the AstTransformer to consider Ident as children instead of properties.
That way we can more fine-grained add trivia to AST nodes.
The `OptVar` change was necessary to preserve the comment after `.IsNone` in https://github.com/fsprojects/fantomas/blob/818c5a956be2fdaf6f4f756c0bd8e5277cd99f38/src/Fantomas.Tests/ControlStructureTests.fs#L246.

Preserve back ticks in enum members

---

src/Fantomas.Tests/Fantomas.Tests.fsproj
src/Fantomas.Tests/FormatConfigEditorConfigurationFileTests.fs
src/Fantomas.Tests/FormatConfigJsonConfigurationFileTests.fs
src/Fantomas.Tests/TestHelpers.fs
src/Fantomas/CodeFormatter.fs
src/Fantomas/CodeFormatterImpl.fs
src/Fantomas/ConfigFile.fs
src/Fantomas/EditorConfig.fs
src/Fantomas/Fantomas.fsproj
src/Fantomas/FormatConfig.fs
src/Fantomas/JsonConfig.fs

I'm on board with having support for `.editorconfig` as requested in #650.
Some of the logic of constructing the configuration record can be re-used and I've extracted just that in this PR. 
Leaving room to do the actual implementation of processing the `.editorconfig` file for somebody else.

Extract shared logic between json config and editorconfig.

---

src/Fantomas.Tests/DataStructureTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Context.fs

This PR implements support for formatting from-end slices without losing the `^` character.
I added a test to verify, and cleaned up the matches a bit to clarify the exact kinds of slice cases each branch handled.
Fixed #691

handle from-end slices for indexers

---

src/Fantomas.Tests/FormatConfigJsonConfigurationFileTests.fs
src/Fantomas/ConfigFile.fs

Fix "--config" rejecting directories with a "."

---

.github/workflows/main.yml

A lot of builds are failing to setup .NET Core, I think this will fix this.

Fix Setup .NET Core in GitHub Actions

---

src/Fantomas.Tests/ClassTests.fs
src/Fantomas/SourceTransformer.fs

Fix #664.
Note that this change order to be first getter then setter (see changed test).

Support property setter before getter (fix #664)

---

src/Fantomas/AstTransformer.fs

As discovered by @Krzysztof-Cieslak [here](https://www.twitch.tv/k_cieslak).

Fix Type for SynMatchClause.Clause in visitSynMatchClause

---

src/Fantomas.Tests/LetBindingTests.fs
src/Fantomas/CodePrinter.fs

Fix: Add space before argument when function is wrapped in parenthesis.

---

src/Fantomas.Tests/OperatorTests.fs
src/Fantomas.Tests/StringTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs

Not sure this is the best solution to fix #754.
Suggestion to wrap all SynExpr.App in parenthesis broke twenty tests and I think we will add it way more than needed.
So that is why I limited the scope to SynExpr.App with multiline parameters.

Wrap multiline string in parenthesis before infix operator

---

src/Fantomas.Tests/FunctionDefinitionTests.fs

#740 is not a problem anymore, adding regression tests.

Add regression tests for long function signatures

---

src/Fantomas.Tests/Fantomas.Tests.fsproj
src/Fantomas.Tests/MultilineBlockBracketsOnSameColumnRecordTests.fs
src/Fantomas.Tests/NewlineBetweenTypeDefinitionAndMembersTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Context.fs
src/Fantomas/FormatConfig.fs

Fixes #752.
I think this is fairly complete, I might have missed some scenarios.
Let me know if some other cases need to be supported as well.

Introduce setting to add newline between record type and members.

---

src/Fantomas.Tests/ClassTests.fs
src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas/CodePrinter.fs

Don't let trivia content before make a member definition multiline

---

src/Fantomas.Tests/SynConstTests.fs
src/Fantomas/TokenParser.fs

Fixes #646
Strings end with the `String` token:
When you have two string after each other it led to incorrect behaviour.
Fixed now.

End String Content after String token

---

src/Fantomas.Tests/RecordTests.fs
src/Fantomas/CodePrinter.fs

Partial fix for #516, although the real problem there is a nasty trivia thing.
Nevertheless, the is needed as well.

Line comment after { leads to multiline construct.

---

src/Fantomas.Tests/FunctionDefinitionTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Trivia.fs

Fix 776, add IdentBetweenTicks trivia for SynPat.LongIdent node, dont use backticks when not needed

---

src/Fantomas/Fantomas.fsproj

I think this slipped back in after a bad merge.

TargetFramework instead of TargetFrameworks

---

src/Fantomas.Tests/CompilerDirectivesTests.fs
src/Fantomas.Tests/OperatorTests.fs
src/Fantomas.Tests/StringTests.fs
src/Fantomas/CodePrinter.fs

Fixes #783, it will only add one extra space in our current problem.
Since this is such an edge case I would go for this fix.
We can revisit this another time to perhaps consider newline + tab.

Add extra space after multiline string

---

src/Fantomas.Tests/ListTests.fs
src/Fantomas/SourceParser.fs

Determine upper or lowercase for SynExpr.DotIndexedGet

---

src/Fantomas.CoreGlobalTool.Tests/ByteOrderMarkTests.fs
src/Fantomas.CoreGlobalTool.Tests/Fantomas.CoreGlobalTool.Tests.fsproj
src/Fantomas.CoreGlobalTool.Tests/TestHelpers.fs
src/Fantomas.CoreGlobalTool/Program.fs

This worked on my machine on Windows.
I'm not really an expert when it comes to these things, all suggestions to improve are welcome.

Respect byte-order mark.

---

src/Fantomas.Tests/ComputationExpressionTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs

Fixes #806
Apply same opening brace for computation expression if the identifier is a nested structure.
```fsharp
App
(NonAtomic,false,
App
(NonAtomic,false,Ident test,
Const
(String
("test",
tmp.fsx (5,11--5,17) IsSynthetic=false),
tmp.fsx (5,11--5,17) IsSynthetic=false),
tmp.fsx (5,6--5,17) IsSynthetic=false),
```
See https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQDaAPACroALmgB8AXQA6yGrEFhBQtGAC8UiArSCAMkTkTIG4frUQwXE6flCw%2Bw-rDALlsAFEAHgAdYzQQDpYAI4ArrTyAE5BsOGRNpBBqJ7eCtDGyM5gAL5OYpAgGUA

Apply opening brace in nested computation expression identifier

---

src/Fantomas.Tests/LetBindingTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Context.fs

Fixes #728 
Hash directives in a let binding before the equals sign were not handled and caused the crash in the linked issue when merging the formatted code for both ASTs back together. 
The changes I made check for the presence of Trivia content before the equals sign in a let binding. In case there is Trivia content it gets printed before the equals sign.

Check for Trivia content before the equals sign in let bindings

---

src/Fantomas.Tests/ClassTests.fs
src/Fantomas.Tests/ModuleTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Context.fs
src/Fantomas/Trivia.fs
src/Fantomas/TriviaHelpers.fs

I've taken a stab at fixing #784, but I'd like to check if I'm heading in the right direction first. The problem is that the `sepModuleAndFirstDecl` checks for any declaration. If there is no such declaration, two newlines are added after the module declaration. As comments are no declarations, this means that the comment will also receive two newlines. The main problem is that running format one more time after that, will add another newlines (there will be three at this point), and so on.
Let me know if I'm heading in the right direction with my solution.

Don't add newline to module where the first trivia is a newline

---

src/Fantomas.Tests/CommentTests.fs
src/Fantomas/Trivia.fs

This PR fix issue #810. 
The used strategy is similar to the one used for [LineCommentOnSingleLine](https://github.com/matteobaglini/fantomas/blob/f83a2de6b311ac89e7be56896304b1feaf6f502e/src/Fantomas/Trivia.fs#L247-L250) at EOF.

Proper handling block comment at the end of file

---

src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas/CodePrinter.fs

Fixes #841 
Member and constructor tuples should have a comma at the end of their corresponding lines.

Add comma at EOL for member/ctor tuples

---

src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas/CodePrinter.fs

Fixes #846 
The way I have implemented this is that we check for the amount of parameters in a typed member definition. If there is more than one parameter the return type is kept in the same line as the last parameter. 
Regarding the checking for the amount of parameters I am not sure if it is implemented in the cleanest way. For that reason this PR is created as draft. When it is clear how the changes should be implemented I can also add more test cases.
cc @nojaf

Split multiple parameters across multiple lines if they exceed page width

---

src/Fantomas.Tests/FunctionDefinitionTests.fs
src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Context.fs

Adds support to format long member definitions with a single parameter.
The test in FunctionDefinition had to be changed, the result is still valid AST, however, I admit this doesn't really look all the good. I already created https://github.com/fsprojects/fantomas/issues/735 a while ago to tackle this properly.
Seems like the lesser evil for now.

Support long member definitions with a single parameter

---

src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas/CodePrinter.fs

Put access modifier on new line when printing a long type constructor

---

src/Fantomas.Tests/MultilineBlockBracketsOnSameColumnRecordTests.fs
src/Fantomas/CodePrinter.fs

Fixes #852 
Puts the `inherit`-keyword into a new line and indents when `MultilineBlockBracketsOnSameColumn` is enabled. Example:
**Code**
```
let a =
{ inherit ProjectPropertiesBase<_>(projectTypeGuids, factoryGuid, targetFrameworkIds, dotNetCoreSDK)
buildSettings = FSharpBuildSettings()
targetPlatformData = targetPlatformData }
```
**Result**
```
let a =
{
inherit ProjectPropertiesBase<_>(projectTypeGuids, factoryGuid, targetFrameworkIds, dotNetCoreSDK)
buildSettings = FSharpBuildSettings()
targetPlatformData = targetPlatformData
}
```
At the time of writing this it is not entirely clear if the behaviour this PR implements is intended. Thus it's a draft for now until we know more.

MultilineBlockBracketsOnSameColumn: Put inherit keyword in record into newline

---

src/Fantomas.Tests/LambdaTests.fs
src/Fantomas/CodePrinter.fs

Fixes #870.
@jindraivanek we already had an indent if multiline so that pushes the body of the `f` of the `fun`.

Wrap lambda in atCurrentColumn

---

README.md

Updated the _try online_ link to the new URL (on fsprojects.github.io).

Try online link updated to new URL.

---

src/Fantomas/CodePrinter.fs

This won't massively improve anything but it is again a logic check to have.

by-pass enterNode and leaveNode when no trivia are left

---

src/Fantomas.Tests/FunctionDefinitionTests.fs
src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas/CodePrinter.fs

Fixes #868.
Notice that not everything is possible to adhere to the max page width.
For example:
```fsharp
type Foo =
static member Deserialize(loooooooooooooooooooooooooooooooooooooooooooooooooooooonnnnnnnnnnnnnnnnnnnnngggggggggggJsonVaaaaalueeeeeeeeeeeeeeee): SomeType =
Decode.SomeType
loooooooooooooooooooooooooooooooooooooooooooooooooooooonnnnnnnnnnnnnnnnnnnnngggggggggggJsonVaaaaalueeeeeeeeeeeeeeee
```
I think this is an acceptable trade-off for now. I'm open to discussing this though.

Format long member binding and constructors according to the F# style guide

---

src/Fantomas.Tests/FunctionDefinitionTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceTransformer.fs

Fixes #883, this is something that is only noticeable when the indent is not 4 spaces.

Long function signatures have indent if parameters are on separate line.

---

src/Fantomas/Context.fs

before
| Method |    Mean |   Error |  StdDev | Rank |        Gen 0 |       Gen 1 |       Gen 2 | Allocated |
|------- |--------:|--------:|--------:|-----:|-------------:|------------:|------------:|----------:|
| Format | 41.41 s | 21.28 s | 1.166 s |    1 | 2660000.0000 | 920000.0000 | 148000.0000 |   13.1 GB |
after
| Method |    Mean |   Error |  StdDev | Rank |        Gen 0 |       Gen 1 |      Gen 2 | Allocated |
|------- |--------:|--------:|--------:|-----:|-------------:|------------:|-----------:|----------:|
| Format | 37.33 s | 2.964 s | 0.162 s |    1 | 2357000.0000 | 759000.0000 | 66000.0000 |  11.92 GB |

Perf: use Queue.length instead Seq.length

---

src/Fantomas.Tests/QueueTests.fs
src/Fantomas/Context.fs
src/Fantomas/Queue.fs

This is total rewrite of `Queue` data structure for performance for our use case.
before 
| Method |    Mean |   Error |  StdDev | Rank |        Gen 0 |       Gen 1 |      Gen 2 | Allocated |
|------- |--------:|--------:|--------:|-----:|-------------:|------------:|-----------:|----------:|
| Format | 35.68 s | 6.544 s | 0.359 s |    1 | 2376000.0000 | 777000.0000 | 82000.0000 |  11.92 GB |
after
| Method |    Mean |   Error |  StdDev | Rank |        Gen 0 |       Gen 1 |      Gen 2 | Allocated |
|------- |--------:|--------:|--------:|-----:|-------------:|------------:|-----------:|----------:|
| Format | 33.09 s | 8.043 s | 0.441 s |    1 | 2165000.0000 | 668000.0000 | 79000.0000 |  10.75 GB |

Perf: optimze Queue data structure

---

src/Fantomas/Trivia.fs

before
| Method |    Mean |   Error |  StdDev | Rank |        Gen 0 |       Gen 1 |      Gen 2 | Allocated |
|------- |--------:|--------:|--------:|-----:|-------------:|------------:|-----------:|----------:|
| Format | 35.87 s | 4.575 s | 0.251 s |    1 | 2150000.0000 | 663000.0000 | 80000.0000 |   10.7 GB |
after
| Method |    Mean |   Error |  StdDev | Rank |       Gen 0 |       Gen 1 |      Gen 2 | Allocated |
|------- |--------:|--------:|--------:|-----:|------------:|------------:|-----------:|----------:|
| Format | 16.48 s | 7.260 s | 0.398 s |    1 | 665000.0000 | 247000.0000 | 35000.0000 |   3.47 GB |
Not bad for 3 lines remove 😛

Perf: Collect trivias - remove unnecessary sorts

---

src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas/Trivia.fs

Fixes #910
The problem here is the new line between the types.
It was being assigned to the attributes in the first type as content after.
The reason for this is that the range of the field does contain the attribute (unlike let binding f.ex).

Don't consider attribute above field a proper candidate for trivia

---

src/Fantomas/TokenParser.fs
src/Fantomas/Trivia.fs

Before:
```
| Method |    Mean |   Error |   StdDev | Rank |       Gen 0 |       Gen 1 |      Gen 2 | Allocated |
|------- |--------:|--------:|---------:|-----:|------------:|------------:|-----------:|----------:|
| Format | 6.588 s | 1.049 s | 0.0575 s |    1 | 606000.0000 | 160000.0000 | 12000.0000 |   2.76 GB |
```
After:
```
| Method |    Mean |   Error |   StdDev | Rank |       Gen 0 |       Gen 1 |      Gen 2 | Allocated |
|------- |--------:|--------:|---------:|-----:|------------:|------------:|-----------:|----------:|
| Format | 6.132 s | 1.095 s | 0.0600 s |    1 | 626000.0000 | 180000.0000 | 28000.0000 |   2.76 GB |
```

Perf blank lines

---

src/Fantomas/Context.fs

before
```
| Method |    Mean |   Error |  StdDev | Rank |       Gen 0 |       Gen 1 |      Gen 2 | Allocated |
|------- |--------:|--------:|--------:|-----:|------------:|------------:|-----------:|----------:|
| Format | 13.35 s | 5.253 s | 0.288 s |    1 | 517000.0000 | 159000.0000 | 14000.0000 |   2.76 GB |
```
after
```
| Method |    Mean |   Error |  StdDev | Rank |       Gen 0 |       Gen 1 |      Gen 2 | Allocated |
|------- |--------:|--------:|--------:|-----:|------------:|------------:|-----------:|----------:|
| Format | 11.02 s | 0.843 s | 0.046 s |    1 | 451000.0000 | 159000.0000 | 13000.0000 |   2.48 GB |
```

Perf: short-circuit (+>) in ShortExpression mode

---

RELEASE_NOTES.md
docs/Documentation.md
docs/Formatting-Elmish-code.md
src/Fantomas.CoreGlobalTool.Tests/Fantomas.CoreGlobalTool.Tests.fsproj
src/Fantomas.CoreGlobalTool/Fantomas.CoreGlobalTool.fsproj
src/Fantomas.Tests/ElmishTests.fs
src/Fantomas.Tests/Fantomas.Tests.fsproj
src/Fantomas.Tests/LambdaTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Fantomas.fsproj
src/Fantomas/FormatConfig.fs
src/Fantomas/SourceParser.fs
src/Fantomas/schema.json

Somewhat related to #470, here is an attempt of having a better way of formatting Elmish / Fable.React inspired code.
I wrote a short guide that the thought process.

Formatting Elmish inspired code

---

src/Fantomas.Tests/CommentTests.fs
src/Fantomas/TokenParser.fs

Fixes #920
I'm open to suggestions when it comes to using that `mutable`.
Had no immediate idea of how to do it without it.

Only keep collecting line comments if they are not separate by a new line

---

src/Fantomas/Trivia.fs

On my local machine:
Before:
```
| Method |    Mean |   Error |   StdDev | Rank |       Gen 0 |       Gen 1 |      Gen 2 | Allocated |
|------- |--------:|--------:|---------:|-----:|------------:|------------:|-----------:|----------:|
| Format | 5.329 s | 3.598 s | 0.1972 s |    1 | 533000.0000 | 178000.0000 | 29000.0000 |    2.5 GB |
```
after:
```
| Method |    Mean |   Error |   StdDev | Rank |       Gen 0 |       Gen 1 |      Gen 2 | Allocated |
|------- |--------:|--------:|---------:|-----:|------------:|------------:|-----------:|----------:|
| Format | 4.727 s | 2.141 s | 0.1174 s |    1 | 490000.0000 | 149000.0000 | 14000.0000 |   2.35 GB |
```

Optimized findFirstNodeAfterLine

---

RELEASE_NOTES.md
src/Fantomas.CoreGlobalTool.Tests/Fantomas.CoreGlobalTool.Tests.fsproj
src/Fantomas.CoreGlobalTool/Fantomas.CoreGlobalTool.fsproj
src/Fantomas.Tests/ElmishTests.fs
src/Fantomas.Tests/Fantomas.Tests.fsproj
src/Fantomas/CodePrinter.fs
src/Fantomas/Fantomas.fsproj
src/Fantomas/FormatConfig.fs
src/Fantomas/SourceParser.fs
src/Fantomas/schema.json

Fixes #927.
@jindraivanek I'm not entirely happy yet with the names of the settings yet.
I'd like to rename `MaxElmishWidth` and `SingleArgumentWebMode` to something more generic.
The naming these things after the current popular frameworks seem like a bad idea.
Call me old fashion but I'd prefer a more timeless ring to the setting names.
Feel free to chime in here @auduchinok.

Add support for Feliz style

---

src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas/AstTransformer.fs
src/Fantomas/Trivia.fs
src/Fantomas/TriviaTypes.fs

Don't add additional newline before middle attribute scenario

---

src/Fantomas.Tests/AppTests.fs
src/Fantomas.Tests/CompilerDirectivesTests.fs
src/Fantomas.Tests/ElmishTests.fs
src/Fantomas.Tests/KeepIfThenInSameLineTests.fs
src/Fantomas.Tests/RecordTests.fs
src/Fantomas.Tests/TypeProviderTests.fs
src/Fantomas/CodePrinter.fs

Fixes #907 by putting every parameter of a function application on a newline if the function application exceeds `PageWidth`.
cc @knocte

Split all parameters of a function application over multiple lines if they exceed page width

---

src/Fantomas.Tests/UnionTests.fs
src/Fantomas/CodePrinter.fs

Do not write a `|` if it's a single case DU with a visibility modifier.

---

src/Fantomas.CoreGlobalTool.Tests/TestHelpers.fs
src/Fantomas.Tests/AttributeTests.fs
src/Fantomas.Tests/CheckTests.fs
src/Fantomas.Tests/QueueTests.fs
src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas/AstTransformer.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Queue.fs
src/Fantomas/Trivia.fs
src/Fantomas/TriviaTypes.fs

Fixes #949 
The main idea is that we count how many lines there are between a SynAttributeList and the parent node (or the next SynAttributeList). If there are gaps, it means trivia will need to be assigned as content after.

Improve assigning trivia after attributes

---

src/Fantomas.Tests/FormatConfigEditorConfigurationFileTests.fs
src/Fantomas/CodeFormatter.fs
src/Fantomas/CodeFormatter.fsi
src/Fantomas/CodeFormatterImpl.fs
src/Fantomas/EditorConfig.fs

Useful in disambiguating situations where no settings could be found. As an added performance bonus, if no settings could be found, it doesn't reconstruct the default config object from scratch.

Add TryReadConfiguration for .editorconfig

---

src/Fantomas.Tests/MultilineBlockBracketsOnSameColumnRecordTests.fs

Is no longer a bug #941.
Fixes #941

Adding regression test for record type with attributes

---

src/Fantomas.Tests/SignatureTests.fs
src/Fantomas/CodePrinter.fs

Preserve with get in signature files

---

src/Fantomas.Tests/SpaceBeforeUppercaseInvocationTests.fs
src/Fantomas/CodePrinter.fs

Don't add space before indexed expression inside DotIndexedGet

---

RELEASE_NOTES.md
src/Fantomas.CoreGlobalTool.Tests/Fantomas.CoreGlobalTool.Tests.fsproj
src/Fantomas.CoreGlobalTool/Fantomas.CoreGlobalTool.fsproj
src/Fantomas.Tests/Fantomas.Tests.fsproj
src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Context.fs
src/Fantomas/Fantomas.fsproj
src/Fantomas/FormatConfig.fs

Fixes #913 , see [GR style guide](https://github.com/G-Research/fsharp-formatting-conventions#place-parameters-on-a-new-line-for-very-long-member-definitions)
I also added some more test to get the default MS style on point.

Support GR very long member definitions

---

src/Fantomas.Tests/LongIdentWithDotsTests.fs
src/Fantomas/CodePrinter.fs

Don't add extra parenthesis for DotGet(Paren(_))

---

src/Fantomas.Tests/ListTests.fs
src/Fantomas/CodePrinter.fs

Indent multiline yield expression

---

src/Fantomas.Tests/ElmishTests.fs
src/Fantomas.Tests/ListTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs

Support Feliz expression with a single child

---

src/Fantomas.Tests/PatternMatchingTests.fs
src/Fantomas/CodePrinter.fs

Print trivia before and after with keyword

---

src/Fantomas.Tests/UnionTests.fs
src/Fantomas/TokenParser.fs
src/Fantomas/Trivia.fs

Assign number trivia to enum cases.

---

src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas/CodePrinter.fs

Print some trivia before properties.

---

src/Fantomas.Tests/LongIdentWithDotsTests.fs
src/Fantomas.Tests/OperatorTests.fs
src/Fantomas/CodePrinter.fs

Keep parenthesis on the same for App inside multiline DotGet thing

---

src/Fantomas.Tests/ListTests.fs
src/Fantomas/Trivia.fs

Ignore SynExpr.CompExpr as TriviaNode candidate.

---

src/Fantomas.Tests/DotGetTests.fs
src/Fantomas.Tests/Fantomas.Tests.fsproj
src/Fantomas/CodePrinter.fs

Keep parenthesis on same line in DotGet.

---

src/Fantomas.Tests/SignatureTests.fs
src/Fantomas/CodePrinter.fs

Don't add additional newline between type and val in signature file

---

src/Fantomas.Tests/IfThenElseTests.fs
src/Fantomas/CodePrinter.fs

Don't add additional new line for SynExpr.IfThenElse inside Sequential

---

src/Fantomas.Tests/IfThenElseTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Context.fs

Print line comment after bool expr in SynExpr.IfThenElse

---

src/Fantomas.Tests/ControlStructureTests.fs
src/Fantomas.Tests/TestHelpers.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Utils.fs

Validate formatted code after unit tests

---

docs/Documentation.md

This trivial PR fixes a missing backtick in Documentaion.md

Fix missing backtick in Documentation.md

---

src/Fantomas.Tests/SignatureTests.fs
src/Fantomas/CodePrinter.fs

Don't add extra parenthesis for SynType.Fun.

---

src/Fantomas.Tests/CompilerDirectivesTests.fs

Adding a regression test for #1026.
This was fixed by the changes of #1058.
Fixes #1026.

Add regression test for indentation after multiple hash directives

---

src/Fantomas.Tests/ClassTests.fs
src/Fantomas.Tests/DotGetTests.fs
src/Fantomas.Tests/LongIdentWithDotsTests.fs
src/Fantomas.Tests/RecordTests.fs
src/Fantomas/CodePrinter.fs

Fixes #1051.
I've added a regression test for the original issue in #246 as well.
@SteveGilham could you confirm that the result in the unit test would work out in your codebase?

Don't always split applications inside a DotGet expression.

---

src/Fantomas.Tests/PatternMatchingTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs

Limit range for arrow token trivia in desugared lambda

---

src/Fantomas.Tests/PatternMatchingTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs

Limit the range for triva from bar token

---

src/Fantomas.Tests/LambdaTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs

Use ranges for parenthesis found in SynExpr.Paren to print trivia

---

src/Fantomas.Tests/NewlineBetweenTypeDefinitionAndMembersTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Context.fs

Preserve existing new line between type and members in signature files

---

src/Fantomas.Tests/SignatureTests.fs
src/Fantomas/CodePrinter.fs

Don't duplicate new line between namespace and attribute of type in signature file

---

src/Fantomas.Tests/ModuleTests.fs
src/Fantomas/CodePrinter.fs

Don't add new line before SynAttributeList when previous SynAttributeList had content after.

---

src/Fantomas.Tests/UnionTests.fs
src/Fantomas/CodePrinter.fs

This solves a regression introduced in https://github.com/fsprojects/fantomas/pull/1052.

Put multiline single case discriminated unions on separate line after equals.

---

src/Fantomas.Tests/ModuleTests.fs
src/Fantomas/CodePrinter.fs

Always add new line between named module and first declaration

---

RELEASE_NOTES.md
docs/Documentation.md
src/Fantomas.CoreGlobalTool.Tests/Fantomas.CoreGlobalTool.Tests.fsproj
src/Fantomas.CoreGlobalTool/Fantomas.CoreGlobalTool.fsproj
src/Fantomas.Extras/Fantomas.Extras.fsproj
src/Fantomas.Tests/CompilerDirectivesTests.fs
src/Fantomas.Tests/ComputationExpressionTests.fs
src/Fantomas.Tests/DotGetTests.fs
src/Fantomas.Tests/Fantomas.Tests.fsproj
src/Fantomas.Tests/FunctionDefinitionTests.fs
src/Fantomas.Tests/LambdaTests.fs
src/Fantomas.Tests/LetBindingTests.fs
src/Fantomas.Tests/LongIdentWithDotsTests.fs
src/Fantomas.Tests/OperatorTests.fs
src/Fantomas.Tests/QuotationTests.fs
src/Fantomas.Tests/RecordTests.fs
src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas.Tests/TypeProviderTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Fantomas.fsproj
src/Fantomas/FormatConfig.fs
src/Fantomas/SourceParser.fs
src/Fantomas/Utils.fs

Feature: MaxDotGetExpressionWidth

---

src/Fantomas.Tests/LambdaTests.fs
src/Fantomas/CodePrinter.fs

Format function calls with multiple lambdas as multiline

---

src/Fantomas.Tests/MultilineBlockBracketsOnSameColumnRecordTests.fs
src/Fantomas.Tests/NumberOfItemsRecordTests.fs
src/Fantomas.Tests/SignatureTests.fs
src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas/CodePrinter.fs

Format multi-line record types with access modifiers consistently

---

src/Fantomas/FormatConfig.fs

Minor change.
It gets compiled to an `FSharpFunc`, so you have to do `FormatConfig.MultilineFormatterType.ToConfigString.Invoke(...)` from outside.

Explicitly specify a method for MultilineFormatterType.ToConfigString

---

src/Fantomas.Tests/LetBindingTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/TriviaHelpers.fs

Print in keyword after correct SynBinding

---

src/Fantomas.Tests/TupleTests.fs
src/Fantomas/CodePrinter.fs

Add parenthesis for multiline SynPat.Tuple expression in SynBinding

---

src/Fantomas.Tests/SignatureTests.fs
src/Fantomas/CodePrinter.fs

Fixes #1181.
Maybe not the fix that was proposed, but this has the least impact.
Is this somewhat acceptable @Smaug123?

Put long return types on the next line of SynModuleSigDecl.Val

---

src/Fantomas.CoreGlobalTool.Tests/CheckTests.fs
src/Fantomas.Extras/FakeHelpers.fs

Ignore newlines when comparing formatted code to original code.

---

.gitignore
docs/Documentation.md
src/Fantomas.Tests/DisableElmishTests.fs
src/Fantomas.Tests/Fantomas.Tests.fsproj
src/Fantomas.Tests/FormatConfigEditorConfigurationFileTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/FormatConfig.fs

Initial attempt to solve #1198 
Left to do:

Add DisableElmishSyntax setting

---

src/Fantomas.Tests/CastTests.fs
src/Fantomas.Tests/ComputationExpressionTests.fs
src/Fantomas.Tests/Fantomas.Tests.fsproj
src/Fantomas/CodePrinter.fs

Added multiline upcast/downcast formatting.

---

src/Fantomas.Tests/IfThenElseTests.fs
src/Fantomas/CodePrinter.fs

Don't add extra newline when no else expression is present. 

---

src/Fantomas.Tests/FormatConfigEditorConfigurationFileTests.fs
src/Fantomas.Tests/TestHelpers.fs

Not sure why, but when trying to build this project with VS4Mac v8.6.7.2
(which uses the following underneath: mono 6.10.0.104 & fsharpc 10.2.3 with
F# 4.5 support) the following error was being reported:
```
Error FS0010: Unexpected symbol '.' in member definition. Expected 'with', '=' or other token. (FS0010) (Fantomas.Tests)
```

Fantomas.Tests: fix build with VS4Mac

---

src/Fantomas.Tests/FunctionDefinitionTests.fs
src/Fantomas.Tests/LetBindingTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Context.fs
src/Fantomas/TriviaContext.fs
src/Fantomas/TriviaHelpers.fs

Both style guides ([MS](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#place-parameters-on-a-new-line-for-long-definitions), [GR](https://github.com/G-Research/fsharp-formatting-conventions#long-function-signatures)) have very strict rules to what should have when a function signature is getting longer than the `max_length`.
The current implement for this is a bit in `genExprSepEqPrependType` and `genPatWithReturnType `.
This was hard to maintain as the information had to be present in both functions and especially the MS way of doing things is rather hard.
So I've split it up into four functions. I've deliberately chosen for some repetition within those functions as it will be beneficial to solve future bugs.
Fixes #1218

Refactored LetBindings

---

src/Fantomas.Tests/IfThenElseTests.fs
src/Fantomas/CodePrinter.fs

Don't print if/then/else as short when ifBranch is SynExpr.IfThenElse

---

src/Fantomas.Tests/AppTests.fs
src/Fantomas.Tests/ClassTests.fs
src/Fantomas.Tests/CommentTests.fs
src/Fantomas.Tests/ComputationExpressionTests.fs
src/Fantomas.Tests/DotGetTests.fs
src/Fantomas.Tests/ElmishTests.fs
src/Fantomas.Tests/LambdaTests.fs
src/Fantomas.Tests/LetBindingTests.fs
src/Fantomas.Tests/PatternMatchingTests.fs
src/Fantomas.Tests/RecordTests.fs
src/Fantomas.Tests/SpaceBeforeLowercaseInvocationTests.fs
src/Fantomas.Tests/SpaceBeforeUppercaseInvocationTests.fs
src/Fantomas.Tests/StringTests.fs
src/Fantomas.Tests/SynExprNewTests.fs
src/Fantomas.Tests/SynExprSetTests.fs
src/Fantomas.Tests/TupleTests.fs
src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas.Tests/TypeProviderTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs

It looks like both style guides are about to land on the same conclusion in #1217.
So I wanted to add a small example of how this could work in Fantomas.
Once both style guides are merged, I can continue working on this.
A couple of things to consider;

Clarify constructors

---

src/Fantomas.Tests/AppTests.fs
src/Fantomas/CodePrinter.fs

Add space between function call inside DotIndexedGet

---

src/Fantomas.Tests/SpaceBeforeClassConstructorTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs

I created two tests to check the case separately with _new_ and _inherit_, plus a test with the original issue code.
I would like help to know what to do for each case.
For the _inherit_ test, analyzing the [tree](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQAuAngA6ww0VgHMAFAEowAXgA6yCBBQALWACdEXMFWSIAtrUmQQAXyA) I have an implicit inherit, called in ```genMemberDefn``` as ```MDImplicitInherit``` on ```CodePrinter.fs``` .  The solution would be to compare if _ctx.Config.SpaceBeforeClassConstructor_ is set and if it is the case insert a space after ```GenType``` on line 3939 and ignore the  ```addSpaceAfterType``` method.
For the _new_ test, I'm not sure, when I see the …

WIP fix 964

---

src/Fantomas.Tests/ComputationExpressionTests.fs
src/Fantomas.Tests/LazyTests.fs
src/Fantomas/CodePrinter.fs

Use atCurrentColumn when parenthesis hold a LetOrUse expression

---

src/Fantomas.Tests/ListTests.fs
src/Fantomas/CodePrinter.fs

This PR adds a missing `genTriviaFor SynExpr_ArrayOrList` in the expression printer so that comments before and after empty array and list literals are preserved. (The new "comment after empty list" test passed before the printer change, but the other three failed.)
Thanks @nojaf for pointing out where the problem was!
Resolves #1281.

Preserve comments before and after empty arrays and lists

---

src/Fantomas.Tests/SynConstTests.fs
src/Fantomas.Tests/TokenParserTests.fs
src/Fantomas/TokenParser.fs

Don't close string when there is a triple backslash before the double quote

---

src/Fantomas.Tests/TypeProviderTests.fs
src/Fantomas/CodePrinter.fs

Add space before type provider named argument.

---

src/Fantomas.Tests/RecordTests.fs
src/Fantomas/CodePrinter.fs

Don't indent static member too far if record has access modifier

---

src/Fantomas.Tests/TokenParserTests.fs
src/Fantomas.Tests/TriviaTests.fs
src/Fantomas/TokenParser.fs

Improves #1272, this PR adds some more restrictions on when a constant value should be considered trivia.
In short, Fantomas cannot always trust the values of string, numbers and characters that are found in the Untyped AST.
That is why these are picked up via the F# tokens.
However, all strings, numbers and characters were detected all the time.
In this PR, we are only detecting them as trivia if they are indeed special cases.

Stricter trivia selection.

---

src/Fantomas.Tests/ClassTests.fs
src/Fantomas.Tests/InterfaceTests.fs
src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Trivia.fs

Keep both keywords in abstract member definitions.

---

src/Fantomas.Tests/ComputationExpressionTests.fs
src/Fantomas/CodePrinter.fs

Keep newline above match bang.

---

src/Fantomas.Tests/SynExprSetTests.fs
src/Fantomas/CodePrinter.fs

Keep new line before SynExpr.DotIndexedSet.

---

src/Fantomas.Tests/ControlStructureTests.fs
src/Fantomas/CodePrinter.fs

Keep new line before SynExpr.For.

---

src/Fantomas.Tests/TupleTests.fs
src/Fantomas/CodePrinter.fs

Put comma upfront when SynExpr.IfThenElse is inside Tuple.

---

src/Fantomas.Tests/IfThenElseTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs

Put SynExpr.DotGet atCurrentColumn in if expression

---

src/Fantomas.Tests/NewlineBetweenTypeDefinitionAndMembersTests.fs
src/Fantomas/CodePrinter.fs

for NewlineBetweenTypeDefinitionAndMembers setting. Fixes #1346.

Take all SynMemberDefn cases into account when printing newline

---

src/Fantomas.Tests/ClassTests.fs
src/Fantomas.Tests/InterfaceTests.fs
src/Fantomas.Tests/ModuleTests.fs
src/Fantomas.Tests/RecordTests.fs
src/Fantomas.Tests/SignatureTests.fs
src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas/CodePrinter.fs

Fixes #1362.
@Smaug123 having the arrows at the start or at the end is not really a big deal for Fantomas.

Revisit long members in a type declaration.

---

src/Fantomas.Tests/CommentTests.fs
src/Fantomas.Tests/TupleTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Context.fs
src/Fantomas/SourceParser.fs

Keep tuple trivia while formatting

---

src/Fantomas.Tests/IfThenElseTests.fs
src/Fantomas.Tests/SynExprNewTests.fs
src/Fantomas/CodePrinter.fs

Fixes #1241.
In #1158 I introduced a check to capture an infix application inside the parenthesis.
This was assuming that the parenthesises were part of [SynExpr.New](https://fsharp.github.io/FSharp.Compiler.Service/reference/fsharp-compiler-syntaxtree-synexpr.html).
This check was a bit naive as that expression can occur in other places as well.
(Part of the IfThenElse in this case).
Then in #1256, I introduce some active patterns `NewTuple` and `AppTuple` that are the only valid use cases for the `genNamedArgumentExpr` function.
This PR fixes this.

Remove invalid check for named arguments.

---

src/Fantomas.CoreGlobalTool.Tests/CheckTests.fs
src/Fantomas.CoreGlobalTool.Tests/ExitCodeTests.fs
src/Fantomas.CoreGlobalTool.Tests/Fantomas.CoreGlobalTool.Tests.fsproj
src/Fantomas.CoreGlobalTool.Tests/TestHelpers.fs
src/Fantomas.CoreGlobalTool/Program.fs

fix #1340 
Running `Fantomas.CoreGlobalTool` to format a file without the `--check` argument, it does the treatment in the else listed below, calling the appropriate function given type of `inputPath` and `outputPath`.
https://github.com/fsprojects/fantomas/blob/d22dc764910040fd70412c3f3c674c6f4a5a1250/src/Fantomas.CoreGlobalTool/Program.fs#L386-L406
The problem is that when an error occurred in one of these functions, it was treated locally but not propagated, 
so the `try/with` condition that changes the error code to 1 is never achieved.
The ideal solution would be to show only the error messages in the last `try\with` and add tests for each function in the `match` expression, besides the simple test that I inserted.
What do you think @nojaf ?

add missing raise for formatting functions 

---

src/Fantomas.CoreGlobalTool/Program.fs

This bad practice is equivalent to doing `throw ex;` instead of `throw`
in C#: you lose the original error stack info.

Rather use reraise() instead of raising same captured exception

---

docs/Documentation.md

Following https://stackoverflow.com/a/42345379/1623521
Fixes https://github.com/fsprojects/fantomas/issues/1207

Documentation.md: add pre-commit hook sample

---

src/Fantomas.Tests/TriviaTests.fs
src/Fantomas/AstTransformer.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Trivia.fs
src/Fantomas/TriviaHelpers.fs
src/Fantomas/TriviaTypes.fs

Related to #1372. 
Characters in F# will always be `SynConst.Char`, we never consider using SynConst as trivia nodes so that is why we worked with the parent nodes (SynExpr.Const and SynPat.Const). However, the is not correct and we should use the appropriate nodes instead.

Add SynConst nodes to TriviaNodes.

---

src/Fantomas.Tests/ClassTests.fs
src/Fantomas.Tests/CompilerDirectivesTests.fs
src/Fantomas.Tests/ControlStructureTests.fs
src/Fantomas.Tests/DotGetTests.fs
src/Fantomas.Tests/DotIndexedGetTests.fs
src/Fantomas.Tests/DotIndexedSetTests.fs
src/Fantomas.Tests/Fantomas.Tests.fsproj
src/Fantomas.Tests/FunctionDefinitionTests.fs
src/Fantomas.Tests/LetBindingTests.fs
src/Fantomas.Tests/LongIdentWithDotsTests.fs
src/Fantomas.Tests/OperatorTests.fs
src/Fantomas.Tests/RecordTests.fs
src/Fantomas.Tests/SpaceBeforeUppercaseInvocationTests.fs
src/Fantomas.Tests/TypeProviderTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Context.fs
src/Fantomas/SourceParser.fs

In this PR I removed `IsInsideDotGet` and `IsInsideDotIndexed` from the ASTContext.
These settings introduce a lot of issues as you constantly need to set and reset the properties accordingly.
To resolve the need for these properties I created some more fine-grained active patterns.
Most notable the `DotGet` family of expressions has been split up into different use cases.
They now also cover the recent [MS style guide recommendations](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-constructors-static-members-and-member-invocations).
Fixes #1401.

Remove IsInsideDotGet and IsInsideDotIndexed

---

src/Fantomas/CodePrinter.fs

The string interpolation usage breaks the online tool.

Remove string interpolation in CodePrinter.fs.

---

src/Fantomas.Tests/MultiLineLambdaClosingNewlineTests.fs
src/Fantomas/CodePrinter.fs

Only take configuration into account for space after function name in MultiLineLambdaClosingNewline

---

src/Fantomas.Tests/MultilineBlockBracketsOnSameColumnRecordTests.fs
src/Fantomas.Tests/RecordTests.fs
src/Fantomas/CodePrinter.fs

Don't double unindent when record has access modifier.

---

src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas/CodePrinter.fs

Add indent and newline for multiline SynExpr of SynMemberDefn.AutoProperty. 

---

RELEASE_NOTES.md
src/Fantomas.CoreGlobalTool.Tests/Fantomas.CoreGlobalTool.Tests.fsproj
src/Fantomas.CoreGlobalTool/Fantomas.CoreGlobalTool.fsproj
src/Fantomas.Extras/Fantomas.Extras.fsproj
src/Fantomas.Tests/DotGetTests.fs
src/Fantomas.Tests/Fantomas.Tests.fsproj
src/Fantomas/CodePrinter.fs
src/Fantomas/Fantomas.fsproj

Only add a space at the end of a long nested DotGet chain. 

---

src/Fantomas.Tests/MultilineBlockBracketsOnSameColumnRecordTests.fs
src/Fantomas/CodePrinter.fs

fix #1396 
adding `atCurrentColumnIndent` before the `genExpr` as suggested.

add atCurrentColumnIndent for record multiline expression

---

src/Fantomas.Tests/TokenParserTests.fs
src/Fantomas.Tests/TriviaTests.fs
src/Fantomas/CodeFormatterImpl.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Context.fs
src/Fantomas/RangeHelpers.fs
src/Fantomas/TokenParser.fs
src/Fantomas/Trivia.fs
src/Fantomas/TriviaTypes.fs

Replace RangeHelpers.rangeEq with actual equals function of FCS.
https://github.com/dotnet/fsharp/blob/501f7551636f9ab5585ad18e7908b78760274d69/src/fsharp/range.fs#L337
@jindraivanek any thoughts on the MkRange field I added in Context?

Use equals from FCS to compare ranges.

---

src/Fantomas.Tests/PatternMatchingTests.fs
src/Fantomas/CodePrinter.fs

Limit WITH keyword range from start of SynExpr til the start of the first Clause.

---

src/Fantomas.Tests/DotGetTests.fs
src/Fantomas.Tests/DotIndexedGetTests.fs
src/Fantomas.Tests/SynExprSetTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs

Take SynExpr.TypeApp into account with long DotGet chains.

---

src/Fantomas.Tests/InterpolatedStringTests.fs
src/Fantomas/TokenParser.fs

New lines were not being preserved when combining the string tokens of an interpolated string expression. If consecutive tokens are on different lines, then we add an additional NewLine in between.
Fixes #1451

Preserve new lines in string portion of interpolated string

---

src/Fantomas.Tests/ElmishTests.fs
src/Fantomas.Tests/Fantomas.Tests.fsproj
src/Fantomas.Tests/IfThenElseTests.fs
src/Fantomas.Tests/MultilineFunctionApplicationsInConditionExpressionsTests.fs
src/Fantomas.Tests/PatternMatchingTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Context.fs
src/Fantomas/SourceParser.fs

As the style for multiline function applications can lead to F# compiler warnings when applied inside `if`, `match` or `when` expressions, I've applied a different style to cope with this.
The formatted result is now valid F# code, though it might compromise the esthetics of the code in some cases.
Correct results outweigh the stylistic aspect, this is an acceptable premise.
Fixes #1403
Fixes #1406
Fixes #1402
Fixes #1390

Alternative function application inside match expression.

---

src/Fantomas.Tests/AppTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs

Apply alternate function application style if function contains parenthesis. 

---

src/Fantomas.Tests/HashDirectiveTests.fs
src/Fantomas/CodePrinter.fs

Don't consider long hash directives to be multiline.

---

README.md

I moved the command line for installing fantomas as a local tool into the paragraph. That should make it a bit more obvious and should prevent people from clicking the link to nuget and using the command line shown there, which is a global install.
No hard feelings, if you think, it was better before ;-)

fantomas local tool install command is more obvious

---

src/Fantomas.Tests/MultiLineLambdaClosingNewlineTests.fs
src/Fantomas/CodePrinter.fs

Only add closing parenthesis on next line if lambda is multiline.

---

src/Fantomas.Tests/InterpolatedStringTests.fs
src/Fantomas/CodePrinter.fs

Add space before interpolated string in prefix application.

---

src/Fantomas.Tests/SpaceBeforeLowercaseInvocationTests.fs
src/Fantomas.Tests/SpaceBeforeUppercaseInvocationTests.fs
src/Fantomas/CodePrinter.fs

Don't add space between function and unit/parenthesis when argument of prefix app.

---

src/Fantomas.Tests/ClassTests.fs
src/Fantomas/CodePrinter.fs

Don't add newline between empty multiline class constructor. 

---

docs/Documentation.md

* Remove two `.editorconfig` entries that seem to be unused.
* Minor ordering change to align with FormatConfig.fs.

Sync Documentation.md with FormatConfig.fs

---

src/Fantomas/CodeFormatterImpl.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Context.fs
src/Fantomas/SourceParser.fs
src/Fantomas/SourceTransformer.fs
src/Fantomas/TokenParser.fs
src/Fantomas/Trivia.fs
src/Fantomas/TriviaTypes.fs

This PR captures the tokens for `SynExpr.LibraryOnlyILAssembly` and prints the collected trivia.
This removes the need to have positions in ASTContext.
Also removed unused field `TopLevelModuleName`.
Fixes #594

Remove getByLookup function in SourceTransformer.fs

---

src/Fantomas.Tests/SynConstTests.fs
src/Fantomas/TokenParser.fs

Fixes #1508 .
And maybe `\a`, `\b`, `\f` and `\v` too? (because I don't know about these escapes so didn't touch.)

Keep hex escapes in string literals (#1508)

---

src/Fantomas.Tests/ElmishTests.fs
src/Fantomas/CodePrinter.fs

Don't indent and add newline when multiline Feliz expression has no children

---

src/Fantomas.Tests/ComputationExpressionTests.fs
src/Fantomas.Tests/IfThenElseTests.fs
src/Fantomas.Tests/PatternMatchingTests.fs
src/Fantomas/CodePrinter.fs

Indented one step from the match/|.

---

src/Fantomas/AstTransformer.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Fantomas.fsproj
src/Fantomas/SourceTransformer.fs
src/Fantomas/Trivia.fs
src/Fantomas/TriviaTypes.fs
src/Fantomas/Utils.fs

Refactored ASTTransformer:
- optimized for tail recursion, heavily inspired by https://www.gresearch.co.uk/article/advanced-recursion-techniques-in-f/
- Threw out ASTNodes that we never use.
- Threw out properties and FsAstNode as they are not used.
Please review if I missed something.

Refactor ASTTransformer

---

src/Fantomas.Tests/ListTests.fs
src/Fantomas/AstTransformer.fs

Following up on the last changes to ASTTransformer.
I had to change `SynExpr.Sequential` because it was still blowing the stack.
The [AST](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQ2wAuYKABwCufALwAdAE7jkECAG0APgCYA3AAZVAWgCMqtVoMBmVXsMbtADm1mA7FZt2HW%2BwYAs2j1oBs2gJwWhpouNr66wcoArNomuvaaahEBhtFa1ua6AcFG6crJqcoeBmZGmhHpbrHKamY6BspVsW61BpFmkWHt9obJRvX50WbKuclu%2BZ2x3t1uwTrBbl59MdO93batXtXahTFDYW6pB54FTWaWBf7ZZm7dltfzsW3a3tdm3l7ewQXJOulzXrZgt50pFYjpupE-up7CVep1of5kp8bLFbLVwf50d0jPD%2BtsTGY-ECfuV-F4-MUwcouqFtmtbtdUrZRkibB5Zls0mtUlNPGCdGCxmyvG50vCvDpIqkBWFzijOpFujohSkbGK3tiJeo-nkbOoDD8jlo-AVagttoTKdLqc9uu9ArYJbZpeprbNvL1DpbtE8XGFvGDLBKA2rRo90kG6WylTcfZt4bLwz7rRKjbZZYTblCmb5gpGtJFZup4dLQdpnTZDrMOjYonqfjGlZZq2E-Jt1NcfpYlbEfn5 …

Run `long array sequence` test on CI.

---

src/Fantomas.Tests/PatternMatchingTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs

Edge case scenario but the extra space is required.
Fixes #1522.

Add extra space before pipe if multiline line or pattern in list/array

---

src/Fantomas.Tests/DotGetTests.fs
src/Fantomas/CodePrinter.fs

Further indent multiline DotGet inside infix expression.

---

README.md

Just a small link update for the changed [repo](https://github.com/JetBrains/resharper-fsharp) name.

Readme: update resharper-fsharp repo name

---

src/Fantomas.Tests/CompilerDirectivesTests.fs
src/Fantomas.Tests/TokenParserTests.fs
src/Fantomas.Tests/TriviaTests.fs
src/Fantomas/Context.fs
src/Fantomas/Queue.fs
src/Fantomas/TokenParser.fs

Combines a trivia combination of define, empty lines, define into one trivia.
[Example](https://fsprojects.github.io/fantomas-tools/#/trivia?data=N4KABGBEDGD2AmBTSAuKAbRAXMAPMAvADoBORAdhBAMQCWAZmACICiAQgKoDipFVYABxK1yWepSKRWnHpF6Uq1ROXgN5-ABQBKSABpwUJPRGIAzqih6DkWqYBip2hfoBDdKcQgAvkA).

Collect empty define block as single trivia.

---

src/Fantomas.Tests/DotGetTests.fs
src/Fantomas/CodePrinter.fs

DotGetApp inside multiline infix expression should indent.

---

src/Fantomas.Tests/SignatureTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceTransformer.fs

Collect newlines between signature module declaration consistently.

---

src/Fantomas.Tests/DynamicOperatorTests.fs
src/Fantomas.Tests/PatternMatchingTests.fs
src/Fantomas/CodePrinter.fs

Only add parenthesis when operator length is equal or greater than indent size. 

---

src/Fantomas.Tests/ListTests.fs
src/Fantomas.Tests/MultilineBlockBracketsOnSameColumnArrayOrListTests.fs
src/Fantomas/CodePrinter.fs

Print trivia assigned to brackets of ArrayOrListOfSeqExpr. 

---

src/Fantomas.Tests/MultilineFunctionApplicationsInConditionExpressionsTests.fs
src/Fantomas.Tests/PatternMatchingTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Context.fs

Put arrow on next line if when expression is multiline.

---

src/Fantomas.Tests/SignatureTests.fs
src/Fantomas/AstTransformer.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs

Print trivia for ident of ValSpfn. 

---

src/Fantomas.Tests/LambdaTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs

Print trivia before SynExpr.Lambda when wrapped in parenthesis.

---

src/Fantomas.Tests/SignatureTests.fs
src/Fantomas/CodePrinter.fs

Print inline internal keywords in the correct order for val. 

---

src/Fantomas.Tests/PatternMatchingTests.fs
src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas.Tests/UnionTests.fs
src/Fantomas/Utils.fs

Fixes #1589.
Fixes #1484.
Fixes #1483.

Don't remove newlines when comparing hash chunks. 

---

docs/Documentation.md
src/Fantomas.Tests/BlankLinesAroundNestedMultilineExpressions.fs
src/Fantomas.Tests/Fantomas.Tests.fsproj
src/Fantomas.Tests/KeepIndentInBranch.fs
src/Fantomas.Tests/NewlinesAroundInnerMultilineExpressions.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Context.fs
src/Fantomas/FormatConfig.fs

Related to #1370.
I still haven't figured out what the boundaries of this setting are.
Full transparency, this might make it into v4.5 or it might be removed altogether.
This PR is an experiment and needs further triaging.
@Smaug123 would this be something GR would enable internally?

Feature BlankLinesAroundNestedMultilineExpressions

---

src/Fantomas.Tests/IfThenElseTests.fs
src/Fantomas/CodePrinter.fs

Keep comment after elif expression before then keyword.

---

src/Fantomas.Tests/OperatorTests.fs
src/Fantomas/CodePrinter.fs

if/then/else in infix should always be multiline.

---

src/Fantomas.Tests/LetBindingTests.fs

Fixes #1610.
The fix is the same as https://github.com/fsprojects/fantomas/pull/1617.

Add regression test. 

---

src/Fantomas.Tests/LetBindingTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs

Correct prefix of synbinding in collected computation expression.

---

src/Fantomas.Tests/SignatureTests.fs
src/Fantomas/CodePrinter.fs

Fixes #1563.
We already took this into account for implementation files.
I'll reflect the style guides in a future PR.

Apply same union case bar rule to signature files. 

---

src/Fantomas.Tests/LambdaTests.fs
src/Fantomas.Tests/MultiLineLambdaClosingNewlineTests.fs
src/Fantomas.Tests/StructTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs

Fixes #1631.
```
| Lambda of
fromMethod: bool *
inLambdaSeq: bool *
args: SynSimplePats *
body: SynExpr *
parsedData: (SynPat list * SynExpr) option *
range: range
```
`parsedData` contains all the information necessary to print out the parameters of a lambda (destructed or not).
This simplifies Fantomas a bit like the whole `ComplexPats` dance can be skipped.

Merge DesugaredLambda and Lambda to one active pattern.

---

src/Fantomas.Tests/LetBindingTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Context.fs

Fixes #1611 following the suggestion by @nojaf.
I went a little further and changed the `indentIfNeeded` function so that, when it does trigger, it adds an extra indent level instead of just one space.
It seems to make sense to me, it looks better, and it didn't break any test, but the only other place where the function is invoked is in the very high-level `genApp` function so I'm not sure if there's a specific case in mind where indenting by exactly 1 was the preferred behaviour. If so, I could add an extra argument to the function.

Multiline type parameter arguments inside indentation (#1611)

---

src/Fantomas.Tests/CompilerDirectivesTests.fs
src/Fantomas.Tests/DotGetTests.fs
src/Fantomas.Tests/RecordTests.fs
src/Fantomas/CodePrinter.fs

Apply genMultilineFunctionApplicationArguments when expression is long inside DotGetApp. 

---

src/Fantomas.Tests/MultilineBlockBracketsOnSameColumnArrayOrListTests.fs
src/Fantomas/CodePrinter.fs

Indent multiline expression in ForEach. 

---

src/Fantomas.Tests/IfThenElseTests.fs
src/Fantomas/AstTransformer.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Context.fs
src/Fantomas/Fantomas.fsproj
src/Fantomas/SourceParser.fs
src/Fantomas/TriviaContext.fs

Related to #1648.
This is something I discovered regardless of the `keep indent` question.

Correct Elif expression range when there is only a single elif.

---

src/Fantomas.Tests/DotGetTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs

Keep lambda at same line in multiline dotget.

---

src/Fantomas.Tests/PatternMatchingTests.fs
src/Fantomas/CodePrinter.fs

Don't add unnecessary parenthesis around SynPat.IsInst. 

---

docs/Documentation.md

fix: AlternativeLongMemberDefinitions changed in #1334 but were not reflected in documentation.
Closes: #1666

Update Documentation to align with AlternativeLongMemberDefinitions

---

src/Fantomas.Tests/InterfaceTests.fs
src/Fantomas/CodePrinter.fs

Reset IsFirstChild of ASTContext before printing interface members. 

---

src/Fantomas.CoreGlobalTool.Tests/ConfigTests.fs
src/Fantomas.Tests/TestHelpers.fs
src/Fantomas.Tests/UtilsTests.fs
src/Fantomas/CodeFormatterImpl.fs
src/Fantomas/Utils.fs

Respect end_of_line when formatting multiple code branches. 

---

src/Fantomas.Tests/AttributeTests.fs
src/Fantomas.Tests/ColMultilineItemTests.fs
src/Fantomas.Tests/CommentTests.fs
src/Fantomas.Tests/CompilerDirectivesTests.fs
src/Fantomas.Tests/Fantomas.Tests.fsproj
src/Fantomas.Tests/SynConstTests.fs
src/Fantomas.Tests/TriviaTests.fs
src/Fantomas/AstExtensions.fs
src/Fantomas/AstTransformer.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Context.fs
src/Fantomas/Fantomas.fsproj
src/Fantomas/Queue.fs
src/Fantomas/SourceParser.fs
src/Fantomas/TokenParser.fs
src/Fantomas/Trivia.fs
src/Fantomas/TriviaTypes.fs

Fixes #1649.
This PR has a bit of an impact, I would like to hear your opinion @jindraivanek.
So, in general, modules and namespace can have a bit of a weird range.
For example an empty named module in [a signature file](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmAC4BOArrPhJAMYD2cFkAtu7QDawwxVqwBGAQ2oAdachlTkAekVhWACzBpWXQWy47klSCAC%2BQA).
The range is influenced by the code comment, so that leads to problems here and there.
In short, it is better not to use them as trivia candidates.
To overcome this limitation, I constructed a range based on the `LongIndent` of a `SynModuleOrNamespace` or `SynModuleOrNamespaceSig`.
Trivia can safely be attached to this node, and then printed for the entire module name (keywords included).
See
```fsharp …
```

Don't use module or namespace as trivia candidate. 

---

src/Fantomas.Tests/CommentTests.fs
src/Fantomas.Tests/TriviaTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/TokenParser.fs
src/Fantomas/TriviaTypes.fs

Fixes #1671, depends on #1656.
Improved the trivia detection via the F# tokens.
Specifically, the detection if a code comment is on a single line or after the source.

Optimize comment after source code detection.

---

src/Fantomas.Tests/ColMultilineItemTests.fs
src/Fantomas.Tests/KeepIndentInBranchTests.fs
src/Fantomas/CodePrinter.fs

Fixes #1671, depends on #1672 (yes, I'm aware this is beginning to become a mess).
ColMultilineItems are correctly detected when `SynExpr.LetOrUse` is nested inside a `SynExpr.Sequential`.
This issue was a good catch.

Properly collect ColMultilineItems for nested LetOrUse in Sequential

---

src/Fantomas.Tests/SignatureTests.fs
src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas/CodePrinter.fs

Long multiline prefix type name should be indented far enough.

---

src/Fantomas.Tests/InterpolatedStringTests.fs
src/Fantomas/CodePrinter.fs

Don't indent multiline interpolated string expressions. 

---

src/Fantomas.Tests/SynConstTests.fs
src/Fantomas/TokenParser.fs

WIP keep \t escaped inside strings

---

src/Fantomas.Tests/AppTests.fs
src/Fantomas/CodePrinter.fs

Don't add newlines to short partial applications

---

CONTRIBUTING.md

I got a little confused while running through the instructions. This fixes the confusion.
Note that I couldn't find any way to specify `dotnet test --filter 'record declaration'` with a space in the name. I tried `%20`, double quotes, and adding escape characters. I don't know if it works on powershell, but it does not seem to work at all when using bash. The error was:
```
An exception occurred while invoking executor 'executor://nunit3testexecutor/': Unexpected Word 'declaration' at position 7 in selection expression.
```
Instead, I specified an issue number.

Small fixes

---

RELEASE_NOTES.md
src/Fantomas.CoreGlobalTool.Tests/Fantomas.CoreGlobalTool.Tests.fsproj
src/Fantomas.CoreGlobalTool/Fantomas.CoreGlobalTool.fsproj
src/Fantomas.Extras/Fantomas.Extras.fsproj
src/Fantomas.Tests/ColMultilineItemTests.fs
src/Fantomas.Tests/Fantomas.Tests.fsproj
src/Fantomas/Context.fs
src/Fantomas/Fantomas.fsproj

Leading newline because of trivia does not item multiline. 

---

src/Fantomas.Tests/PatternMatchingTests.fs
src/Fantomas/CodePrinter.fs

Detect multiline clause by UnIndentBy event.

---

src/Fantomas.Tests/KeepIndentInBranchTests.fs
src/Fantomas.Tests/LetBindingTests.fs
src/Fantomas/CodePrinter.fs

Respect KeepIndentInBranch with multiple levels of nested LetOrUse or Sequential expressions.

---

src/Fantomas.Tests/MultiLineLambdaClosingNewlineTests.fs
src/Fantomas.Tests/OperatorTests.fs
src/Fantomas/CodePrinter.fs

Avoid offset error when a comment appears before a match statement ininfix expression.

---

src/Fantomas.Tests/KeepIndentInBranchTests.fs
src/Fantomas/CodePrinter.fs

KeepIndentInBranch for value bindings.

---

src/Fantomas.Tests/MultiLineLambdaClosingNewlineTests.fs
src/Fantomas/CodePrinter.fs

Always add newline if expression lambda body expression is multiline in MultiLineLambdaClosingNewline setting.

---

src/Fantomas.Tests/ClassTests.fs
src/Fantomas/CodePrinter.fs

Print trivia for SynPat_Paren when member binding is multiline paren tuple. 

---

src/Fantomas.Tests/IfThenElseTests.fs
src/Fantomas/CodePrinter.fs

Add parenthesis if necessary in multiline if/then/else followed by infix operator. 

---

src/Fantomas.Tests/LambdaTests.fs

Add regression test for lambda argument in multiline function application.

---

src/Fantomas.Tests/AppTests.fs
src/Fantomas/CodePrinter.fs

Reset the max line length after printing the interpolated expression.

---

src/Fantomas.Tests/KeepIndentInBranchTests.fs
src/Fantomas/SourceParser.fs

Consider all function applications as short branch.

---

src/Fantomas.Tests/UnionTests.fs
src/Fantomas/CodePrinter.fs

Only print union case fields when there are any. 

---

src/Fantomas.Tests/CompilerDirectivesTests.fs
src/Fantomas.Tests/TokenParserTests.fs
src/Fantomas/TokenParser.fs

Verbatim string is ignore for hash directive scan.

---

src/Fantomas.Tests/IfThenElseTests.fs
src/Fantomas/CodePrinter.fs

Only format to alternative function application in if expression when application is multiline. 

---

src/Fantomas.Tests/LambdaTests.fs
src/Fantomas/SourceParser.fs

Get lambda body expression correctly. 

---

src/Fantomas.Tests/DotGetTests.fs
src/Fantomas/CodePrinter.fs

Process function applications the same way as if the DotGet would not have a lambda. 

---

src/Fantomas.Tests/KeepIndentInBranchTests.fs
src/Fantomas.Tests/PatternMatchingTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/TriviaContext.fs
src/Fantomas/Utils.fs

Apply same alternative formatting for match expression as in if expressions.

---

src/Fantomas.Tests/MultiLineLambdaClosingNewlineTests.fs
src/Fantomas/CodePrinter.fs

Consider MatchLambda as single lambda when MultiLineLambdaClosingNewline is enabled.

---

src/Fantomas.CoreGlobalTool.Tests/CheckTests.fs
src/Fantomas.CoreGlobalTool.Tests/IgnoreFilesTests.fs
src/Fantomas.CoreGlobalTool/Program.fs

When processing an entire folder with a command such as this:
```
fantomas --recurse .
```
the `.fantomasignore` file is effectively useless because the `processSourceString` function is generating a fixed file name of either `tmp.fs` or `tmp.fsi`. This file name is in turn used by a call to `IgnoreFile.isIgnoredFile` by `formatContentInternalAsync`, so a `.fantomasignore` file like this presents an issue:
```
*.fs
!/path/to/important.fs
```
Even when formatting `important.fs`, it will be "seen" as `tmp.fs` by `formatContentInternalAsync` and therefore ignored.
This PR is an intuitive attempt at fixing the issue with minimal change. That said, I do feel like the ignore check is possibly occurring in the wrong place and would be better hoisted to an outer layer of the system. In fact, …

Honor .fantomasignore file when processing a folder

---

src/Fantomas.Tests/DynamicOperatorTests.fs
src/Fantomas.Tests/FormatAstTests.fs
src/Fantomas.Tests/InterfaceTests.fs
src/Fantomas.Tests/LetBindingTests.fs
src/Fantomas.Tests/ModuleTests.fs
src/Fantomas.Tests/OperatorTests.fs
src/Fantomas.Tests/SynConstTests.fs
src/Fantomas.Tests/TokenParserBoolExprTests.fs
src/Fantomas.Tests/TokenParserTests.fs
src/Fantomas.Tests/UnionTests.fs
src/Fantomas.Tests/UtilsTests.fs

As part of my [previous PR](https://github.com/fsprojects/fantomas/pull/1838), it came to light that there are tests with capitalized names where the guidelines state they should be lowercase. This PR fixes all instances, apart from those test names that start with acronyms or symbol names.

Start test names with lowercase where relevant

---

src/Fantomas.Tests/FSharpScriptTests.fs
src/Fantomas.Tests/Fantomas.Tests.fsproj
src/Fantomas.Tests/FormatConfigEditorConfigurationFileTests.fs

Making sure all IO related tests are executed in a newly created subfolder of the temp folder.
Some tests interfered with each other on random occasions due to file locks on the `<TempFolder>\.editorconfig` file.

Refactor FSharpScriptTests to use helpers from FormatConfigEditorConfigurationFileTests.

---

src/Fantomas/AstTransformer.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs
src/Fantomas/TokenParser.fs
src/Fantomas/TriviaTypes.fs

SynExpr.MatchLambda holds the range of the `function` keyword.
So there is no need to get this information from the F# tokens.

Use function keyword range from AST instead of from token.

---

src/Fantomas.Tests/CompilerDirectivesTests.fs
src/Fantomas/TokenParser.fs

This one was tricky to debug, at least for me. The root of the problem was that `getTokenizedHashes`' inner `processLine` function was rewriting some tokens with an offset, but not adjusting others. This meant that the significant whitespace ended up _before_ the `#if` rather than after it where it belonged.
Fixes #1866

Retain significant whitespace in nested, indented #if directives

---

src/Fantomas.Tests/AppTests.fs
src/Fantomas.Tests/CommentTests.fs
src/Fantomas.Tests/CompilerDirectivesTests.fs
src/Fantomas.Tests/ComputationExpressionTests.fs
src/Fantomas.Tests/ControlStructureTests.fs
src/Fantomas.Tests/DisableElmishTests.fs
src/Fantomas.Tests/DotGetTests.fs
src/Fantomas.Tests/ElmishTests.fs
src/Fantomas.Tests/IfThenElseTests.fs
src/Fantomas.Tests/KeepIndentInBranchTests.fs
src/Fantomas.Tests/LambdaTests.fs
src/Fantomas.Tests/LetBindingTests.fs
src/Fantomas.Tests/ListTests.fs
src/Fantomas.Tests/MultiLineLambdaClosingNewlineTests.fs
src/Fantomas.Tests/OperatorTests.fs
src/Fantomas.Tests/PatternMatchingTests.fs
src/Fantomas.Tests/RecordTests.fs
src/Fantomas.Tests/StringTests.fs
src/Fantomas.Tests/SynConstTests.fs
src/Fantomas.Tests/SynExprSetTests.fs
src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs
src/Fantomas/TriviaContext.fs

Hi @dsyme, in order to follow up on https://github.com/dotnet/docs/issues/25207, I've implemented the change in Fantomas to have a better idea of what the impact would be.
I'll explain the high-level gist of the implementation and perhaps you confirm if I understood the guidance correctly.
So, firstly I believe the guidance was focused around function applications where a lambda (be it SynExpr.Lambda or SynExpr.MatchLambda) is the last argument.
I've captured the nested SynExpr.App in an active pattern `(|AppWithLambda|_|)` and applied new logic to that exact shape of SynExpr. 
First, if the expression is short, we try to put it in one line.
```fsharp
functionName arg1 arg2 arg3 (fun arg4 -> bodyExpr)
```
If the `max_line_length` is crossed or the body is multiline, we apply alternative …

Style guide lambda

---

docs/Documentation.md

Remove mention of fsharp_infix_operator_expression_multiline_formatter as it was removed (#1232)
Resolves #1884

Update max_infix_operator_expression documentation

---

CONTRIBUTING.md
src/Fantomas/CodePrinter.fs

Added a small section about ASTContext, it should be avoided and I want to raise some awareness for newcomers.
Also threw in a few lines that Rider can be used, as we have a section on Ionide it could elude that you need to use VSCode which is not the case. //cc @auduchinok

Add warning about ASTContext and section on Rider.

---

src/Fantomas.Tests/ClassTests.fs
src/Fantomas.Tests/CommentTests.fs
src/Fantomas.Tests/FormatAstTests.fs
src/Fantomas.Tests/FunctionDefinitionTests.fs
src/Fantomas.Tests/InterfaceTests.fs
src/Fantomas.Tests/ModuleTests.fs
src/Fantomas.Tests/NewlineBetweenTypeDefinitionAndMembersTests.fs
src/Fantomas.Tests/NumberOfItemsRecordTests.fs
src/Fantomas.Tests/RecordTests.fs
src/Fantomas.Tests/SignatureTests.fs
src/Fantomas.Tests/SpecialConstructsTests.fs
src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas/CodePrinter.fs

Fixes https://github.com/fsprojects/fantomas/issues/1934

fix spacing for val and member in signatures

---

src/Fantomas.Tests/ClassTests.fs
src/Fantomas/CodePrinter.fs

Correct indentation after multi-line base constructor

---

src/Fantomas.Tests/ActivePatternTests.fs
src/Fantomas/SourceParser.fs

This fixes the issue with power operators in #1945
There is a bit of concerning duplication and divergence between OpName, OpNameFullInPattern, and OpNameFull before and after my change:
https://github.com/fsprojects/fantomas/blob/10f599c2d2cdeddcfb2c00b915aaf45b3a5f9be1/src/Fantomas/SourceParser.fs#L120-L175
that might need a bit of restructuring to avoid this popping up again in a slightly different place but this PR helps move the right way.

Fix power operator in code quotation pattern match

---

src/Fantomas.CoreGlobalTool/Daemon.fs
src/Fantomas.Extras/EditorConfig.fs
src/Fantomas/FormatConfig.fs

This adds the configuration meta information to the Fantomas Daemon.
The configuration response would look like:
```json
{
"settings": {
"indent_size": {
"type": "number",
"defaultValue": "4",
"category": "Indentation",
"displayName": "Indent spaces",
"description": "Number of spaces to use for indentation"
},
"max_line_length": {
"type": "number",
"defaultValue": "120",
"category": "Boundaries",
"displayName": "Maximum line length",
"description": "The column where we break to new lines"
},
"fsharp_semicolon_at_end_of_line": {
"type": "boolean",
"defaultValue": "false",
"category": "Convention",
"displayName": "Semicolon at end-of-line",
"description": "Forces a semicolon to be added to the end of a line"
},
"fsharp_space_before_parameter": {
"type": "boolean",
"defaultValue": "true", …
```

Config documentation

---

src/Fantomas.Tests/IndexSyntaxTests.fs
src/Fantomas/RangeHelpers.fs
src/Fantomas/SourceParser.fs

Fixes #1929.
@dsyme would you mind verifying if I stole the `isAdjacentTo` logic correctly from:
https://github.com/dotnet/fsharp/blob/main/src/fsharp/CheckExpressions.fs#L7886-L7901
and https://github.com/dotnet/fsharp/blob/699291aab8a3b5e877d9482cdf1c83808bdd8a9f/src/fsharp/range.fs#L280-L281
Thanks!

New Index syntax on raw list.

---

src/Fantomas.Tests/AttributeTests.fs
src/Fantomas/CodePrinter.fs

The world is a brighter place when a field of ASTContext is removed.
Fixes #1918 
Fixes #1874
Fixes #1898

Remove IsFirstChild from ASTContext.

---

build.fsx
src/Fantomas.Client/Fantomas.Client.fsproj
src/Fantomas.Client/FantomasToolLocator.fs
src/Fantomas.Client/LSPFantomasService.fs
src/Fantomas.Client/LSPFantomasServiceTypes.fs

In this PR, I'm adding a check to see if the process is still running.
Theoretically, this can only happen when the user kills the process by itself or something major unforeseen kills the process.
In any case, it worked on my machine.
I've also changed the Dispose implementation slightly as I noticed the processes weren't really killed.
I'm not sure how useful the `isCancellationRequested` check is.
@baronfel would you mind reviewing this one, please?
Thanks!

Restart fantomas-tool when process has exited.

---

src/Fantomas.Tests/SignatureTests.fs
src/Fantomas/AstExtensions.fs
src/Fantomas/AstTransformer.fs
src/Fantomas/CodePrinter.fs

Use FullRange for SynExceptionDefnRepr, SynExceptionSig and SynModuleSigDecl. 

---

build.fsx
src/Fantomas.Tests/OperatorTests.fs
src/Fantomas/CodePrinter.fs

Closes #1979 by forcing the use of a space between all Prefix Applications (typically operators) and any SynExpr.Const arguments.
This is a bit broader of a change than strictly speaking would be required. The only required change to prevent soundness bugs would be to detect if the const was a negative number in some form and apply spacing then, because the core bug is that removing the spacing transforms the expression from `+ (-2)` to `+- 2` in meaning, so the operator being applied changes.  I think it's reasonable to enforce a single-space everywhere, and if necessary we could encode this in the style guide.

apply spacing between operators and all SynExpr.Const

---

src/Fantomas.Tests/IndexSyntaxTests.fs
src/Fantomas/CodePrinter.fs

Move IndexWithoutDotExpr higher in the genExpr pattern match.

---

build.fsx
src/Fantomas.Client/FantomasToolLocator.fs

@baronfel this fixes the problem in Ionide where people have https://marketplace.visualstudio.com/items?itemName=formulahendry.dotnet-test-explorer installed.
Setting the environment variable again blows up the whole thing.

Verify if DOTNET_CLI_UI_LANGUAGE is already present.

---

src/Fantomas.Tests/KeepIndentInBranchTests.fs
src/Fantomas/SourceParser.fs

Pipe operator application with lambda is considered long for KeepIndentInBranch. 

---

src/Fantomas.CoreGlobalTool.Tests/DaemonTests.fs
src/Fantomas.CoreGlobalTool/Daemon.fs
src/Fantomas.Extras/EditorConfig.fs

Always first apply the editor config settings before overruling them.

Read editorconfig settings before overwriting settings with request configuration.

---

src/Fantomas.Tests/InterfaceTests.fs
src/Fantomas.Tests/SignatureTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/Context.fs

See #1991, the attempt was to rebase that PR with 4.6 branch.

Stars at end 2

---

src/Fantomas.Tests/ClassTests.fs
src/Fantomas/CodePrinter.fs

Print members after explicit class/end.

---

src/Fantomas.Tests/ClassTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs
src/Fantomas/SourceTransformer.fs

Format `x.Member with get()` as regular member binding. 

---

.fantomasignore
src/Fantomas.Tests/CommentTests.fs
src/Fantomas.Tests/ContextTests.fs
src/Fantomas.Tests/StringTests.fs
src/Fantomas/Context.fs
src/Fantomas/Utils.fs

Fixes #1941
Thanks for the pointer @jindraivanek

Don't trim end of line inside a String.

---

src/Fantomas.Tests/SynConstTests.fs
src/Fantomas/CodePrinter.fs

Fixes #560.
I didn't bother to add more tests for this as people shouldn't use StrictMode, to begin with.
Other than that there are also some vague ideas to restore the original string in the untyped tree.

Use SynStringKind to restore verbatim string in StrictMode.

---

src/Fantomas.Tests/LambdaTests.fs

Add regression test for comment after arrow in SynExpr.Lambda. 

---

src/Fantomas.Tests/CompilerDirectivesTests.fs

Add regression test for type definition in signature file wrapped with hash directives. 

---

src/Fantomas/AstTransformer.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/RangeHelpers.fs
src/Fantomas/SourceParser.fs
src/Fantomas/SourceTransformer.fs
src/Fantomas/TokenParser.fs
src/Fantomas/TriviaTypes.fs

The range of both `SynExpr.ArrayOrList` and `SynExpr.ArrayOrListComputed` includes the delimiters (`[`,`[|`,`|]`,`]`).
So, these can be added as main nodes instead of detecting them from the Fsharp tokens.
Main nodes are preferable over token types so this refactor optimizes trivia a bit.
It moves the mechanism from TokenParser to ASTTransformer which is a better way to deal with trivia anchors.
We can probably do something similar for records.

Remove LBRACK, LBRACK_BAR, RBRACK and BAR_RBRACK from TokenParser.

---

src/Fantomas.Tests/LambdaTests.fs
src/Fantomas/CodePrinter.fs

Fixes #2015.
@jindraivanek let me know if you want a release with this fix.

Add space after parenthesis function call with lambda argument.

---

src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas/AstTransformer.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs
src/Fantomas/TokenParser.fs
src/Fantomas/TriviaContext.fs
src/Fantomas/TriviaTypes.fs

Similar to https://github.com/fsprojects/fantomas/pull/2035 and https://github.com/fsprojects/fantomas/pull/2033.

Remove LPAREN and RPAREN from TokenParser.

---

src/Fantomas.Tests/StringTests.fs
src/Fantomas/TokenParser.fs

This is a fix when explicit "\000" unicode character is replaced by null character.
The test in this PR works both with "\000" and "?" as expected result however, written with the sprintf the "\000" is converted into "?" when formatting is applied. 
Fixes #2050

Adding 0 to be recognized as one of the escaped characters.

---

src/Fantomas.Tests/CompilerDirectivesTests.fs
src/Fantomas/CodePrinter.fs

Fix 2014:  separate ParsedHashDirective by a newline

---

src/Fantomas.Tests/LambdaTests.fs

@nojaf I think you are right, #1998 was fixed by #2036
Here's the regression test for #1998

Add regression test for #1998

---

src/Fantomas.Tests/LetBindingTests.fs
src/Fantomas.Tests/LongIdentWithDotsTests.fs
src/Fantomas/CodePrinter.fs

Fixes #2027 and fixes #2062.
There is a very minor stylistic impact by this fix.
I'm not sure yet if I'm going to release this as part of the 4.6 series or wait for 4.7.

Print trivia in LongIdentWithDots application.

---

CONTRIBUTING.md

Fixes #2056 
Mention build pipeline in contributing guidelines and fix some minor typos while here.

Fix 2056: Mention build pipeline in contributing guidelines

---

src/Fantomas.Tests/CommentTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs

Fixes #2043 
- comments after let bindings with return types
- comments after SynType_Array in record type

Fix 2043: Comment after [] is lost

---

docs/Formatting-Elmish-code.md

Fixed the link for the [SynExpr Type](https://fsharp.github.io/fsharp-compiler-docs/reference/fsharp-compiler-syntax-synexpr.html) in the FSharp compiler docs. The [current link](https://fsharp.github.io/FSharp.Compiler.Service/reference/fsharp-compiler-syntaxtree-synexpr.html) is broken.

Fix FSharp compiler docs link for SynExpr

---

docs/Documentation.md

Fixed the link for the [SynExpr.DotGet](https://fsharp.github.io/fsharp-compiler-docs/reference/fsharp-compiler-syntax-synexpr.html#DotGetl) expression, in the FSharp compiler docs. The [current link](https://fsharp.github.io/FSharp.Compiler.Service/reference/fsharp-compiler-syntaxtree-synexpr.html) is broken.
Sorry for not batching this with the [previous PR](https://github.com/fsprojects/fantomas/pull/2082), just found this broken link.

Fix FSharp compiler docs link for SynExpr.DotGet expression

---

.githooks/pre-push
CONTRIBUTING.md
build.fsx

Feel free to not take this, this is a little experiment.
I added a git hook that fires before commits are pushed to a repo that invokes the `CheckFormat` target.  If that target fails, the push fails.
In order for this to work, by default the hook script would have to live in the `.git/hooks` directory, but this directory isn't sharable/tracked in git. Therefore, I made a new directory to hold the hooks, and added a build script target that can be used to set up this kind of repo-local git config (since the .git/config file can't be shared for the same reason!). One other use of this target might be to set the `.git-blame-ignore-revs` file configuration, for example.
What do you think? I would imagine if you like this I'd need to update the README as well.

Pre push hook to ensure code is formatted on upload

---

src/Fantomas.Tests/KeepIfThenInSameLineTests.fs

#1160 is already fixed in current. So here is a regression test to close the issue.

Add regression test for #1160, Unexpected indentation in if-else when using keep_if_then_in_same_line=true

---

CONTRIBUTING.md

Might be worse it, to explain how we handle stale issues.

Explain what's needed to close issues, that aren't reproducable anymore.

---

CONTRIBUTING.md
src/Fantomas.Tests/MultilineBlockBracketsOnSameColumnRecordTests.fs
src/Fantomas/CodePrinter.fs

Fix 1749 Creating anonymous record based on a function call with a list arg fails

---

src/Fantomas.Tests/AppTests.fs
src/Fantomas/CodePrinter.fs
src/Fantomas/SourceParser.fs

Fix 1932: Unexpected newline added before let bang

---

CHANGELOG.md
src/Fantomas.Tests/ColMultilineItemTests.fs
src/Fantomas.Tests/RecordTests.fs
src/Fantomas/CodePrinter.fs

Fixes #2109 
As @nojaf  suggested, it's fixed by wrapping genExpr() in atCurrentColumnIndent()

Keep copyInfo for record fixed at starting column

---

CHANGELOG.md
src/Fantomas.Client/paket.references
src/Fantomas.CoreGlobalTool/paket.references
src/Fantomas.Extras/paket.references
src/Fantomas/paket.references

I noticed `Ionide.KeepAChangelog.Tasks` and `Dotnet.ReproducibleBuilds` are listed as dependencies, this should not be the case.
This PR tries to rectify that.

Add  copy_local: true for Ionide.KeepAChangelog.Tasks and Dotnet.ReproducibleBuilds.

---

CHANGELOG.md
src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas/CodePrinter.fs

When property getters and setters are emitted, if we're emitting two properties then the second one, getter or setter, needs to be emitted with the `and` keyword. If this isn't done, the emitted code doesn't compile.
This fixes #2129

Emit correct keyword for properties with both getter and setter specified

---

src/Fantomas.Tests/DotGetTests.fs
src/Fantomas/CodePrinter.fs

Respect current column when dotget is found in quotation. 

---

CHANGELOG.md
src/Fantomas.Tests/IndexSyntaxTests.fs
src/Fantomas/SourceParser.fs

Fixes #2151 
I think the source of the problem was that `ElmishReactWithChildren` was matching too much, so I restricted it instead of changing `IndexWithoutDotExpr`.

Fix 2151, index syntax without dot on array of arrays

---

docs/Documentation.md

The syntax for applying same config settings to both extensions might not be immediately obvious.

docs: use multiple extension (.fs and .fsx) in .editorconfig sample

---

CHANGELOG.md
src/Fantomas.Tests/NewlineBetweenTypeDefinitionAndMembersTests.fs
src/Fantomas/CodePrinter.fs

fixes #2175 
Basically, just a copy&paste of @nojaf suggestions

Fix newline idempotency issue with multiline abstract members

---

CHANGELOG.md
src/Fantomas.Tests/AppTests.fs
src/Fantomas.Tests/CommentTests.fs
src/Fantomas.Tests/ControlStructureTests.fs
src/Fantomas.Tests/DotGetTests.fs
src/Fantomas.Tests/InterfaceTests.fs
src/Fantomas.Tests/ListTests.fs
src/Fantomas.Tests/PatternMatchingTests.fs
src/Fantomas.Tests/TypeDeclarationTests.fs
src/Fantomas.Tests/TypeProviderTests.fs
src/Fantomas/CodePrinter.fs

Don't add space between type of array and square brackets.
Fixes #2192.

Don't add space between type of array and square brackets (#2192)

---

CHANGELOG.md
src/Fantomas.Tests/DotIndexedGetTests.fs
src/Fantomas/CodePrinter.fs

Idempotency problem when using lower MaxLineLength than default and fantomas needs to split lines
Fixes https://github.com/fsprojects/fantomas/issues/2176

Multiline parentheses objectExpression in indexer expression

---

CHANGELOG.md
src/Fantomas.CoreGlobalTool/Program.fs

As of release [3.4](https://github.com/fable-compiler/Fable/releases/tag/3.4.0) Fable uses the `fable_modules` directory instead of `.fable`. So I think it makes sense to add it to the list of always excluded directories.

Add fable_modules to the directories always excluded

---

CHANGELOG.md
src/Fantomas.Tests/DotGetTests.fs
src/Fantomas.Tests/QuotationTests.fs
src/Fantomas/CodePrinter.fs

Fixes #2203 
I used a slightly different fix to be more in line with what we do sofar.
Mainly to not put the `<@` on separate lines.

Fix idempotency problem with multiline quotation expressions.

---

paket.dependencies
paket.lock
src/Fantomas.Client/CHANGELOG.md
src/Fantomas.Client/FantomasToolLocator.fs

Version 5.0.0-alpha-00X is not being recognised as higher by the `supportedRange.IsSatisfied` function without `includePrerelease = true`.
See https://github.com/adamreeve/semver.net#pre-release-versions
This blocks users from using the next major version in editors.

Include prerelease when verifying a compatible version.

---

CHANGELOG.md
src/Fantomas.Core.Tests/CommentTests.fs
src/Fantomas.Core.Tests/Fantomas.Core.Tests.fsproj
src/Fantomas.Core.Tests/NumberOfItemsRecordTests.fs
src/Fantomas.Core.Tests/RecordDeclarationsWithXMLDocTests.fs
src/Fantomas.Core.Tests/RecordTests.fs
src/Fantomas.Core/CodePrinter.fs

Consider wider default format for record declarations if any XML doc comments are present on fields

---

CHANGELOG.md
src/Fantomas.Core.Tests/DotGetTests.fs
src/Fantomas.Core.Tests/LambdaTests.fs
src/Fantomas.Core.Tests/RecordTests.fs
src/Fantomas.Core.Tests/Stroupstrup/ElmishTests.fs
src/Fantomas.Core.Tests/TypeDeclarationTests.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/SourceParser.fs

Fixes #2231
Fixes #2041
Not super sure about this one and it may need more discussion, but I think we are a bit too liberal adding spaces before the lparen of lambda arguments. This can easily break calls to Linq methods. See the example in #2231

Be more cautious when adding a sepSpace before paren lambda

---

CHANGELOG.md
docs/Documentation.md
src/Fantomas.Core.Tests/FormatConfigEditorConfigurationFileTests.fs
src/Fantomas.Core.Tests/NumberOfItemsListOrArrayTests.fs
src/Fantomas.Core.Tests/Stroupstrup/DotIndexedSetExpressionTests.fs
src/Fantomas.Core.Tests/Stroupstrup/DotSetExpressionTests.fs
src/Fantomas.Core.Tests/Stroupstrup/ElmishTests.fs
src/Fantomas.Core.Tests/Stroupstrup/FunctionApplicationDualListTests.fs
src/Fantomas.Core.Tests/Stroupstrup/FunctionApplicationSingleListTests.fs
src/Fantomas.Core.Tests/Stroupstrup/KeepIndentInBranchExpressionTests.fs
src/Fantomas.Core.Tests/Stroupstrup/LambdaExpressionTests.fs
src/Fantomas.Core.Tests/Stroupstrup/LetOrUseBangExpressionTests.fs
src/Fantomas.Core.Tests/Stroupstrup/LongIdentSetExpressionTests.fs
src/Fantomas.Core.Tests/Stroupstrup/MultiLineLambdaClosingNewlineExpressionTests.fs
src/Fantomas.Core.Tests/Stroupstrup/NamedArgumentExpressionTests.fs
src/Fantomas.Core.Tests/Stroupstrup/SetExpressionTests.fs
src/Fantomas.Core.Tests/Stroupstrup/SynBindingFunctionExpressionTests.fs
src/Fantomas.Core.Tests/Stroupstrup/SynBindingFunctionLongPatternExpressionTests.fs
src/Fantomas.Core.Tests/Stroupstrup/SynBindingFunctionWithReturnTypeExpressionTests.fs
src/Fantomas.Core.Tests/Stroupstrup/SynBindingValueExpressionTests.fs
src/Fantomas.Core.Tests/Stroupstrup/SynExprAndBangExpressionTests.fs
src/Fantomas.Core.Tests/Stroupstrup/SynMatchClauseExpressionTests.fs
src/Fantomas.Core.Tests/Stroupstrup/SynTypeDefnSigReprSimpleTests.fs
src/Fantomas.Core.Tests/Stroupstrup/SynTypeDefnSimpleReprRecordTests.fs
src/Fantomas.Core.Tests/Stroupstrup/YieldOrReturnBangExpressionTests.fs
src/Fantomas.Core.Tests/Stroupstrup/YieldOrReturnExpressionTests.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/Context.fs
src/Fantomas.Core/FormatConfig.fs

`fsharp_experimental_stroupstrup_style` => `fsharp_experimental_stroustrup_style`

Correct typo in fsharp_experimental_stroustrup_style

---

CHANGELOG.md
src/Fantomas.Core.Tests/SignatureTests.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/Context.fs

Could you please review @dsyme if this is in line with the style guide?
I do notice that Fantomas doesn't put a space before the colon in `when ^T :`.
Is this by design for constraints?
Fixes #2230.

Put long multiline constrained SRTP on separate lines.

---

CHANGELOG.md
src/Fantomas.Core.Tests/ClassTests.fs
src/Fantomas.Core.Tests/LetBindingTests.fs
src/Fantomas.Core.Tests/TypeDeclarationTests.fs
src/Fantomas.Core/CodePrinter.fs

Hello @dsyme, this is an attempt to address https://github.com/fsprojects/fantomas/issues/2267 and https://github.com/fsprojects/fantomas/issues/2266.
I went with the original proposals to start somewhere.
At the verify least, the areas that need a change in Fantomas are found.
All in all, I don't think this is that bad and it looks consistent to me with https://github.com/fsprojects/fantomas/pull/2263.

Long generic constraints

---

CHANGELOG.md
src/Fantomas.Core.Tests/OperatorTests.fs
src/Fantomas.Core.Tests/SynConstTests.fs
src/Fantomas.Core/CodePrinter.fs

Fixes still open part of #2207
As Don has already [agreed](https://github.com/fsharp/fslang-design/issues/660#issuecomment-1138847319) to do it like this and there is a [PR](https://github.com/dotnet/docs/pull/29657) pending for the style guide clarification, I think we can move on with this.
I changed the test to use `*` instead of `/` because we have another test which already covers SynMeasure.Divide.

add space around binary operators in units of measure

---

CHANGELOG.md
src/Fantomas.Core.Tests/InterfaceTests.fs
src/Fantomas.Core/CodePrinter.fs

only call sepSpaceBeforeClassConstructor if we are generating a class

---

src/Fantomas.Core.Tests/CommentTests.fs
src/Fantomas.Core.Tests/SignatureTests.fs
src/Fantomas.Core/Context.fs

While adding the regression test for #1975 I noticed double spaces in some cases.
I moved the wordXXX functions to keep them together and make use of sepSpace like @nojaf suggested.
The existing tests which expected the double spaces were adjusted.

Add regression test for 1975 and fix double spaces

---

CHANGELOG.md
docs-old/Documentation.md
src/Fantomas.Core.Tests/ActivePatternTests.fs
src/Fantomas.Core.Tests/AppTests.fs
src/Fantomas.Core.Tests/CommentTests.fs
src/Fantomas.Core.Tests/CompilerDirectivesTests.fs
src/Fantomas.Core.Tests/ComputationExpressionTests.fs
src/Fantomas.Core.Tests/ControlStructureTests.fs
src/Fantomas.Core.Tests/DotGetTests.fs
src/Fantomas.Core.Tests/DynamicOperatorTests.fs
src/Fantomas.Core.Tests/Fantomas.Core.Tests.fsproj
src/Fantomas.Core.Tests/IfThenElseTests.fs
src/Fantomas.Core.Tests/KeepIndentInBranchTests.fs
src/Fantomas.Core.Tests/LetBindingTests.fs
src/Fantomas.Core.Tests/ListTests.fs
src/Fantomas.Core.Tests/MaxIfThenShortWidthTests.fs
src/Fantomas.Core.Tests/MultilineBlockBracketsOnSameColumnArrayOrListTests.fs
src/Fantomas.Core.Tests/MultilineFunctionApplicationsInConditionExpressionsTests.fs
src/Fantomas.Core.Tests/OperatorTests.fs
src/Fantomas.Core.Tests/PatternMatchingTests.fs
src/Fantomas.Core.Tests/TupleTests.fs
src/Fantomas.Core/AstTransformer.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/Context.fs
src/Fantomas.Core/FormatConfig.fs
src/Fantomas.Core/SourceParser.fs

This PR introduces the `fsharp_max_if_then_short_width` setting from https://github.com/fsprojects/fantomas/issues/2299 and revisits long `ifExpr` and `matchExpr` (See https://github.com/fsharp/fslang-design/issues/646#issuecomment-1138808449).
My personal interest is more in the latter, as it is quite satisfying how much more consistently we deal with these situations.
The flow is the following:
```fsharp
if x then y
```
First `if x then` is printed, if it fits on the rest of the line it stays in one line.
If it cross the `max_line_length` boundary or is multiline it changes to
```fsharp
if
x
then
y
```
If the entire expression is lower than the `fsharp_max_if_then_short_width`, it stays in one line.
Otherwise, it will put the `thenExpr` on the next line:
```fsharp
if x then
y
```
The …

Revisit if/then/else

---

.fantomasignore
.githooks/pre-push
build.fsx

Using a `.fantomasignore` makes it easier to format everything from the command line.
What I often do is build fantomas locally and run it on the `src` folder.
This will simplify that process.
The `CheckFormat` target also calls the `Clean` target, so having that each time the git hook triggers is actually quite annoying. I don't want to touch the FAKE stuff much anymore because we are looking at alternatives in https://github.com/fsprojects/fantomas/pull/2303

Update git pre-push check.

---

CHANGELOG.md
src/Fantomas.Core.Tests/FormatAstTests.fs
src/Fantomas.Core.Tests/SynLongIdentTests.fs
src/Fantomas.Core/CodeFormatter.fs
src/Fantomas.Core/CodeFormatter.fsi

The main motivation for this is the `FormatASTAsync` function, which is used primarily by projects that generate code. They do not have any source input and typically don't care about the output so use they use the default configuration.

Mark config as optional in public API.

---

CHANGELOG.md
src/Fantomas.Tests/Integration/CheckTests.fs
src/Fantomas.Tests/Integration/ExitCodeTests.fs
src/Fantomas/Program.fs

Fixes #2341 
Instead of showing the complete help in case of InputPath.Unspecified, a hint is shown.
Of course, it's subjective, but I somehow prefer CLI tools which don't slap the whole help in my face without me asking for it.

Extend InputPath DU to improve error messages

---

docs/_template.html
docs/docs/contributors/FSharp.md
docs/docs/contributors/Formatted Code.md
docs/docs/contributors/Getting Started.md
docs/docs/contributors/Index.md
docs/docs/contributors/Prepare Context.md
docs/docs/contributors/Print AST with Context.md
docs/docs/contributors/Solution Structure.md
src/Fantomas.Core.Tests/CodePrinterHelperFunctionsTests.fs
src/Fantomas.Core.Tests/Fantomas.Core.Tests.fsproj
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/Context.fs

An initial few pages for https://github.com/fsprojects/fantomas/issues/2320.
When reviewing this you might want to read it locally using:
https://github.com/fsprojects/fantomas/blob/8593cb20c867699bedc6a9c5c735fa4532db27ed/docs/.README.md
Enjoy!
PS: @yisusalanpng is working on the styling in https://github.com/fsprojects/fantomas/pull/2377

Fantomas.Core documentation

---

src/Fantomas.Core.Tests/Stroustrup/MultiLineLambdaClosingNewlineExpressionTests.fs
src/Fantomas.Core.Tests/Stroustrup/SynMatchClauseExpressionTests.fs
src/Fantomas.Core.Tests/Stroustrup/SynTypeDefnSigReprSimpleTests.fs
src/Fantomas.Core.Tests/Stroustrup/SynTypeDefnSimpleReprRecordTests.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/Context.fs
src/Fantomas.Core/FormatConfig.fs
src/Fantomas.Core/SourceParser.fs

Not sure if these were intentionally left out of #2251, but I figured for the sake of code clarity these references to the ragnarok code name should probably be updated to actually refer to the stroustrup feature.

Update leftover references to ragnarok

---

CHANGELOG.md
src/Fantomas.Core.Tests/OperatorTests.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/SourceParser.fs

Fixes #2434
@Smaug123 I did add a space on both sides of the operator.

Add spaces around custom operator definition starting with a star.

---

CHANGELOG.md
src/Fantomas.Core.Tests/OperatorTests.fs
src/Fantomas.Core/CodePrinter.fs

Wrap lambda and if/then/else expressions in parenthesis in single line infix compositions.

---

CHANGELOG.md
src/Fantomas.Core.Tests/ListTests.fs
src/Fantomas.Core/CodePrinter.fs

Fixes #2158 
I wasn't sure about the added duplication in `IndexWithoutDotExpr` but factoring the change seemed to add as much complexity. Elsewhere seems to favour mild duplication. Happy to adjust as preferred.
Noticed in the ListTests.fs file the last function isn't marked as a test. I've checked and it runs fine. I have NOT added it to this PR but happy to or add a separate PR to get properly added and running:
https://github.com/fsprojects/fantomas/blob/2d5db3e6c7b7fb47e374505765ed530dfd934aa2/src/Fantomas.Core.Tests/ListTests.fs#L2302-L2321

Maintain column indentation for list of functions

---

CHANGELOG.md
src/Fantomas.Core.Tests/OperatorTests.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/SourceParser.fs

Don't add spaces for single op_Multiply operator name.

---

CHANGELOG.md
src/Fantomas.Tests/CheckTests.fs
src/Fantomas.Tests/Integration/CheckTests.fs
src/Fantomas/Format.fs

Strip only \r to be able to detect a changed number of newlines

---

docs/docs/index.md

Currently our index sends to a 404 page instead of the contribution page. I changed it to point to CONTRIBUTING.md of this repository.
If contributors section for the new docs site is ready let me know so I change it to point there instead!

Change Contributions guideline to right url

---

docs/index.html

This makes the space after the "easy" in Chet's testimonial being rendered.

Add a &nbsp; to help browsers render the space after an em tag

---

CHANGELOG.md
src/Fantomas.Core.Tests/Stroustrup/SynTypeDefnSimpleReprRecordTests.fs
src/Fantomas.Core/CodePrinter.fs

Adjusted the formatting for record definitions with accessibility modifiers using the Stroustrup style.
This may or may not be a naive approach to solving this problem, any feedback would be much appreciated!
This will fix #2481
I'm not sure what the "correct" format is here. I went with my original example in the issue
```fsharp
type Person = private {
FirstName: string
LastName: string
}
```

Fix record definition using Stroustrup style

---

docs/.style/homepage.sass
docs/.style/sidebar.sass
docs/index.html

(#2317)
Typing text hidden on mobile
Community sponsors optimized on mobile
Removal of news menu item
Minor tweaks
WIP: Still figuring out why the docs sidebar scrolls

Mobile optimizations

---

CHANGELOG.md
src/Fantomas.Core.Tests/SynExprSetTests.fs
src/Fantomas.Core/CodePrinter.fs

Fix spacing for Const and Ident expressions in NamedIndexedPropertySet

---

src/Fantomas.Core/CodePrinter.fs

Besides [this](https://github.com/fsprojects/fantomas/pull/2509#discussion_r973543837) I found two other occurences of `id` which imho could be made more clear by using `sepNone`.

Use sepNone instead of id to improve clarity

---

CHANGELOG.md
docs/docs/contributors/Index.md

Closes #2447.
Please let me know if I could phrase anything better.

Add documentation for Visual Studio build issue

---

docs/.style/fsdocs-custom.sass
docs/content/webcomponents.js

This ensures that the headers are visible when a page is visited using an anchor.

Add scroll padding top.

---

CHANGELOG.md
src/Fantomas.Core.Tests/CommentTests.fs
src/Fantomas.Core/CodePrinter.fs

Fixes https://github.com/fsprojects/fantomas/issues/2538

Comments in anonymous records

---

src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/SourceParser.fs

This simplifies some code around `SynPat.LongIdent` in `genPat`.

Split up PatLongIdent usage in genPat.

---

src/Fantomas.Core.Tests/PatternMatchingTests.fs
src/Fantomas.Core/CodePrinter.fs

Restoring something we previously didn't cover in any unit test.

Ensure original 5.0.x behaviour.

---

CHANGELOG.md
src/Fantomas.Core.Tests/TypeDeclarationTests.fs
src/Fantomas.Core/CodePrinter.fs

Don't add additional space for multiline AlternativeLongMemberDefinitions constructor.

---

CHANGELOG.md
src/Fantomas.Core.Tests/DotSetTests.fs
src/Fantomas.Core.Tests/Fantomas.Core.Tests.fsproj
src/Fantomas.Core/CodePrinter.fs

Don't add space between function application with parentheses in DotSet.

---

CHANGELOG.md
src/Fantomas.Core.Tests/QuotationTests.fs
src/Fantomas.Core/AstTransformer.fs

Don't visit operator in SynExpr.Quote, fixes 2535

---

CHANGELOG.md
src/Fantomas.Core.Tests/BaseConstructorTests.fs
src/Fantomas.Core.Tests/ClassTests.fs
src/Fantomas.Core.Tests/Fantomas.Core.Tests.fsproj
src/Fantomas.Core.Tests/MultilineBlockBracketsOnSameColumnRecordTests.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/SourceParser.fs

Update according to the guidance of https://github.com/fsharp/fslang-design/issues/693.
Fixes https://github.com/fsharp/fslang-design/issues/693.
Fixes https://github.com/fsprojects/fantomas/issues/2111
Fixes https://github.com/fsprojects/fantomas/issues/2335
@Smaug123 there is a minor impact for [MultilineBlockBracketsOnSameColumn](https://fsprojects.github.io/fantomas/docs/end-users/Configuration.html#fsharp_multiline_block_brackets_on_same_column).
I don't think you really use that much. Nevertheless, does it seem acceptable?

Change style of base constructor calls.

---

CHANGELOG.md
src/Fantomas.Core.Tests/QuotationTests.fs

Here's the regression test in order to close #2110

Add regression test for 2110

---

CHANGELOG.md
src/Fantomas.Core.Tests/MultilineBlockBracketsOnSameColumnRecordTests.fs
src/Fantomas.Core.Tests/NumberOfItemsRecordTests.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/Context.fs
src/Fantomas.Core/SourceParser.fs

This is an attempt to address the issues in #2412 and #1167 to allow anonymous record types to be formattable with the bracket alignment working like with normal records.

Multiline bracket aligning for anonymous record types

---

CHANGELOG.md
src/Fantomas.Core.Tests/ClassTests.fs
src/Fantomas.Core.Tests/NewlineBetweenTypeDefinitionAndMembersTests.fs
src/Fantomas.Core.Tests/SignatureTests.fs
src/Fantomas.Core.Tests/TypeAnnotationTests.fs
src/Fantomas.Core.Tests/TypeDeclarationTests.fs
src/Fantomas.Core/CodePrinter.fs

In https://github.com/fsprojects/fantomas/commit/be2475cc5976ae5160fbd6a242a09dc37b367b75, the style for multiline prefix types was slightly changed. But this can lead to invalid F# code in certain scenarios. It is safer to revert that change.
//cc @dawedawe

Revert multiline app type

---

CHANGELOG.md
src/Fantomas.Core.Tests/CommentTests.fs
src/Fantomas.Core/Trivia.fs

Fixes #2585
Added addtional cases for  `SynPat_Attrib`, `SynPat_Named`, `SynPat_Typed` to `visitLastChildNode`

Fixed comments on params with attributes

---

CHANGELOG.md
src/Fantomas.Core.Tests/MultilineBlockBracketsOnSameColumnRecordTests.fs
src/Fantomas.Core.Tests/RecordTests.fs
src/Fantomas.Core/AstTransformer.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/SourceParser.fs
src/Fantomas.Core/TriviaTypes.fs

fixes the lost comments in #2566

Capture StartEndRange information in SynExpr.AnonRecd to fix #2566

---

CHANGELOG.md
src/Fantomas.Core.Tests/Stroustrup/SynTypeDefnSimpleReprRecordTests.fs
src/Fantomas.Core/CodePrinter.fs

Tighten the condition for unindent in genMultilineSimpleRecordTypeDefnAlignBrackets

---

build.fsx

I believe this will fail the build if the scripts cannot be compiled.
Which is what we want in order to ensure correct documentation.

Build documentation with strict flag.

---

src/Fantomas.Core.Tests/DallasTests.fs
src/Fantomas.Core.Tests/OperatorTests.fs
src/Fantomas.Core/CodePrinter2.fs

Fixes a regression reported by @jindraivanek on Discord.

Take all let in bindings in a multiline infix expression into account.

---

src/Fantomas.Core.Tests/DallasTests.fs
src/Fantomas.Core/CodePrinter2.fs
src/Fantomas.Core/Fangorn.fs
src/Fantomas.Core/Flowering.fs
src/Fantomas.Core/SyntaxOak.fs

- Move `ImplicitConstructorNode` to `TypeNameNode` level
- Improve the range of `TypeNameNode`
- Have a single path to print `TypeNameNode`
- Fix a bug where a block comment was considered to be on one line.

Improve TypeDefn

---

CHANGELOG.md
src/Fantomas.Core.Tests/DallasTests.fs
src/Fantomas.Core.Tests/SignatureTests.fs
src/Fantomas.Core/CodePrinter2.fs
src/Fantomas.Core/SyntaxOak.fs

Fixes problem with trivia before an equals sign found in the current codebase.

Fix multiline implicit constructor

---

src/Fantomas.Core.Tests/DallasTests.fs
src/Fantomas.Core/CodePrinter2.fs

This avoids a comment being printed twice.

genNode for patterns case by case.

---

CHANGELOG.md
Directory.Build.props

On my local machine:
Before:
```
Benchmark/step-0> | Method |     Mean |   Error |  StdDev | Rank |       Gen0 |      Gen1 |     Gen2 | Allocated |
Benchmark/step-0> |------- |---------:|--------:|--------:|-----:|-----------:|----------:|---------:|----------:|
Benchmark/step-0> | Format | 136.0 ms | 0.55 ms | 0.46 ms |    1 | 13250.0000 | 2500.0000 | 750.0000 | 157.83 MB |
```
After:
```
Benchmark/step-0> | Method |     Mean |    Error |   StdDev | Rank |     Gen0 |     Gen1 | Allocated |
Benchmark/step-0> |------- |---------:|---------:|---------:|-----:|---------:|---------:|----------:|
Benchmark/step-0> | Format | 98.23 ms | 0.772 ms | 0.722 ms |    1 | 600.0000 | 400.0000 | 157.82 MB |
```
I think we should do this for the daemon as well, as this makes sense for the …

Enable Server gc

---

src/Fantomas.Core.Tests/TypeDeclarationTests.fs
src/Fantomas.Core/CodePrinter2.fs

Indent accessibility and type name when they contain trivia before.

---

CHANGELOG.md
src/Fantomas.Tests/Integration/DaemonTests.fs
src/Fantomas/IgnoreFile.fs
src/Fantomas/IgnoreFile.fsi

I discovered that ignored files can potentially be formatted by `Fantomas.Client`.
Steps to reproduce:
- Clone https://github.com/dotnet/fsharp
- Run the following script:
```fsharp
#r "nuget: Fantomas.Client"
open System
open System.IO
open Fantomas.Client.Contracts
open Fantomas.Client.LSPFantomasService
let service = new LSPFantomasService() :> FantomasService
let file = @"C:\Users\nojaf\Projects\fsharp\src\Compiler\Checking\NicePrint.fs"
let content = File.ReadAllText file
let formatReq : FormatDocumentRequest = {
SourceCode = content
FilePath = file
Config = None
}
service.FormatDocumentAsync(formatReq).Result.Code
```
The code will read `1` which means `Formatted`, you should receive `4` (`Ignored`) instead.
I believe I found a fix for this problem but I would like a review from …

Call ignoreFile.IsIgnored with absolute path.

---

src/Fantomas.Core.Tests/PatternMatchingTests.fs
src/Fantomas.Core/CodePrinter2.fs

Ensure that the comma in a tuple is indented far enough in a pattern match.

---

src/Fantomas.Core.Tests/CommentTests.fs
src/Fantomas.Core/Flowering.fs

Attach trivia to node after when node before is on the previous line.

---

src/Fantomas.Core/CodePrinter2.fs
src/Fantomas.Core/Context.fs
src/Fantomas.Core/Defines.fs
src/Fantomas.Core/FormatConfig.fs

The code for printing a function with or without return type has historically always been very similar.
Because of the different rules in both style guides, it was split up but with minimal changes, we can converge these two functions.

Clean up genBinding

---

src/Fantomas.Core.Tests/CommentTests.fs
src/Fantomas.Core.Tests/IfThenElseTests.fs
src/Fantomas.Core/CodePrinter2.fs
src/Fantomas.Core/Fangorn.fs
src/Fantomas.Core/SyntaxOak.fs

Related to https://github.com/fsprojects/fantomas/issues/2449.
@dawedawe this might seem a bit complex and it definitely is a very creative way to approach the problem space.
In essence, I wrote a special type that deals with the trivia assignment of `else if`.
If a trivia would be assigned to either `else` or `if`, the best possible node is selected so that we can write `else if` in one piece without trivia interference.
This isn't without drawbacks but given the delicate nature this might do the trick.

Process `else if` using ElseIfNode.

---

src/Fantomas.Core.Tests/LambdaTests.fs
src/Fantomas.Core/CodePrinter2.fs

Ensure closing parenthesis is indented far enough in function application with lambda.

---

src/Fantomas.Core.Tests/TypeDeclarationTests.fs
src/Fantomas.Core/CodePrinter2.fs
src/Fantomas.Core/Fangorn.fs

Correct the range for recursive types.
Indent everything after the leading keyword.
Fixes https://github.com/fsprojects/fantomas/issues/2360
Fixes https://github.com/fsprojects/fantomas/issues/2361

Correct the range for recursive types

---

src/Fantomas.Core.Tests/PatternMatchingTests.fs
src/Fantomas.Core/CodePrinter2.fs

Use atCurrentColumn for pattern in match clause.

---

src/Fantomas.Core/ASTTransformer.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/SyntaxOak.fs
src/Fantomas.Core/Trivia.fs

This aligns the patterns closer to [TypeSignatureParameterNode](https://fsprojects.github.io/fantomas/reference/fantomas-core-syntaxoak-typesignatureparameternode.html)

Combined Attrib and Typed into PatParameterNode.

---

CHANGELOG.md
src/Fantomas.Core.Tests/Stroustrup/SynBindingValueExpressionTests.fs
src/Fantomas.Core.Tests/Stroustrup/SynTypeDefnSimpleReprRecordTests.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/Context.fs
src/Fantomas.Core/Context.fsi
src/Fantomas.Core/SyntaxOak.fs

Fix nested values inside anonymous records and types not displaying properly in stroustrup style

---

CHANGELOG.md
src/Fantomas.Core.Tests/MultiLineLambdaClosingNewlineTests.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/Context.fs
src/Fantomas.Core/Context.fsi

Fixes #2682.
The gist of this fix is moving `atCurrentColumn` calls to the very specific location they are required to ensure valid code.
`
The usage in `ExprApp` was too general and I moved it to `Expr.JoinIn` and removed the need for it in `Expr.TypeApp`.
`atCurrentColumn` break the natural indentation flow and we should avoid it as much as possible.

Move atCurrentColumn calls from multiline application expression to specific locations.

---

CHANGELOG.md
src/Fantomas.Core.Tests/TypeDeclarationTests.fs
src/Fantomas.Core/ASTTransformer.fs
src/Fantomas.Core/CodePrinter.fs

genNode for SimplePatNode.

---

src/Fantomas.FCS/Fantomas.FCS.fsproj
src/Fantomas.FCS/packages.lock.json

This newer version of `FsLexYacc` contains https://github.com/fsprojects/FsLexYacc/pull/154.

Update FsLexYacc to 11.0.1

---

src/Fantomas.Core/CodePrinter.fs

This is mainly an attempt to simplify the code around handling different bracket styles for record types, and to increase consistency and readability in `genTypeDefn` a little bit.

Refactor handling around bracket style in `genTypeDefn`

---

CHANGELOG.md
src/Fantomas.Core.Tests/Stroustrup/SynTypeDefnSimpleReprRecordTests.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/Context.fs
src/Fantomas.Core/Context.fsi

Fix anonymous record type alias handling when using Stroustrup style

---

CHANGELOG.md
src/Fantomas.Core.Tests/ChainTests.fs
src/Fantomas.Core.Tests/CompilerDirectivesTests.fs
src/Fantomas.Core.Tests/DotGetTests.fs
src/Fantomas.Core.Tests/DotIndexedGetTests.fs
src/Fantomas.Core.Tests/Fantomas.Core.Tests.fsproj
src/Fantomas.Core.Tests/IfThenElseTests.fs
src/Fantomas.Core.Tests/LambdaTests.fs
src/Fantomas.Core.Tests/MultiLineLambdaClosingNewlineTests.fs
src/Fantomas.Core.Tests/RecordTests.fs
src/Fantomas.Core.Tests/SpaceBeforeUppercaseInvocationTests.fs
src/Fantomas.Core.Tests/SpecialConstructsTests.fs
src/Fantomas.Core.Tests/TestHelpers.fs
src/Fantomas.Core.Tests/TypeDeclarationTests.fs
src/Fantomas.Core/ASTTransformer.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/Selection.fs
src/Fantomas.Core/SyntaxOak.fs

An attempt to address https://github.com/fsharp/fslang-design/issues/688.
This is merely a suggestion on how to provide guidance. Nothing has been decided so far.
The gist of this PR is that everything that is `SynExpr.DotGet` related is being converted to an `Expr.Chain`. A `ChainNode` consists of links. Each link is either a dot or something between a dot.
Examples:
```fsharp
A.B.C().D
E.F(fun g -> g).H
I<j>().K[0].L(m,n,o).P
``` 
The expression between a dot could be multiple things:
- An identifier such as `A` or `A<b>`
- An application with unit `A()`
- An application with a parenthesis expression `A(b)` (including lambdas `A(fun b -> b)`)
- An index expression `.[A]`
Capturing all these different F# AST shapes into one unified model is already a big win.
A lot of very selective AST …

Initial chain proof of concept.

---

CHANGELOG.md
src/Fantomas.Core.Tests/ChainTests.fs
src/Fantomas.Core/ASTTransformer.fs

Consider TypeApp as Identifier in mkLinksFromFunctionName.

---

CHANGELOG.md
src/Fantomas.Core.Tests/ChainTests.fs
src/Fantomas.Core.Tests/LambdaTests.fs
src/Fantomas.Core.Tests/LetBindingTests.fs
src/Fantomas.Core.Tests/TypeDeclarationTests.fs
src/Fantomas.Core/CodePrinter.fs

Keep Subsequent identifier links on the same line.

---

src/Fantomas.Core.Tests/TypeDeclarationTests.fs

Closes #1514
Looks like this issue already got fixed at some point. I just added some regression tests for the specific issue.

Add regression tests for #1514

---

CHANGELOG.md
src/Fantomas.Core.Tests/Stroustrup/MultiLineLambdaClosingNewlineExpressionTests.fs
src/Fantomas.Core/CodePrinter.fs

Fix parenthesis placement with Stroustrup alignment when using MultiLineLambdaClosingNewline=true

---

src/Fantomas.Tests/Integration/ConfigTests.fs
src/Fantomas.Tests/Integration/ForceTests.fs
src/Fantomas.Tests/Integration/IgnoreFilesTests.fs
src/Fantomas.Tests/Integration/MultiplePathsTests.fs
src/Fantomas.Tests/Integration/WriteTests.fs
src/Fantomas.Tests/packages.lock.json
src/Fantomas/Fantomas.fsproj
src/Fantomas/IgnoreFile.fs
src/Fantomas/Logging.fs
src/Fantomas/Program.fs
src/Fantomas/packages.lock.json

To show the general direction and maybe get some feedback, here's an early draft for the logging feature:
`--verbosity d` should be the same as in the past with the addition of the count of processed files in the end
`--verbosity n` should be pretty quiet
Fixes #2627

Extend logging and verbosity options

---

src/Fantomas.Core.Tests/ASTTransformerTests.fs
src/Fantomas.Core/ASTTransformer.fs
src/Fantomas.Core/ASTTransformer.fsi
src/Fantomas.Core/CodeFormatterImpl.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/Selection.fs
src/Fantomas.Core/SyntaxOak.fs

I don't think the Oak should be affected by any stylistic settings.
So in that regard, `ExprEndsWithDualListAppNode` and `ExprEndsWithSingleListAppNode` were a bit unfortunate choices. Both cases are special groupings of ExprAppNode if experimental Stroustrup is active.
It feels more correct to move this to `CodePrinter` instead of `ASTTransformer`.
If we in the future want to have a grouping of applications that ends with a record, we can more easily facilitate this without the need of having an extra special `Node`.

Refactor ExprEndsWithDualListAppNode and ExprEndsWithSingleListAppNode

---

CHANGELOG.md
src/Fantomas.Core.Tests/TypeDeclarationTests.fs
src/Fantomas.Core/ASTTransformer.fs

Keep backticks in optional SynType.SignatureParameter.

---

docs/docs/contributors/Pull request ground rules.md
src/Fantomas.Core.Tests/CodePrinterHelperFunctionsTests.fs
src/Fantomas.Core/ASTTransformer.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/FormatConfig.fs
src/Fantomas.Core/ISourceTextExtensions.fs
src/Fantomas.Core/Queue.fs
src/Fantomas.Core/Selection.fs
src/Fantomas.Core/SyntaxOak.fs
src/Fantomas.Core/Trivia.fs

There were a lot of members that introduced identifiers that went unused, it was inconsistent (e.g. sometimes `x.Thing`, sometimes `this.Thing`) and while the compiler was happy with that, it felt like additional noise. 
I updated `SyntaxOak.fs` to make things more consistent across node definitions: 
- If possible, use `member val`
- Use discard when identifier is needed but not used
- Otherwise use `x.Thing`, which seemed to be the most commonly used before

Update member declaration syntax in SyntaxOak.fs to be more consistent

---

docs/content/webcomponents.js
docs/docs/end-users/Configuration.fsx

Currently the icons left of the explanation text aren't rendered.
I'm not much of a JS dev, so there's most likely a better fix.

Let the icons (green, orange, ...) in the explanation be rendered.

---

CHANGELOG.md
Directory.Build.props
build.fsx
src/Fantomas.Benchmarks/packages.lock.json
src/Fantomas.Core.Tests/packages.lock.json
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/packages.lock.json
src/Fantomas.FCS/Fantomas.FCS.fsproj
src/Fantomas.FCS/packages.lock.json
src/Fantomas.Tests/packages.lock.json
src/Fantomas/packages.lock.json

Removed some unused functions in `CodePrinter`.
Also bumped `FCS` to a commit where a lot of unused code was removed there.
`Fantomas.FCS` would now take a dependency on `System.Diagnostics.DiagnosticSource` but that was bound to happen eventually.

Remove unused code

---

docs/.style/fsdocs-custom.sass
docs/content/webcomponents.js
docs/docs/end-users/Configuration.fsx
fantomas.sln

Add info about MultilineBracketStyle to docs, fix issue with icons

---

CHANGELOG.md
Directory.Build.props
src/Fantomas.Core.Tests/CompilerDirectivesTests.fs
src/Fantomas.Core/ASTTransformer.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/SyntaxOak.fs

Process `as` keyword in SynMemberDefn.ImplicitCtor trivia.

---

CHANGELOG.md
src/Fantomas.Core.Tests/CursorTests.fs
src/Fantomas.Core/CodeFormatter.fs
src/Fantomas.Core/CodeFormatter.fsi
src/Fantomas/Daemon.fs

https://github.com/fsprojects/fantomas/pull/2749#issuecomment-1410435446

Add separate CodeFormatter.FormatDocumentAsync overloads with cursor and config

---

src/Fantomas.Core.Tests/CrampedMultilineBracketStyleTests.fs
src/Fantomas.Core/ASTTransformer.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/Context.fs
src/Fantomas.Core/Selection.fs
src/Fantomas.Core/SyntaxOak.fs

It's happened several times that something that gets fixed with records that didn't get fixed for anonymous records. Since they share so much in the style guide, I wanted to see if I could refactor `genExpr` to handle them both at the same time so they could share as much logic as possible. I refactored both nodes to use the same field node type, and added an active pattern to join them together and then only handle differences explicitly as needed. It seems to work perfectly to me and I actually found an existing bug that was fixed for records but not anonymous records in the process 🙃.

Consolidate and share logic for Records and AnonymousRecords

---

src/Fantomas.Core.Tests/Stroustrup/SynBindingValueExpressionTests.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/Context.fs
src/Fantomas.Core/Context.fsi
src/Fantomas.Core/FormatConfig.fs

I'm going through the code in https://github.com/dotnet/docs/pull/33171 to try and get fantomas to match the ideal styles there.
This changes the output of the following code from this:
```fsharp
let newState = {
Foo =
Some
{
F1 = 0
F2 = ""
}
}
```
to this
```fsharp
let newState = {
Foo =
Some {
F1 = 0
F2 = ""
}
}
```
Which lets fantomas format code to better match some of the examples there.
But this also brings up a point we've discussed before:
For lowercase function applications with a single record node, with Stroustrup enabled, is there a problem with allowing this style? Because this will also format code like this
```fsharp
let newState =
notAComputationExpr {
F1 = 0
F2 = ""
}
```
I argue that it's fine, and it's is my personal preference, but @nojaf has expressed valid concerns …

Fix handling of AppExpr with a single stroustrup record

---

CHANGELOG.md
src/Fantomas.Core.Tests/IfThenElseTests.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/SyntaxOak.fs

Fixes #2752.
Duplicate newline was there because we were adding empty line trivia to `else if` node and then adding yet another newline to print the condition expr.

Ensure extra newlines are not added when formatting `else if`

---

src/Fantomas.Core.Tests/Stroustrup/SynTypeDefnSimpleReprRecordTests.fs
src/Fantomas.Core/CodePrinter.fs

Fix Stroustrup record member declaration indent issue

---

CHANGELOG.md
src/Fantomas.Core/MultipleDefineCombinations.fs

fixes a performance regression

remove AsParallel() when mapping over the results in mergeMultipleFormatResults()

---

CHANGELOG.md
src/Fantomas.Core.Tests/CompilerDirectivesTests.fs
src/Fantomas.Core/CodePrinter.fs

remove call to genNode in genFunctionNameWithMultilineLids to avoid duplicated trivia printing

---

docs/docs/end-users/Configuration.fsx

Some values did not match those in https://github.com/fsprojects/fantomas/blob/main/src/Fantomas.Core/FormatConfig.fs.
For `MaxDotGetExpressionWidth` and `NewlineBetweenTypeDefinitionAndMembers`, I had to update the examples so they demonstrate an actual change.
You may consider moving the `NewlineBetweenTypeDefinitionAndMembers` from the G-Research style section, because (as I understand it) the G-Research style is now the default. (This is not done in this PR.)

Fix documented defaults

---

CHANGELOG.md
src/Fantomas.Core.Tests/CompilerDirectivesTests.fs
src/Fantomas.Core/CodePrinter.fs

Use workaround from 628 for nested modules, too

---

CHANGELOG.md
src/Fantomas.Core.Tests/FunctionDefinitionTests.fs
src/Fantomas.Core.Tests/SignatureTests.fs
src/Fantomas.Core/ASTTransformer.fs

Should fix https://github.com/fsprojects/fantomas/issues/2875.
Hopefully I have not forgotten anything.

Fix mkSynTypar to account for quotes around type parameter

---

src/Fantomas.FCS/Fantomas.FCS.fsproj
src/Fantomas.FCS/packages.lock.json

Updating the FsLexYacc dependency so we can use the signature files for *.fsy files.

Use signature files for *.fsy files.

---

CHANGELOG.md
src/Fantomas.Core.Tests/LetBindingTests.fs

I wrote a regression test case for cons pattern in let binding (#1996).
Is it OK?

Add regression test for cons pattern in let binding (#1996)

---

CHANGELOG.md
Directory.Build.props
build.fsx
src/Fantomas.Core.Tests/SynConstTests.fs
src/Fantomas.Core/ASTTransformer.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/SyntaxOak.fs
src/Fantomas.FCS/Parse.fs

This makes use of the new modeling of `SynMeasure.Divide`.
Now that the `measure1` is optional, we have a chance to see, if the original code had it or not.
fixes #2926 and #2927

Adjust to optional lhs of SynMeasure.Divide

---

CHANGELOG.md
Directory.Build.props
build.fsx
src/Fantomas.Core.Tests/SynConstTests.fs
src/Fantomas.Core/ASTTransformer.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/SyntaxOak.fs

Fixes #2930
Fixes #2932 
Fixes #2933

Fix some block comments in Rational

---

.config/dotnet-tools.json
Directory.Build.props
build.fsx
global.json

To increase our level of dogfooding
- use dotnet 8 preview sdk
- use lang preview

use dotnet 8 preview sdk and lang preview

---

CHANGELOG.md
src/Fantomas.Core.Tests/TypeDeclarationTests.fs
src/Fantomas.Core/ASTTransformer.fs

Fix 2954 by using mkIdent in SynPat.OptionalVal

---

build.fsx
docs/docs/end-users/GettingStarted.fsx
src/Fantomas.Client/Contracts.fs
src/Fantomas.Core/ASTTransformer.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/Context.fs
src/Fantomas.Core/Trivia.fs
src/Fantomas.Core/Utils.fs
src/Fantomas.Core/Utils.fsi

Use faster and safer ordinal comparisons for strings.

Refactor string comparisons

---

build.fsx

With this PR, you can do a simple `dotnet fsi build.fsx` after a `git clean -xdf`.
Before, you had to do a `dotnet fsi build.fsx -p Init` prior to the `Build` pipeline.

use __SOURCE_DIRECTORY__ for the analyzersProjectPath

---

docs/docs/end-users/Configuration.fsx

I'm guessing this happened during a reckless find & replace for all occurrences of `red` to `color="red"`
﻿Please verify your pull request is respecting our [Pull request ground rules](https://fsprojects.github.io/fantomas/docs/contributors/Pull%20request%20ground%20rules.html).
You can find more information in our [Contributors documentation section](https://fsprojects.github.io/fantomas/docs/contributors/Index.html).

Fix description error in doc

---

build.fsx

This fixes an issue where the `formatChanged` pipeline fails if there are both staged and unstaged changes for the same file.

Fix issue in build.fsx

---

CHANGELOG.md
src/Fantomas.FCS/Parse.fs

As expected, the strict indentation in the `Fantomas.FCS` parser was not enabled.
I don't think it matters much for Fantomas, as we expect a valid tree anyway.
This could be useful for the online tool though.
//cc @auduchinok

Turn on strict indentation.

---

CHANGELOG.md
src/Fantomas.Core.Tests/PatternMatchingTests.fs
src/Fantomas.Core/CodePrinter.fs

fixes #2953 
Currently, just a draft as the fix is not idempotent.

Fix 2953 - Comment lost after named pat pair.

---

CHANGELOG.md
src/Fantomas/Program.fs

fixes #2854 
It's a bit complicated, but 
first we treated unknown flags as input folders
these input folders weren't found and then we treated these folders as output folders
these output folders didn't exist, so we created them, hence the famous `--recurse` folder came into life.

Fix 2854, accidental treatment of old flags as folders

---

CHANGELOG.md
src/Fantomas.Tests/Integration/WriteTests.fs
src/Fantomas.Tests/TestHelpers.fs
src/Fantomas/Program.fs

Uh, there really seems to be no one using this :(
I'll add tests later.

Fix output filename

---

CHANGELOG.md
src/Fantomas.Core.Tests/ClassTests.fs
src/Fantomas.Core.Tests/CodeFormatterTests.fs
src/Fantomas.Core.Tests/DallasTests.fs
src/Fantomas.Core.Tests/LetBindingTests.fs
src/Fantomas.Core.Tests/NewlineBetweenTypeDefinitionAndMembersTests.fs
src/Fantomas.Core.Tests/SignatureTests.fs
src/Fantomas.Core.Tests/TypeAnnotationTests.fs
src/Fantomas.Core.Tests/TypeDeclarationTests.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/Context.fs

Closes #2706, from Amplifying F# session

Fix issues with multiline generic type parameters

---

CHANGELOG.md
src/Fantomas.Core.Tests/Stroustrup/SynBindingFunctionExpressionTests.fs
src/Fantomas.Core.Tests/Stroustrup/SynBindingValueExpressionTests.fs
src/Fantomas.Core/Context.fs

Resolves https://github.com/fsprojects/fantomas/issues/3079
Instead of giving up on Stroustrup-Formatting whenever there is Trivia on the closing brackets, only do that for HashDirectives and allow any other kind of Trivia such as comments or NewLines

Check Hash Directive more strictly inside of lists or arrays

---

CHANGELOG.md
src/Fantomas.Core.Tests/DynamicOperatorTests.fs
src/Fantomas.Core/CodePrinter.fs

fixes #3088 
As written in the comment in the tests, I think we are better off not trying to apply the SpaceBefore(Upper|Lower)caseInvocation setting in the ? call chain as that can easily produce invalid code.

Fix exn in (|UppercaseExpr|LowercaseExpr|)

---

CHANGELOG.md
src/Fantomas.Core.Tests/TupleTests.fs
src/Fantomas.Core/CodePrinter.fs

add missing construction of return info node for deconstructed tuples

---

CHANGELOG.md
src/Fantomas.Core.Tests/PatternMatchingTests.fs
src/Fantomas.Core/CodePrinter.fs

fixes #2866 by just implementing @nojaf  advice

Guard against a newline induced precedence change

---

CHANGELOG.md
src/Fantomas.Core.Tests/ConstructorTests.fs
src/Fantomas.Core/CodePrinter.fs

fixes #2865 by just following @nojaf advice again
Also, add back a changelog entry which I removed accidentaly before.

Add a missing case to containsLambdaOrMatchExpr to fix 2865

---

src/Fantomas.Client/CHANGELOG.md
src/Fantomas.Client/FantomasToolLocator.fs

See issue: https://github.com/fsprojects/fantomas/issues/3104
```DOTNET_CLI_HOME``` can be used to specify alternate locations of global tools rather than the user's home directory.
See: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables
Tested using local script:
fsharp
```
#r "artifacts/bin/Fantomas.Client/release/Fantomas.Client.dll"
#r "nuget: SemanticVersioning"
#r "nuget: StreamJsonRpc"
open System
open Fantomas.Client
open Fantomas.Client.FantomasToolLocator
open Fantomas.Client.LSPFantomasServiceTypes
Environment.CurrentDirectory <- "/home/jovyan"
let cwd = Environment.CurrentDirectory
let cwdFolder = Fantomas.Client.LSPFantomasServiceTypes.Folder cwd
let fantomasToolResult: Result<FantomasToolFound, FantomasToolError> =
findFantomasTool cwdFolder
let …
```

Use DOTNET_CLI_HOME for finding fantomas as global tool (Fixes #3104)

---

CHANGELOG.md
src/Fantomas.Core.Tests/TypeDeclarationTests.fs
src/Fantomas.Core/CodePrinter.fs

Fixes idempotency issue when a single-case union extension is not started with a pipe #3102. Without this change, the body of the extension body is moved one line downward on each format run.

fix idempotency for single case union w/o pipe

---

CHANGELOG.md
src/Fantomas.Core.Tests/DotLambdaTests.fs
src/Fantomas.Core/CodePrinter.fs

Check if we just wrote a DotLambda on a record value before deciding on space before parens, fix 3120

---

CHANGELOG.md
src/Fantomas.Core.Tests/OperatorTests.fs
src/Fantomas.Core.Tests/TupleTests.fs
src/Fantomas.Core/CodePrinter.fs

1. fix for #3082 in CodePrinter.fs
2. 1 test in TupleTests.fs
3. Alter test to new _intended_ behavior in OperatorTests.fs
❗CHANGELOG.md change missing (I didn't push it because it was breaking my builds)

Fixed unnecessary parentheses in last tuple item (fsprojects#3082)

---

CHANGELOG.md
src/Fantomas.Core.Tests/ChainTests.fs
src/Fantomas.Core/CodePrinter.fs

Fixes https://github.com/fsprojects/fantomas/issues/3132
I don't fully understand the mechanism behind this idempotency problem, but it seems to only happen with a LeadingSimpleChain of length one, followed by a DotGet call. I changed the logic of printing multi-line leading chains to match how it is done if there are no links that follow the leading chain.
Please let me know if this change makes sense! I tested it to the best of my ability but I am not totally familiar with FSharp syntax and fantomas formatting guidelines.

Fix multiple line type expression with dotget idempotency

---

CHANGELOG.md
src/Fantomas.Core.Tests/LambdaTests.fs
src/Fantomas.Core/CodePrinter.fs

Fix idempotency issue with comments in apps on lambda expressions

---

docs/.README.md
docs/docs/index.md

Fixes #3157
Doc reference to G-Research/../.editorconfig fixed.
Build step `dotnet fsi .\docs\.style\style.fsx` removed as file doesn't exist and doesn't cause build failure.

Doc reference to G-Research/../.editorconfig incorrect

---

.config/dotnet-tools.json
docs/docs/end-users/Configuration.fsx
src/Fantomas.Core.Tests/CodePrinterHelperFunctionsTests.fs
src/Fantomas.Core.Tests/ContextTests.fs
src/Fantomas.Core/CodePrinter.fs
src/Fantomas.Core/Context.fs

The format changes showing up here are mostly #3134

Bump fantomas tool 7.0.1

---

CHANGELOG.md
src/Fantomas/Program.fs

should go in after #3160 
fixes #3148 
One could argue it should only be reported when there are format results but I think it makes sense to have it also with all the error cases like `InputPath.NoFSharpFile` etc.

Print version in detailed verbosity

---

CHANGELOG.md
src/Fantomas.Core.Tests/ActivePatternTests.fs
src/Fantomas.Core/ASTTransformer.fs

fixes #3126 
we can't directly reuse `mkIdent` as the backticks are inside the idText between the bars.

Preserve backticked idents in Active Pattern idents

---

docs/docs/end-users/FormattingCheck.md

https://fsprojects.github.io/fantomas/docs/end-users/FormattingCheck.html#FAKE
Currently still has `--recurse`, and doesn't have `DotNet.exec` format that works with FAKE 5 or 6 as far as I can tell.
This just fixes that.
Sorry for not creating an issue first, but it's a simple docs change!

Docs - Update FAKE fantomas command
