RELEASE_NOTES.md, src/Fantomas.Tests/FormattingPropertyTests.fs, src/Fantomas.Tests/FunctionDefinitionTests.fs, src/Fantomas.Tests/PatternMatchingTests.fs, src/Fantomas.Tests/TypeDeclarationTests.fs, src/Fantomas/CodeFormatter.fs, src/Fantomas/CodeFormatter.fsx, src/Fantomas/CodePrinter.fs, src/Fantomas/FakeHelpers.fs, src/Fantomas/SourceParser.fs, src/Fantomas/SourceTransformer.fs, src/Fantomas/TokenMatcher.fs, src/Fantomas/Utils.fs
Fixes:
- https://github.com/fsprojects/VisualFSharpPowerTools/issues/918
- https://github.com/fsprojects/VisualFSharpPowerTools/issues/886
- https://github.com/fsprojects/VisualFSharpPowerTools/issues/772
- https://github.com/dungpa/fantomas/issues/164
=> Bug fixes for VFPT

RELEASE_NOTES.md, paket.lock, src/Fantomas.Cmd/AssemblyInfo.fs, src/Fantomas.Tests/FunctionDefinitionTests.fs, src/Fantomas.UI/AssemblyInfo.fs, src/Fantomas/AssemblyInfo.fs, src/Fantomas/CodeFormatter.fsx, src/Fantomas/CodePrinter.fs
=> Publish NuGet package v1.9.0

src/Fantomas.Tests/OperatorTests.fs, src/Fantomas/FormatConfig.fs
Fantomas master isn't building correctly, so I can't run the test.
If it works, this should resolve #173.
=> Added monadic bind operator pipelining and unit test

docs/Documentation.md
=> :memo: remove extra `

README.md
This PR will close issue #187.
=> Add information about VS 2015 support

README.md, src/Fantomas/CodeFormatter.fsx
Fixes #198 
See how it looks like: https://github.com/OkayX6/fantomas/tree/architecture-notes#how-to-contribute
=> Architecture notes

paket.dependencies, paket.lock, src/Fantomas.Cmd/Fantomas.Cmd.fsproj, src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas.Tests/TestHelpers.fs, src/Fantomas/CodeFormatterImpl.fs, src/Fantomas/Fantomas.fsproj, src/Fantomas/TokenMatcher.fs
=> update FSharp.Compiler.Services to latest release

paket.lock
We have another release of FCS
=> update FCS to latest release

README.md
Now code samples are properly formatted.
=> Updated code samples in README.md

src/Fantomas.Tests/FunctionDefinitionTests.fs, src/Fantomas/CodePrinter.fs
Fix issue from this comment: https://github.com/Microsoft/visualfsharp/pull/3542#issuecomment-337543936.
=> Don't remove parentheses around lambda "complex" parameter with type.

src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas.Tests/StructTests.fs, src/Fantomas/CodePrinter.fs
=> Retain members outside struct-end (fix #201)

src/Fantomas.Tests/ControlStructureTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs
=> Support if/elif without else (fix #226).

src/Fantomas/Fantomas.fsproj
=> Change Content to None

src/Fantomas.Tests/ModuleTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs
=> Fix for recursive modules

README.md
Trying to have a more up to date readme file.
Should fix #243
=> [WIP] improve readme

src/Fantomas.Tests/ComputationExpressionTests.fs, src/Fantomas.Tests/FormattingPropertyTests.fs, src/Fantomas/CodeFormatterImpl.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs, src/Fantomas/SourceTransformer.fs
=> Support "match!"

.paket/Paket.Restore.targets, src/Fantomas.Cmd/AssemblyInfo.fs, src/Fantomas.Cmd/Fantomas.Cmd.fsproj, src/Fantomas.CoreGlobalTool/Fantomas.CoreGlobalTool.fsproj, src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas/AssemblyInfo.fs, src/Fantomas/Fantomas.fsproj
Updated all files with 2.9 version.
=> 2.9 version

src/Fantomas.Tests/ActivePatternTests.fs, src/Fantomas.Tests/ClassTests.fs, src/Fantomas.Tests/CommentTests.fs, src/Fantomas.Tests/ComparisonTests.fs, src/Fantomas.Tests/CompilerDirectivesTests.fs, src/Fantomas.Tests/ComputationExpressionTests.fs, src/Fantomas.Tests/ControlStructureTests.fs, src/Fantomas.Tests/DataStructureTests.fs, src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas.Tests/FormattingSelectionOnlyTests.fs, src/Fantomas.Tests/FormattingSelectionTests.fs, src/Fantomas.Tests/FunctionDefinitionTests.fs, src/Fantomas.Tests/InterfaceTests.fs, src/Fantomas.Tests/ModuleTests.fs, src/Fantomas.Tests/NoTrailingSpacesTests.fs, src/Fantomas.Tests/OperatorTests.fs, src/Fantomas.Tests/PatternMatchingTests.fs, src/Fantomas.Tests/PipingTests.fs, src/Fantomas.Tests/PreserveEOLTests.fs, src/Fantomas.Tests/RecordTests.fs, src/Fantomas.Tests/SignatureTests.fs, src/Fantomas.Tests/TypeDeclarationTests.fs, src/Fantomas.Tests/TypeProviderTests.fs, src/Fantomas/CodeFormatterImpl.fs, src/Fantomas/Utils.fs
=> Removed trailing spaces for each line, after formatting.

src/Fantomas.Tests/PreserveEOLTests.fs, src/Fantomas/CodePrinter.fs
=> Keep newline if all items in list or array already had a newline

src/Fantomas.Tests/FormatAstTests.fs, src/Fantomas.Tests/LetBindingTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/Context.fs, src/Fantomas/TokenMatcher.fs
=> Dont use let .. in when multiline after "in"or formatting from AST. Should fix #384

src/Fantomas.Cmd/Program.fs
=> Skip files in obj folder.

src/Fantomas.Tests/ActivePatternTests.fs, src/Fantomas.Tests/AttributeTests.fs, src/Fantomas.Tests/ClassTests.fs, src/Fantomas.Tests/CommentTests.fs, src/Fantomas.Tests/ComparisonTests.fs, src/Fantomas.Tests/ComputationExpressionTests.fs, src/Fantomas.Tests/DataStructureTests.fs, src/Fantomas.Tests/FormattingSelectionOnlyTests.fs, src/Fantomas.Tests/FormattingSelectionTests.fs, src/Fantomas.Tests/FunctionDefinitionTests.fs, src/Fantomas.Tests/InterfaceTests.fs, src/Fantomas.Tests/ModuleTests.fs, src/Fantomas.Tests/OperatorTests.fs, src/Fantomas.Tests/PatternMatchingTests.fs, src/Fantomas.Tests/PreserveEOLTests.fs, src/Fantomas.Tests/RecordTests.fs, src/Fantomas.Tests/SignatureTests.fs, src/Fantomas.Tests/SpecialConstructsTests.fs, src/Fantomas.Tests/StructTests.fs, src/Fantomas.Tests/TypeDeclarationTests.fs, src/Fantomas.Tests/TypeProviderTests.fs, src/Fantomas.Tests/UnionTests.fs, src/Fantomas/FormatConfig.fs
=> Default config: SpaceBeforeColon = false

src/Fantomas.Cmd/Program.fs
Detect that https://github.com/fsprojects/fantomas/pull/432 and https://github.com/fsprojects/fantomas/pull/433 were not in sync.
=> Use FormatConfig defaults in Cmd tool.

src/Fantomas.Tests/UnionTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs
=> Respect generic type style (prefix, postfix)

src/Fantomas.Tests/CompilerDirectivesTests.fs, src/Fantomas/CodePrinter.fs
=> Fix: print trivia for infix app.

src/Fantomas/Trivia.fs
AFAIU, both branches are appending an item and we don't need to distinguish empty list and just call appendItem.
=> simplify a case in `addTriviaToTriviaNode`

src/Fantomas.Tests/AppTests.fs, src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas.Tests/PatternMatchingTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/Context.fs
=> No newline before lambda unless really needed. Fix 503

src/Fantomas.Tests/CommentTests.fs, src/Fantomas.Tests/ControlStructureTests.fs, src/Fantomas/CodePrinter.fs
Proposal fix for issue highlighted here: #527 where elif condition gets mis-indented, generating compile error.
=> fix misindentation of elif condition expression

docs/Documentation.md, src/Fantomas.Tests/CommentTests.fs, src/Fantomas/CodePrinter.fs
Generate Trivia for enum cases
Also, changed the default pageWidth in docs which was wrong
=> Enum cases comments

README.md
A first attempt to have some contribution guidelines.
Let me know what you think @jindraivanek.
=> Initial contribution guidelines

src/Fantomas.Tests/OperatorTests.fs, src/Fantomas/CodePrinter.fs
=> Fix: Print line comment after infix function

src/Fantomas.Tests/LetBindingTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/Context.fs
=> Don't add any extra newlines within Sequential expr.

src/Fantomas.Tests/DataStructureTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/Context.fs, src/Fantomas/TokenParser.fs
=> Fix: print line comment after [

src/Fantomas.Tests/CompilerDirectivesTests.fs, src/Fantomas.Tests/UnionTests.fs, src/Fantomas/CodePrinter.fs
=> Fix: Print pipe before single case DU when it has an access modifier.

src/Fantomas.Tests/UnionTests.fs, src/Fantomas/CodePrinter.fs
=> Fix unindented type abbreviation with line comment

src/Fantomas.Tests/CompilerDirectivesTests.fs, src/Fantomas.Tests/RecordTests.fs, src/Fantomas/Context.fs
=> Always force hash directives on a new line.

src/Fantomas.Tests/UnionTests.fs, src/Fantomas/CodePrinter.fs
=> Add a pipe when a single case DU has attributes.

src/Fantomas.Tests/FormatConfigConfigurationFileTests.fs
=> Fix warnings in FormatConfigConfigurationFileTests.fs

src/Fantomas.Tests/LetBindingTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/Utils.fs
=> Add parenthesis when hash symbol has postfix

src/Fantomas.Tests/SignatureTests.fs, src/Fantomas/CodePrinter.fs
=> Print out type extension members in signature files

src/Fantomas.Tests/AttributeTests.fs, src/Fantomas/CodePrinter.fs
=> Don't add extra newline between attribute and let binding

RELEASE_NOTES.md, src/Fantomas.CoreGlobalTool/Fantomas.CoreGlobalTool.fsproj, src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas/Fantomas.fsproj
I'd like to release another beta.
I've integrated the [first beta into FSAutocomplete](https://github.com/fsharp/FsAutoComplete/pull/517).
And before this goes to Ionide I would like https://github.com/fsprojects/fantomas/pull/616 to be in there, as it might confuse people.
Then we can ask some early feedback about the configuration file before marking it as final.
=> Bump to 3.2.0-beta-002

src/Fantomas.CoreGlobalTool/Program.fs
=> Allow --version as single input for cli.

docs/Documentation.md, src/Fantomas.CoreGlobalTool/Program.fs, src/Fantomas.Tests/FormatConfigConfigurationFileTests.fs, src/Fantomas/FormatConfig.fs
=> Add deprecation warnings for ReorderOpenDeclaration.

src/Fantomas.Tests/SynConstTests.fs, src/Fantomas.Tests/TokenParserTests.fs, src/Fantomas.Tests/TriviaTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/Context.fs, src/Fantomas/TokenParser.fs, src/Fantomas/Trivia.fs, src/Fantomas/TriviaHelpers.fs, src/Fantomas/TriviaTypes.fs
=> Formatting original char from trivia.

src/Fantomas/Context.fs
This should improve memory usage but will most likely not fix all performance issues.
=> Fix: dump and continue

src/Fantomas.Tests/ComputationExpressionTests.fs, src/Fantomas/CodePrinter.fs
Fixes #690 by writing the and! expressions in line!
=> add support for writing the 'and!' expressions and patterns

src/Fantomas.Tests/SpaceBeforeSemicolonTests.fs, src/Fantomas/AstTransformer.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/EditorConfig.fs
Sorry some of these got in there in the first place 😅
=> Fix warnings

src/Fantomas.Tests/TypeDeclarationTests.fs, src/Fantomas/SourceParser.fs
=> Don't add duplicate newline between letbindings inside type

.github/workflows/myget.yml, src/Fantomas.CoreGlobalTool.Tests/Fantomas.CoreGlobalTool.Tests.fsproj
Apply same `<NoWarn>FS0988</NoWarn>` to Fantomas.CoreGlobalTool.Tests.
And same fix for myget.yaml GH action
=> Fix warnings tool test project

src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas/Fantomas.fsproj
A small cleanup for warnings in fsproj files.
=> Cleanup fsproj: TargetFrameworks -> TargetFramework

src/Fantomas.Tests/IfThenElseTests.fs, src/Fantomas/CodePrinter.fs
=> Fix else keyword not being part of SynIfThenElse range

src/Fantomas.Tests/ClassTests.fs, src/Fantomas/CodePrinter.fs
=> Add space before parameters passed to inherited class

src/Fantomas.Tests/ElmishTests.fs, src/Fantomas.Tests/FormattingPropertyTests.fs, src/Fantomas.Tests/ListTests.fs
These tests worked on my machine.
=> Restore ignored tests

src/Fantomas.Tests/ElmishTests.fs, src/Fantomas.Tests/FormattingPropertyTests.fs, src/Fantomas.Tests/ListTests.fs
This reverts commit 4710748c49d8cbb38d0abd1b8661f0d79c8232fb.
=> Revert "Restore ignored tests"

src/Fantomas.Tests/SignatureTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs, src/Fantomas/Trivia.fs
=> Fix: line comment above static member in signature file

src/Fantomas/CodePrinter.fs, src/Fantomas/Trivia.fs
Little clean up I discovered after https://github.com/fsprojects/fantomas/pull/743
=> Assign override|default|member keyword as content itself.

src/Fantomas.Tests/CompilerDirectivesTests.fs, src/Fantomas/CodePrinter.fs
=> Fix namespace global mixed with hash directives

src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas.Tests/MultilineBlockBracketsOnSameColumnArrayOrListTests.fs, src/Fantomas.Tests/MultilineBlockBracketsOnSameColumnRecordTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/Context.fs, src/Fantomas/FormatConfig.fs, src/Fantomas/TriviaHelpers.fs
=> feature: multiline block brackets on same column

src/Fantomas.Tests/SynConstTests.fs, src/Fantomas/CodePrinter.fs
=> Print value of SynConst.UserNum as string

.github/workflows/main.yml
Initial attempt didn't work:
Trying to escape the entire curl command this time.
=> Escape entire curl command as string

src/Fantomas.Tests/LetBindingTests.fs, src/Fantomas/SourceParser.fs
=> Determine if DotGet expression is upper- or lowercase

src/Fantomas.Tests/RecordTests.fs, src/Fantomas/CodePrinter.fs
=> Print trivia after short record type declaration

src/Fantomas.Tests/OperatorTests.fs, src/Fantomas/Context.fs
=> Add modulo operator to NoBreakInfixOps

src/Fantomas.CoreGlobalTool/Program.fs
Print the same message as in [fileToFile](https://github.com/fsprojects/fantomas/blob/191d7ef98e8fac4c07260e8d3cbb1ddf36775766/src/Fantomas.CoreGlobalTool/Program.fs#L230), helps in #726.
=> Print file that is will be processed

README.md
=> Update FCS instructions in README

src/Fantomas.Tests/AttributeTests.fs, src/Fantomas/CodePrinter.fs
=> Add newline between assembly level attributes

src/Fantomas.Tests/SignatureTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs
=> Add generic constraints

src/Fantomas.Tests/SynConstTests.fs, src/Fantomas/TokenParser.fs, src/Fantomas/Trivia.fs
=> Don't reformat negative single floating-point numbers

src/Fantomas.Tests/SignatureTests.fs, src/Fantomas.Tests/TypeDeclarationTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/TokenParser.fs, src/Fantomas/Trivia.fs
=> Preserve abstract keyword in signature file

src/Fantomas.Tests/CommentTests.fs
The fix for #810 also fixes #516.
Adding regression test.
=> Adding regression test for #516.

.config/dotnet-tools.json, src/Fantomas.Tests/FormatConfigJsonConfigurationFileTests.fs, src/Fantomas.Tests/FormattingPropertyTests.fs, src/Fantomas.Tests/RecordTests.fs, src/Fantomas.Tests/TestHelpers.fs, src/Fantomas.Tests/TokenParserBoolExprTests.fs, src/Fantomas/AstTransformer.fs, src/Fantomas/CodeFormatterImpl.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/Context.fs, src/Fantomas/FormatConfig.fs, src/Fantomas/Queue.fs, src/Fantomas/SourceParser.fs, src/Fantomas/TokenParser.fs, src/Fantomas/TokenParserBoolExpr.fs, src/Fantomas/Trivia.fs
With this PR it is possible to run FSharpLint
`dotnet fsharplint lint .\fantomas.sln`
and spot little improvements.
=> Add fsharp lint

src/Fantomas.CoreGlobalTool.Tests/ByteOrderMarkTests.fs, src/Fantomas.CoreGlobalTool.Tests/CheckTests.fs, src/Fantomas.CoreGlobalTool.Tests/ConfigTests.fs, src/Fantomas.CoreGlobalTool.Tests/Fantomas.CoreGlobalTool.Tests.fsproj, src/Fantomas.CoreGlobalTool.Tests/TestHelpers.fs, src/Fantomas.Tests/FormatConfigJsonConfigurationFileTests.fs, src/Fantomas/ConfigFile.fs, src/Fantomas/Utils.fs
=> Allow passing fantomas-config.json without any path prefix

src/Fantomas.Tests/LongIdentWithDotsTests.fs, src/Fantomas/CodePrinter.fs
=> Keep start of lambda on same line as dot

RELEASE_NOTES.md, src/Fantomas.CoreGlobalTool.Tests/Fantomas.CoreGlobalTool.Tests.fsproj, src/Fantomas.CoreGlobalTool/Fantomas.CoreGlobalTool.fsproj, src/Fantomas.Tests/ComputationExpressionTests.fs, src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas/CodePrinter.fs, src/Fantomas/Fantomas.fsproj
=> print Trivia before entire LetBang expression

src/Fantomas.Tests/QueueTests.fs, src/Fantomas.Tests/TokenParserTests.fs, src/Fantomas/Context.fs, src/Fantomas/TokenParser.fs, src/Fantomas/Trivia.fs, src/Fantomas/TriviaTypes.fs
Less impressive as the previous PR but still peals of one or two seconds in the benchmark.
TriviaNodeAssigner leads to fewer allocations.
=> Improve perf

src/Fantomas.Tests/CommentTests.fs, src/Fantomas.Tests/TokenParserTests.fs, src/Fantomas.Tests/TriviaTests.fs, src/Fantomas/TokenParser.fs
=> Collect multiple line comments as a single trivia

src/Fantomas/Trivia.fs
On my machine:
before:
```
| Method |    Mean |   Error |   StdDev | Rank |       Gen 0 |       Gen 1 |      Gen 2 | Allocated |
|------- |--------:|--------:|---------:|-----:|------------:|------------:|-----------:|----------:|
| Format | 7.678 s | 1.078 s | 0.0591 s |    1 | 737000.0000 | 229000.0000 | 12000.0000 |   3.47 GB |
```
after:
```
| Method |    Mean |   Error |   StdDev | Rank |       Gen 0 |       Gen 1 |      Gen 2 | Allocated |
|------- |--------:|--------:|---------:|-----:|------------:|------------:|-----------:|----------:|
| Format | 6.627 s | 1.012 s | 0.0555 s |    1 | 611000.0000 | 160000.0000 | 12000.0000 |   2.76 GB |
```
=> Improved triviaBetweenAttributeAndParentBinding

docs/index.html
Fetches the data from table storage and creates something like:
=> Added benchmark result page

src/Fantomas.Tests/TypeDeclarationTests.fs, src/Fantomas/CodePrinter.fs
=> Write out generic type constraint in type definition

src/Fantomas.Tests/SignatureTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/Context.fs
=> Add and keyword between multiple member constraints

README.md
I've created an extension which behaves equivalently to the Format Document/Selection commands for other languages.
=> Add section for Visual Studio extension to the Readme

src/Fantomas.Tests/AttributeTests.fs, src/Fantomas/CodePrinter.fs
Fixes #864, an would be a proper fix for https://github.com/fsprojects/fantomas/issues/304.
=> Fix indentation of multiline attributes

src/Fantomas.Tests/TypeProviderTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/TriviaHelpers.fs
=> Add space before at verbatim string in type abbreviation

src/Fantomas.Tests/CompilerDirectivesTests.fs, src/Fantomas.Tests/MultilineBlockBracketsOnSameColumnRecordTests.fs, src/Fantomas/CodePrinter.fs
=> Print trivia before closing brace

src/Fantomas.Tests/DynamicOperatorTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/Trivia.fs
=> Preserve back ticks for ident after dynamic operator

src/Fantomas.Tests/AttributeTests.fs
This is already fixed, adding a regression test.
Fixes #631.
=> Adding regression test for #631.

src/Fantomas.Tests/PatternMatchingTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/TokenParser.fs
=> Print trivia after clause arrow and function keyword

src/Fantomas.Tests/CompilerDirectivesTests.fs, src/Fantomas/AstTransformer.fs, src/Fantomas/CodePrinter.fs
=> Add compiler defines around parameter type definition

src/Fantomas.Benchmarks/Fantomas.Benchmarks.fsproj, src/Fantomas.CoreGlobalTool.Tests/Fantomas.CoreGlobalTool.Tests.fsproj, src/Fantomas.CoreGlobalTool/Fantomas.CoreGlobalTool.fsproj, src/Fantomas.Extras/Fantomas.Extras.fsproj, src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas.Tests/InterpolatedStringTests.fs, src/Fantomas/AstTransformer.fs, src/Fantomas/CodeFormatterImpl.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/Fantomas.fsproj, src/Fantomas/Trivia.fs
Solves #998.
I think time will tell what is the best approach for multiline constructs in interpolated strings.
This could be good enough for now and we can revisit when more examples pop up.
=> First attempt at interpolated strings.

.config/dotnet-tools.json, src/Fantomas.Benchmarks/Runners.fs, src/Fantomas.Tests/FormatConfigEditorConfigurationFileTests.fs, src/Fantomas.Tests/ModuleTests.fs, src/Fantomas.Tests/TestHelpers.fs, src/Fantomas/AstTransformer.fs, src/Fantomas/CodeFormatterImpl.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceTransformer.fs, src/Fantomas/TokenParser.fs, src/Fantomas/Trivia.fs, src/Fantomas/Utils.fs, src/Fantomas/Version.fs
Keeping a nice tradition in honour.
Thank you @auduchinok.
=> Remove warnings

src/Fantomas.Tests/LambdaTests.fs, src/Fantomas/CodePrinter.fs
=> Don't add extra new line before LongIdentSet.

src/Fantomas.Tests/CompilerDirectivesTests.fs, src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas.Tests/HashDirectiveTests.fs, src/Fantomas/CodePrinter.fs
=> Don't print SynModuleDecl.HashDirective trivia twice

src/Fantomas.Tests/UnionTests.fs, src/Fantomas/CodePrinter.fs
=> Print trivia for UnionCase

src/Fantomas.Tests/LetBindingTests.fs, src/Fantomas/CodePrinter.fs
=> Don't add additional new line before new.

src/Fantomas.Tests/RecordTests.fs, src/Fantomas/CodePrinter.fs
=> Print name of static members

src/Fantomas.Tests/AttributeTests.fs, src/Fantomas.Tests/ComputationExpressionTests.fs, src/Fantomas/CodePrinter.fs
=> Add new line and indent multiline return expression

src/Fantomas.Tests/StringTests.fs, src/Fantomas/CodePrinter.fs
=> Use correct trivia string for SynPat.Const

src/Fantomas.Tests/ClassTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/Context.fs
=> Further indent closing parenthesis for multiline string

src/Fantomas.Tests/ControlStructureTests.fs, src/Fantomas/CodePrinter.fs
=> Print trivia for SynExpr.Assert

src/Fantomas.Tests/ControlStructureTests.fs, src/Fantomas/CodePrinter.fs
=> Print trivia for SynExpr.While

src/Fantomas.Tests/ListTests.fs, src/Fantomas/CodePrinter.fs
=> Print trivia after closing bracket

src/Fantomas.Tests/PatternMatchingTests.fs, src/Fantomas/CodePrinter.fs
=> Print trivia before SynExpr.MatchLambda

src/Fantomas.Tests/LongIdentWithDotsTests.fs, src/Fantomas/CodePrinter.fs
=> Print trivia for SynExpr.LongIdent

src/Fantomas.Tests/ElmishTests.fs, src/Fantomas/CodePrinter.fs
=> Keep comment after closing bracket of elmish element without children

src/Fantomas.Tests/ComputationExpressionTests.fs, src/Fantomas/CodePrinter.fs
=> Select correct SynExpr trivia node type in computation expression body

build.fsx, src/Fantomas.Tests/OperatorTests.fs, src/Fantomas/Trivia.fs
=> Choose SynExpr.Ident instead of SynExpr.App as trivia node

src/Fantomas.Tests/MultilineBlockBracketsOnSameColumnRecordTests.fs, src/Fantomas.Tests/RecordTests.fs, src/Fantomas/CodePrinter.fs
=>  Print comments after closing record brace

src/Fantomas.Tests/SignatureTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceTransformer.fs
=> Don't add extra new line between nested module in signature file

src/Fantomas.Tests/SynExprSetTests.fs, src/Fantomas/CodePrinter.fs
=> Don't add extra new line before SynExpr.LetOrUse inside Sequence

src/Fantomas.Tests/SignatureTests.fs, src/Fantomas/CodePrinter.fs
=> Consider trivia of attribute between SigModuleDecl

src/Fantomas.Tests/ModuleTests.fs, src/Fantomas/CodePrinter.fs
=> Keep extra indent for short single case DU

src/Fantomas.Tests/RecordTests.fs, src/Fantomas/CodePrinter.fs
=> Print trivia after closing multi line record brace

src/Fantomas.Tests/UnionTests.fs, src/Fantomas/CodePrinter.fs
=> Print comment after closing parenthesis of SynType.Paren

src/Fantomas.Tests/SynConstTests.fs, src/Fantomas/TokenParser.fs
=> Capture trivia of int64 number

src/Fantomas.Tests/DotGetTests.fs, src/Fantomas/CodePrinter.fs
=> Don't break line between TypeApp and Parenthesis tuple inside DotGet

RELEASE_NOTES.md, src/Fantomas.CoreGlobalTool.Tests/Fantomas.CoreGlobalTool.Tests.fsproj, src/Fantomas.CoreGlobalTool/Fantomas.CoreGlobalTool.fsproj, src/Fantomas.Extras/Fantomas.Extras.fsproj, src/Fantomas.Tests/DotGetTests.fs, src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas/CodePrinter.fs, src/Fantomas/Fantomas.fsproj
Resolve [remark in 501](https://github.com/fsprojects/fantomas/issues/501#issuecomment-695284222)
=> Further indent desugered lamdba in multi line dotget expression.

src/Fantomas.Tests/CompilerDirectivesTests.fs, src/Fantomas.Tests/LambdaTests.fs, src/Fantomas.Tests/OperatorTests.fs, src/Fantomas/CodePrinter.fs
=> Print trivia before closing parenthesis in desugared lambda

src/Fantomas.Tests/UnionTests.fs
=> Add regression test for static member of union type

src/Fantomas.CoreGlobalTool/Program.fs, src/Fantomas.Tests/TestHelpers.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/Context.fs, src/Fantomas/SourceParser.fs, src/Fantomas/TokenParser.fs, src/Fantomas/Trivia.fs, src/Fantomas/TriviaContext.fs, src/Fantomas/TriviaHelpers.fs
@auduchinok I did find https://youtrack.jetbrains.com/issue/RIDER-51461 and https://youtrack.jetbrains.com/issue/RIDER-51463 which seem incorrect to me.
=> Remove warnings found in Rider 2020.3 EAP.

build.fsx, src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas.Tests/SynExprNewTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs
=> Put multi line named argument on next line

src/Fantomas.Tests/MultilineBlockBracketsOnSameColumnRecordTests.fs, src/Fantomas.Tests/NumberOfItemsRecordTests.fs, src/Fantomas.Tests/RecordTests.fs, src/Fantomas/CodePrinter.fs
=> Revisit formatting of SynPat.Record

src/Fantomas.Tests/AppTests.fs, src/Fantomas.Tests/CommentTests.fs, src/Fantomas.Tests/CompilerDirectivesTests.fs, src/Fantomas.Tests/ComputationExpressionTests.fs, src/Fantomas.Tests/DisableElmishTests.fs, src/Fantomas.Tests/DotGetTests.fs, src/Fantomas.Tests/ElmishTests.fs, src/Fantomas.Tests/KeepIfThenInSameLineTests.fs, src/Fantomas.Tests/LambdaTests.fs, src/Fantomas.Tests/LetBindingTests.fs, src/Fantomas.Tests/ListTests.fs, src/Fantomas.Tests/LongIdentWithDotsTests.fs, src/Fantomas.Tests/NumberOfItemsListOrArrayTests.fs, src/Fantomas.Tests/OperatorTests.fs, src/Fantomas.Tests/PatternMatchingTests.fs, src/Fantomas.Tests/StringTests.fs, src/Fantomas.Tests/SynExprSetTests.fs, src/Fantomas.Tests/TypeDeclarationTests.fs, src/Fantomas.Tests/TypeProviderTests.fs, src/Fantomas/CodePrinter.fs
=> Put lambdas on next line in multiline function calls

src/Fantomas.Tests/CastTests.fs, src/Fantomas/CodePrinter.fs
=> Add SynExpr_Upcast and SynExpr_Downcast to genTrivia of genExpr.

RELEASE_NOTES.md, paket.dependencies, paket.lock, src/Fantomas.CoreGlobalTool.Tests/Fantomas.CoreGlobalTool.Tests.fsproj, src/Fantomas.CoreGlobalTool/Fantomas.CoreGlobalTool.fsproj, src/Fantomas.Extras/Fantomas.Extras.fsproj, src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas/Fantomas.fsproj
=> Release notes for 4.3.0-alpha-004

src/Fantomas.Tests/UnionTests.fs, src/Fantomas/CodePrinter.fs
=> genTrivia for SynEnumCase

src/Fantomas.Tests/LetBindingTests.fs, src/Fantomas/CodePrinter.fs
=> Respect the order of keyword in a letbinding

src/Fantomas.Tests/PatternMatchingTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs
=> Keep SynPat.Or in same line unless in pattern match

src/Fantomas.Tests/ListTests.fs, src/Fantomas/CodePrinter.fs
=> Respect indentation of multiline yield bang inside ArrayOrListOfSeqExpr

src/Fantomas.Tests/AppTests.fs, src/Fantomas.Tests/ClassTests.fs, src/Fantomas.Tests/CompilerDirectivesTests.fs, src/Fantomas.Tests/LetBindingTests.fs, src/Fantomas.Tests/OperatorTests.fs, src/Fantomas.Tests/RecordTests.fs, src/Fantomas.Tests/StringTests.fs, src/Fantomas/CodePrinter.fs
=> Follow the normal flow for multiline strings in function applications

RELEASE_NOTES.md, src/Fantomas.CoreGlobalTool.Tests/Fantomas.CoreGlobalTool.Tests.fsproj, src/Fantomas.CoreGlobalTool/Fantomas.CoreGlobalTool.fsproj, src/Fantomas.Extras/Fantomas.Extras.fsproj, src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas.Tests/IfThenElseTests.fs, src/Fantomas.Tests/PatternMatchingTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/Fantomas.fsproj, src/Fantomas/SourceParser.fs
Issues I discovered while formatting Fantomas.
=> Fix regressions

src/Fantomas.Tests/CompilerDirectivesTests.fs, src/Fantomas.Tests/ComputationExpressionTests.fs, src/Fantomas.Tests/LetBindingTests.fs, src/Fantomas/CodePrinter.fs
=> Indent and add newline for multiline do(bang) expressions

src/Fantomas.Tests/IfThenElseTests.fs, src/Fantomas/CodePrinter.fs
=> Add parenthesis for multiline function application in if/then condition

src/Fantomas.Tests/TupleTests.fs, src/Fantomas/CodePrinter.fs
=> fix long tuple formatting with lambda or match

src/Fantomas.Tests/CodeFormatterTests.fs, src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas/CodeFormatterImpl.fs
=>  Replace Program.fs file name.

src/Fantomas.Tests/LetBindingTests.fs, src/Fantomas.Tests/TupleTests.fs, src/Fantomas/CodePrinter.fs
=> Print trivia after equal sign in SynBinding

docs/Documentation.md, src/Fantomas.Tests/ActivePatternTests.fs, src/Fantomas.Tests/AppTests.fs, src/Fantomas.Tests/CompilerDirectivesTests.fs, src/Fantomas.Tests/ComputationExpressionTests.fs, src/Fantomas.Tests/ControlStructureTests.fs, src/Fantomas.Tests/DynamicOperatorTests.fs, src/Fantomas.Tests/IfThenElseTests.fs, src/Fantomas.Tests/InterfaceTests.fs, src/Fantomas.Tests/LetBindingTests.fs, src/Fantomas.Tests/PatternMatchingTests.fs, src/Fantomas.Tests/RecordTests.fs, src/Fantomas.Tests/TupleTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/RangeHelpers.fs, src/Fantomas/TriviaHelpers.fs, src/Fantomas/Utils.fs
=> Revisit if/then/else according to MS style guide.

RELEASE_NOTES.md, src/Fantomas.CoreGlobalTool.Tests/Fantomas.CoreGlobalTool.Tests.fsproj, src/Fantomas.CoreGlobalTool/Fantomas.CoreGlobalTool.fsproj, src/Fantomas.Extras/Fantomas.Extras.fsproj, src/Fantomas.Tests/AppTests.fs, src/Fantomas.Tests/ControlStructureTests.fs, src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas.Tests/IfThenElseTests.fs, src/Fantomas.Tests/LetBindingTests.fs, src/Fantomas.Tests/LongIdentWithDotsTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/Fantomas.fsproj
Related to #1258, I did not yet take the SynExpr.IfThenElse without else branches into account.
=> Revisit if then without else

src/Fantomas.Tests/SpaceBeforeUppercaseInvocationTests.fs
#1226 does not appear to be a problem anymore.
Adding regression test.
=> Add regression test for #1226.

src/Fantomas.Tests/SynExprSetTests.fs, src/Fantomas/CodePrinter.fs
=> Revisit multi line mutable setter assignment.

src/Fantomas.Tests/ListTests.fs
=> Add regression test for atCurrentColumn usage inside ArrayOrList

src/Fantomas.Tests/PatternMatchingTests.fs, src/Fantomas/CodePrinter.fs
=> Put multiline when condition on the next line.

src/Fantomas.Tests/IfThenElseTests.fs, src/Fantomas/CodePrinter.fs
=> Add parenthesis around multi line if/then/else that is piped.

src/Fantomas.Tests/TupleTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/Context.fs
=> Add parenthesis around multi line if/then/else inside tuple

src/Fantomas.Tests/DynamicOperatorTests.fs, src/Fantomas.Tests/IfThenElseTests.fs, src/Fantomas/CodePrinter.fs
=> Add parenthesis around multi line if/then/else before infix.

src/Fantomas.Tests/AppTests.fs, src/Fantomas.Tests/DotGetTests.fs, src/Fantomas.Tests/InterfaceTests.fs, src/Fantomas.Tests/RecordTests.fs, src/Fantomas.Tests/TypeDeclarationTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs, src/Fantomas/TriviaContext.fs
=> Revisit member bindings.

.gitpod.yml, RELEASE_NOTES.md, src/Fantomas.CoreGlobalTool.Tests/Fantomas.CoreGlobalTool.Tests.fsproj, src/Fantomas.CoreGlobalTool/Fantomas.CoreGlobalTool.fsproj, src/Fantomas.Extras/Fantomas.Extras.fsproj, src/Fantomas.Tests/CodeFormatterTests.fs, src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas/CodeFormatterImpl.fs, src/Fantomas/Fantomas.fsproj
=> Validate filename

src/Fantomas.Tests/PatternMatchingTests.fs, src/Fantomas/CodePrinter.fs
=> Add atCurrentColumnIndent to match expression

src/Fantomas.Tests/FunctionDefinitionTests.fs, src/Fantomas/CodePrinter.fs
=> Reset IsMemberDefinition in genLetBinding.

src/Fantomas.Tests/CommentTests.fs, src/Fantomas/CodePrinter.fs
issue  #1220 
Added the genTrivia method in the genParsedHashDirective.
=> add genTrivia in genParsedHashDirective 1220

src/Fantomas.Tests/ClassTests.fs, src/Fantomas.Tests/TypeDeclarationTests.fs, src/Fantomas/CodePrinter.fs
=> Update formatting of class constructors

src/Fantomas.Tests/SynExprNewTests.fs, src/Fantomas/CodePrinter.fs
=> Format SynExpr.New with a non tuple argument.

src/Fantomas.Tests/PatternMatchingTests.fs, src/Fantomas/CodePrinter.fs
Fixes #1364.
ASTContext is evil and I should know better...
=> Remove IsMemberDefinition from ASTContext

src/Fantomas.Tests/IfThenElseTests.fs, src/Fantomas/CodePrinter.fs
=> Indent arguments far enough in function application inside if expression. 

src/Fantomas.Tests/ElmishTests.fs, src/Fantomas.Tests/ListTests.fs, src/Fantomas.Tests/MultilineBlockBracketsOnSameColumnArrayOrListTests.fs, src/Fantomas.Tests/RecordTests.fs, src/Fantomas/CodePrinter.fs
=> Indent expression inside ArrayOrListOfSeqExpr atCurrentColumnIndent

src/Fantomas.Tests/InterfaceTests.fs, src/Fantomas/CodePrinter.fs
=> Print trivia before object expression

src/Fantomas.Tests/SignatureTests.fs, src/Fantomas/CodePrinter.fs
=> Keep inline keyword in signature type member.

src/Fantomas.Tests/SignatureTests.fs, src/Fantomas.Tests/TypeDeclarationTests.fs, src/Fantomas/CodePrinter.fs
=> Further indent constraint in multi line member definition.

src/Fantomas.Tests/ControlStructureTests.fs, src/Fantomas/CodePrinter.fs
=> Format multiple clauses named underneath each other

src/Fantomas.Tests/ListTests.fs, src/Fantomas.Tests/MultilineBlockBracketsOnSameColumnArrayOrListTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs
=> Always put lambdas in an array/list multiline.

src/Fantomas.Tests/AppTests.fs, src/Fantomas.Tests/AttributeTests.fs, src/Fantomas.Tests/ClassTests.fs, src/Fantomas.Tests/CommentTests.fs, src/Fantomas.Tests/CompilerDirectivesTests.fs, src/Fantomas.Tests/ComputationExpressionTests.fs, src/Fantomas.Tests/ControlStructureTests.fs, src/Fantomas.Tests/DisableElmishTests.fs, src/Fantomas.Tests/FormatAstTests.fs, src/Fantomas.Tests/FunctionDefinitionTests.fs, src/Fantomas.Tests/HashDirectiveTests.fs, src/Fantomas.Tests/InterfaceTests.fs, src/Fantomas.Tests/LetBindingTests.fs, src/Fantomas.Tests/ListTests.fs, src/Fantomas.Tests/MaxFunctionBindingWidthTests.fs, src/Fantomas.Tests/ModuleTests.fs, src/Fantomas.Tests/NewlineBetweenTypeDefinitionAndMembersTests.fs, src/Fantomas.Tests/NumberOfItemsRecordTests.fs, src/Fantomas.Tests/OperatorTests.fs, src/Fantomas.Tests/RecordTests.fs, src/Fantomas.Tests/SignatureTests.fs, src/Fantomas.Tests/SpaceBeforeSemicolonTests.fs, src/Fantomas.Tests/SpecialConstructsTests.fs, src/Fantomas.Tests/StructTests.fs, src/Fantomas.Tests/TypeDeclarationTests.fs, src/Fantomas/CodePrinter.fs
=> Surround return type annotations with white space.

.gitpod.yml, RELEASE_NOTES.md, src/Fantomas.CoreGlobalTool.Tests/Fantomas.CoreGlobalTool.Tests.fsproj, src/Fantomas.CoreGlobalTool/Fantomas.CoreGlobalTool.fsproj, src/Fantomas.Extras/Fantomas.Extras.fsproj, src/Fantomas.Tests/DotGetTests.fs, src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas/CodePrinter.fs, src/Fantomas/Fantomas.fsproj
=> Don't add space between first function call in chain.

src/Fantomas.Tests/PatternMatchingTests.fs, src/Fantomas/CodePrinter.fs
=> Put match inside match on the next line.

src/Fantomas.Tests/ComputationExpressionTests.fs, src/Fantomas/CodePrinter.fs
As promised, here is a PR adressing #1463.
Please let me know if there is something I should improve here :)
Thanks for taking your time!
=> Add genTrivia for SynExpr.JoinIn. Fixes #1463

src/Fantomas.Tests/DotGetTests.fs
While I was hanging around this repo I though "why not pick some more stuff here".
So here is a quick and simple regression test for #1422.
The returned output reflects fantomas-tools as of e1054c1501b4eadb5fefa7b08daa8fb0f2b6153a
=> Add regression test for #1422

src/Fantomas.Tests/DotIndexedGetTests.fs
Add regression test to account for fix of problem in #1407, to verify that it was fixed by #1415
=> Add regression test to account for fix of problem in #1407

src/Fantomas.Tests/AppTests.fs, src/Fantomas.Tests/DotIndexedGetTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs
=> Remove unit expression from AppSingleArg active pattern.

src/Fantomas.Tests/FunctionDefinitionTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs
=> Don't repeat parenthesis in SynType. 

src/Fantomas.Tests/RecordTests.fs, src/Fantomas/CodePrinter.fs
=> Add space before paren in funcall

src/Fantomas.Tests/LetBindingTests.fs, src/Fantomas.Tests/OperatorTests.fs, src/Fantomas/CodePrinter.fs
=> Add in keyword when LetOrUse is part of infix expression.

src/Fantomas.Tests/ControlStructureTests.fs, src/Fantomas.Tests/IfThenElseTests.fs, src/Fantomas/CodePrinter.fs
=> Put multiline match inside if expression on the next line.

src/Fantomas.Tests/CompilerDirectivesTests.fs
=> Add regression test for define above SynExpr.Do.

src/Fantomas.Tests/IfThenElseTests.fs
=> Add regression test for multiline yield bang in if/then expression.

src/Fantomas.Tests/ElmishTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/Context.fs, src/Fantomas/SourceParser.fs, src/Fantomas/TriviaHelpers.fs
=> Create custom range for brackets in Elmish elements inside of full SynExpr range.

CONTRIBUTING.md
@Smaug123, @jgiannuzzi or @stackedsax could you review my prose, please?
The usual English and grammar and stuff.
Thanks!
=> Add additional pointers to the Contribution Guidelines.

src/Fantomas.Tests/CommentTests.fs, src/Fantomas/TokenParser.fs
Refactored the construction of `LineCommentOnSingleLine` and `LineCommentAfterSourceCode` from F# tokens.
=> Optimize tokens to LineCommentOnSingleLine and LineCommentAfterSourceCode trivia.

src/Fantomas.Tests/InterfaceTests.fs, src/Fantomas.Tests/SignatureTests.fs, src/Fantomas.Tests/TypeDeclarationTests.fs, src/Fantomas/CodePrinter.fs
=> Don't indent in genTypeList.

src/Fantomas.Tests/SynConstTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/TokenParser.fs, src/Fantomas/TriviaHelpers.fs, src/Fantomas/TriviaTypes.fs
=> Print trivia around SynConst and correct line comment construction

RELEASE_NOTES.md, docs/Documentation.md, src/Fantomas.CoreGlobalTool.Tests/Fantomas.CoreGlobalTool.Tests.fsproj, src/Fantomas.CoreGlobalTool/Fantomas.CoreGlobalTool.fsproj, src/Fantomas.Extras/Fantomas.Extras.fsproj, src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas.Tests/FormatConfigEditorConfigurationFileTests.fs, src/Fantomas.Tests/KeepIndentInBranch.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/Context.fs, src/Fantomas/Fantomas.fsproj, src/Fantomas/FormatConfig.fs, src/Fantomas/SourceParser.fs, src/Fantomas/SourceTransformer.fs
A first attempt to get to the behaviour of https://github.com/fsprojects/fantomas/issues/1361.
I would need some more examples to detect if all use-cases are covered by this.
The solution is based on the AST of the source so that is still in spirit with the project.
Please take a look at the unit tests and let me know if this is a good start.
=> Initial support of setting KeepIndentInBranch.

src/Fantomas.Tests/NewlineBetweenTypeDefinitionAndMembersTests.fs, src/Fantomas.Tests/TypeDeclarationTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/Context.fs, src/Fantomas/TriviaHelpers.fs
=> Print trivia before with keyword.

src/Fantomas.Tests/OperatorTests.fs, src/Fantomas/TokenParser.fs, src/Fantomas/TriviaTypes.fs
=> Add QMARK_QMARK to FsTokenType.

src/Fantomas.Tests/CompilerDirectivesTests.fs, src/Fantomas/CodePrinter.fs
=> genTrivia for SynExpr.TypeApp.

src/Fantomas.Tests/InterpolatedStringTests.fs, src/Fantomas/CodePrinter.fs
=> Print format in SynInterpolatedStringPart.FillExpr.

src/Fantomas.Tests/DotGetTests.fs, src/Fantomas/CodePrinter.fs
=> Print typed argument in dotget with lambda.

src/Fantomas.Tests/OperatorTests.fs, src/Fantomas/CodePrinter.fs
=> Add in keyword to multiple let binding in infix expression.

src/Fantomas.Tests/SignatureTests.fs, src/Fantomas/CodePrinter.fs
=> Print trivia before SynTypeDefnSimpleRepr.Union in signature files

src/Fantomas.Tests/ComputationExpressionTests.fs, src/Fantomas.Tests/OperatorTests.fs, src/Fantomas.Tests/PatternMatchingTests.fs, src/Fantomas/CodePrinter.fs
=> Indent match lambda in multiline infix expression

src/Fantomas.Tests/SignatureTests.fs, src/Fantomas/AstExtensions.fs, src/Fantomas/AstTransformer.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/Context.fs, src/Fantomas/Fantomas.fsproj, src/Fantomas/SourceParser.fs, src/Fantomas/TriviaTypes.fs
=> Print trivia of TypeDefnSig using FullRange extension.

src/Fantomas.Tests/IfThenElseTests.fs, src/Fantomas/CodePrinter.fs
=> Apply alternative app format in infix in if expr

src/Fantomas.Tests/KeepIndentInBranch.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs
=> Add more scenarios for KeepIndentInBranch.

src/Fantomas.Tests/TypeDeclarationTests.fs, src/Fantomas/CodePrinter.fs
=> Print const keyword for TStaticConstantExpr.

src/Fantomas.Tests/AttributeTests.fs, src/Fantomas/CodePrinter.fs
=> Print byref as & in extern function declaration.

src/Fantomas.Tests/TokenParserTests.fs, src/Fantomas/TokenParser.fs
=> Take line comments into account when parsing defines from source.

src/Fantomas.Tests/TypeDeclarationTests.fs, src/Fantomas/CodePrinter.fs
=> Print trivia of SynSimplePats_SimplePats.

src/Fantomas.Tests/IfThenElseTests.fs, src/Fantomas/CodePrinter.fs
=> Add newline between multiline infix expression in if expression.

src/Fantomas.Tests/IfThenElseTests.fs, src/Fantomas/CodePrinter.fs
=> Put multiline if expression with comment on next line. 

src/Fantomas.Tests/AppTests.fs, src/Fantomas/CodePrinter.fs
=> Print trivia for SynExpr.Paren in alternate style

src/Fantomas.Tests/SignatureTests.fs, src/Fantomas.Tests/TypeDeclarationTests.fs, src/Fantomas/CodePrinter.fs
=> Format multiline type function signature in multiple lines.

src/Fantomas.Tests/OperatorTests.fs, src/Fantomas/TokenParser.fs, src/Fantomas/TriviaTypes.fs
=> Add DOLLAR token to FsTokenType.

src/Fantomas.Tests/CompilerDirectivesTests.fs, src/Fantomas/Trivia.fs
=> Use findFirstNodeAfterLine to assign Directive trivia.

src/Fantomas.Tests/ElmishTests.fs, src/Fantomas/CodePrinter.fs
=> Print trivia of brackets in ElmishReactWithChildren.

src/Fantomas.Tests/LetBindingTests.fs, src/Fantomas/TokenParser.fs
=> Don't combine LineCommentAfterSourceCode and LineCommentOnSingleLine as one trivia. 

src/Fantomas.Tests/SignatureTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs
=> Take attribute trivia into account for SynTypeDefnSig. 

src/Fantomas.Tests/MultiLineLambdaClosingNewlineTests.fs, src/Fantomas/CodePrinter.fs
=> Print trivia of SynExpr_Paren in MultiLineLambdaClosingNewline.

src/Fantomas.Tests/LetBindingTests.fs, src/Fantomas.Tests/VerboseSyntaxConversionTests.fs, src/Fantomas/CodePrinter.fs
=> Don't determine isInSameLine based on ranges.

src/Fantomas.Tests/InterpolatedStringTests.fs, src/Fantomas/TokenParser.fs
=> Detect newlines in interpolated strings. 

src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas.Tests/KeepIndentInBranchTests.fs, src/Fantomas/CodePrinter.fs
=> Take combo sequentials, LetOrUse into account for KeepIndentInBranch setting.

src/Fantomas.Tests/LetBindingTests.fs, src/Fantomas/CodePrinter.fs
=> Add unindent to long TFuns.

src/Fantomas.Tests/LetBindingTests.fs, src/Fantomas.Tests/SignatureTests.fs, src/Fantomas.Tests/TypeDeclarationTests.fs, src/Fantomas/CodePrinter.fs
=> Put arrow before type arg instead of on last line.

src/Fantomas.Tests/KeepIndentInBranchTests.fs, src/Fantomas.Tests/TypeDeclarationTests.fs, src/Fantomas/SourceParser.fs
=> Consider simple function application as short branch expr.

src/Fantomas.Tests/InterpolatedStringTests.fs, src/Fantomas/TokenParser.fs
=> Consider $@" as special string start.

src/Fantomas.Tests/CommentTests.fs, src/Fantomas/TokenParser.fs
=> Consider comment after single semicolon as LineCommentOnSingleLine

src/Fantomas.Tests/ControlStructureTests.fs, src/Fantomas/CodePrinter.fs
=> Only indent match  clause if setting IndentOnTryWith is active.

src/Fantomas.Tests/ElmishTests.fs, src/Fantomas/CodePrinter.fs
=> Print trivia between empty dual list Elmish children. 

src/Fantomas.Tests/DotGetTests.fs, src/Fantomas/CodePrinter.fs
=> Add space before dotget lambda function.

src/Fantomas.Tests/CastTests.fs, src/Fantomas.Tests/CommentTests.fs, src/Fantomas.Tests/ComputationExpressionTests.fs, src/Fantomas/CodePrinter.fs
=> Print trivia for SynExpr explicitly.

src/Fantomas.Tests/ControlStructureTests.fs, src/Fantomas/CodePrinter.fs
=> Trivia before bar of try with clause should indent.

src/Fantomas.Tests/BlankLinesAroundNestedMultilineExpressions.fs, src/Fantomas.Tests/TypeDeclarationTests.fs, src/Fantomas/CodePrinter.fs
=> Collect recursive types using ColMultilineItem.

src/Fantomas.Tests/LambdaTests.fs, src/Fantomas.Tests/PatternMatchingTests.fs, src/Fantomas/Context.fs, src/Fantomas/Queue.fs, src/Fantomas/Trivia.fs
Something went wrong while merging https://github.com/fsprojects/fantomas/pull/1656.
I noticed the latest changes were not in there.
=> Correct bad merge of PR 1656.

src/Fantomas.Tests/PatternMatchingTests.fs, src/Fantomas/CodePrinter.fs
=> Don't add parenthesis if last clause is single line.

src/Fantomas.Tests/OperatorTests.fs, src/Fantomas/SourceParser.fs
=> Exclude infix applications as Elmish pattern.

docs/Documentation.md, src/Fantomas.CoreGlobalTool.Tests/ByteOrderMarkTests.fs, src/Fantomas.CoreGlobalTool.Tests/CheckTests.fs, src/Fantomas.CoreGlobalTool.Tests/ConfigTests.fs, src/Fantomas.CoreGlobalTool.Tests/ExitCodeTests.fs, src/Fantomas.CoreGlobalTool.Tests/Fantomas.CoreGlobalTool.Tests.fsproj, src/Fantomas.CoreGlobalTool.Tests/IgnoreFilesTests.fs, src/Fantomas.CoreGlobalTool.Tests/MultiplePathsTests.fs, src/Fantomas.CoreGlobalTool.Tests/TestHelpers.fs, src/Fantomas.CoreGlobalTool/Program.fs, src/Fantomas/CodeFormatterImpl.fs
Fixes #1696.
I took an interest in this as it opens the door to sunset the `--recurse` flag eventually.
=> Feature multiple files in cli

src/Fantomas.Tests/KeepIndentInBranchTests.fs, src/Fantomas/CodePrinter.fs
=> Indent multiline if condition for KeepIndentInBranch. 

src/Fantomas.Tests/KeepIndentInBranchTests.fs, src/Fantomas/CodePrinter.fs
=> Combine KeepIndentInBranch and MultiLineLambdaClosingNewline. 

src/Fantomas.Tests/IfThenElseTests.fs, src/Fantomas/CodePrinter.fs
=> Process nested dotget app paren in multiline if expression. 

src/Fantomas.Tests/BlankLinesAroundNestedMultilineExpressions.fs, src/Fantomas.Tests/ColMultilineItemTests.fs, src/Fantomas.Tests/CompilerDirectivesTests.fs, src/Fantomas.Tests/ComputationExpressionTests.fs, src/Fantomas.Tests/ControlStructureTests.fs, src/Fantomas.Tests/DotGetTests.fs, src/Fantomas.Tests/IfThenElseTests.fs, src/Fantomas.Tests/InterpolatedStringTests.fs, src/Fantomas.Tests/KeepIndentInBranchTests.fs, src/Fantomas.Tests/LetBindingTests.fs, src/Fantomas.Tests/LongIdentWithDotsTests.fs, src/Fantomas.Tests/MultilineFunctionApplicationsInConditionExpressionsTests.fs, src/Fantomas.Tests/OperatorTests.fs, src/Fantomas.Tests/PatternMatchingTests.fs, src/Fantomas/CodePrinter.fs
=> Always place try/with clause on the next line with a bar. 

src/Fantomas.Tests/ControlStructureTests.fs, src/Fantomas/CodePrinter.fs
=> Wrap try/with expression with atCurrentColumn.

src/Fantomas.Tests/ColMultilineItemTests.fs, src/Fantomas/Context.fs
=> Keep track of newline inside trivia via special event WriteLineInsideTrivia

docs/Documentation.md, src/Fantomas.Tests/BarBeforeDiscriminatedUnionDeclarationTests.fs, src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas.Tests/FormatConfigEditorConfigurationFileTests.fs, src/Fantomas.Tests/KeepBarBeforeDiscriminatedUnionDeclarationTests.fs, src/Fantomas.Tests/UnionTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/Fantomas.fsproj, src/Fantomas/FormatConfig.fs
First attempt to fix #1750.
Let me know if you have another name in mind for the setting @Smaug123.
=> Introduce new setting KeepBarBeforeDiscriminatedUnionDeclaration.

src/Fantomas.Tests/KeepIndentInBranchTests.fs, src/Fantomas/CodePrinter.fs
=> Print trivia after arrow in last clause.

src/Fantomas.Tests/CommentTests.fs
=> Add regression test for newline followed by line comment.

.github/workflows/main.yml, paket.dependencies, paket.lock, src/Fantomas.Tests/SynConstTests.fs
=> Add regression test for concatenation of multi-line triple quote strings

src/Fantomas.Tests/UnionTests.fs
=> Add regression test for comment above union case in signature file.

src/Fantomas.Tests/KeepIndentInBranchTests.fs, src/Fantomas/SourceParser.fs
=> Keep indent for newline infix application. 

src/Fantomas.Tests/CompilerDirectivesTests.fs, src/Fantomas/CodePrinter.fs
=> Print trivia above recursive binding in type definition.

README.md, docs/Documentation.md, src/Fantomas.Tests/ClassTests.fs, src/Fantomas.Tests/CommentTests.fs, src/Fantomas.Tests/CompilerDirectivesTests.fs, src/Fantomas.Tests/ComputationExpressionTests.fs, src/Fantomas.Tests/ControlStructureTests.fs, src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas.Tests/FunctionDefinitionTests.fs, src/Fantomas.Tests/HashDirectiveTests.fs, src/Fantomas.Tests/IfThenElseTests.fs, src/Fantomas.Tests/InterfaceTests.fs, src/Fantomas.Tests/LetBindingTests.fs, src/Fantomas.Tests/ListTests.fs, src/Fantomas.Tests/RecordTests.fs, src/Fantomas.Tests/SpaceBeforeColonTests.fs, src/Fantomas.Tests/SpecialConstructsTests.fs, src/Fantomas.Tests/StructTests.fs, src/Fantomas.Tests/SynConstTests.fs, src/Fantomas.Tests/TypeDeclarationTests.fs, src/Fantomas/CodePrinter.fs
=> Update space before colon to F# style guide

src/Fantomas.Tests/LambdaTests.fs, src/Fantomas/SourceParser.fs
=> Take amount of lambda parameters into account when finding the lambda body

src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas.Tests/LibraryOnlySynExprTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs
=> Add support for SynExpr.LibraryOnlyStaticOptimization.

src/Fantomas.Tests/LambdaTests.fs, src/Fantomas/SourceParser.fs
=> Take single tuple parameter in lambda into account to capture lambda body.

src/Fantomas.Tests/RecordTests.fs, src/Fantomas/CodePrinter.fs
=> Control semicolon in pattern list via setting.

src/Fantomas.Tests/LetBindingTests.fs, src/Fantomas/CodePrinter.fs
=> Put sequential atCurrentColom inside parenthesis.

src/Fantomas.Tests/KeepIndentInBranchTests.fs, src/Fantomas/SourceParser.fs
=> Consider tuple as short branch in KeepIndentInBranch setting.

src/Fantomas.Tests/PatternMatchingTests.fs
This was fixed in #1501.
Adding regression test to fix #1234.
=> Add regression test for #1234.

src/Fantomas.Tests/KeepIndentInBranchTests.fs, src/Fantomas/CodePrinter.fs
=> Add space after long if expression in KeepIndentInBranch. 

src/Fantomas.Tests/MultilineBlockBracketsOnSameColumnRecordTests.fs, src/Fantomas.Tests/SignatureTests.fs, src/Fantomas/CodePrinter.fs
=> Unindent after record and before members.

src/Fantomas.Tests/LetBindingTests.fs, src/Fantomas.Tests/TypeDeclarationTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs
=> Collect ColMultilineItem using continuation passing style. 

.config/dotnet-tools.json, src/Fantomas.CoreGlobalTool.Tests/CheckTests.fs, src/Fantomas.CoreGlobalTool/Program.fs, src/Fantomas.Tests/FsUnit.fs, src/Fantomas.Tests/TokenParserBoolExprTests.fs, src/Fantomas.Tests/UtilsTests.fs, src/Fantomas/Utils.fs
Also added a couple of clean ups.
=> Update Fantomas and FSharpLint.

docs/Documentation.md
I don't know if this is correct, but it looks like a copy/paste that didn't get fixed.
=> Make record_* use consistent

src/Fantomas.CoreGlobalTool/Program.fs
No contribution is too small right 😉
=> Fix CLI arguments help typo

.config/dotnet-tools.json, global.json, src/Fantomas.Tests/PatternMatchingTests.fs, src/Fantomas/AstTransformer.fs, src/Fantomas/TriviaTypes.fs
=> Remove SynPat_Or as trivia node candidate. 

src/Fantomas.Tests/AppTests.fs, src/Fantomas.Tests/TypeDeclarationTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs
=> Print trivia for less and greater tokens of TypeApp. 

src/Fantomas.Tests/CompilerDirectivesTests.fs, src/Fantomas.Tests/ComputationExpressionTests.fs, src/Fantomas/SourceParser.fs
=> Consider LetOrUseBang inside Sequential as CompExprBody

src/Fantomas.Tests/ClassTests.fs, src/Fantomas/CodePrinter.fs
Fixes https://github.com/fsprojects/fantomas/issues/1442
=> Avoid vanity alignment in base ctor call

src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs
=> Remove option wrap for tuple range. 

src/Fantomas.Tests/SignatureTests.fs, src/Fantomas/SourceParser.fs
=> Add ticks to mod identifier. 

src/Fantomas.Client/FantomasToolLocator.fs, src/Fantomas.Client/LSPFantomasService.fs, src/Fantomas.Client/LSPFantomasServiceTypes.fs
In preparation for the call discussed in https://github.com/fsprojects/fantomas/issues/1982, I'd like to add some additional error handling to be able to pinpoint what step exactly is going wrong.
@baronfel would you mind taking a look at this? Just as a sanity review kinda thing.
=> Add more detailed information when the daemon fails to start.

src/Fantomas.CoreGlobalTool.Tests/Fantomas.CoreGlobalTool.Tests.fsproj, src/Fantomas.CoreGlobalTool.Tests/WriteTests.fs, src/Fantomas.CoreGlobalTool/Program.fs
=> Fix 1984: Don't rewrite unchanged files

docs/Documentation.md, src/Fantomas.Extras/EditorConfig.fs, src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas.Tests/FormatConfigEditorConfigurationFileTests.fs, src/Fantomas.Tests/InsertFinalNewlineTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/FormatConfig.fs, src/Fantomas/Queue.fs
Adding support for `insert_final_newline`, see https://editorconfig.org/
Fixes #2002
=> Add support for insert_final_newline.

src/Fantomas.Tests/AttributeTests.fs, src/Fantomas/AstExtensions.fs, src/Fantomas/AstTransformer.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/TriviaTypes.fs
=> Preserve trivia after attributes before name of nested module

src/Fantomas.Tests/KeepIndentInBranchTests.fs
=> Add regression test for preservation of else if. 

src/Fantomas/SourceParser.fs
=> Remove isFunctionBinding

src/Fantomas/AstTransformer.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs, src/Fantomas/Trivia.fs
Use constant range in SynEnumCase.
=> Improve SynEnumCase

src/Fantomas.Tests/ElmishTests.fs, src/Fantomas/CodePrinter.fs
=> Keep comment after opening bracket in ElmishReactWithoutChildren expression. 

src/Fantomas.Tests/Fantomas.Tests.fsproj, src/Fantomas.Tests/LazyTests.fs, src/Fantomas.Tests/SingleExprTests.fs, src/Fantomas/AstTransformer.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/RangeHelpers.fs, src/Fantomas/SourceParser.fs, src/Fantomas/TriviaTypes.fs
Fixes #1875.
Let me know @panmau if you want a revision release for this.
=> Extract keyword for SingleExpr expressions.

src/Fantomas.Tests/NumberOfItemsRecordTests.fs
=> Enable brace related test

src/Fantomas.Tests/CommentTests.fs, src/Fantomas.Tests/InterfaceTests.fs, src/Fantomas/AstTransformer.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs
Fixes #2052.
@bent-rasmussen, please let me know if you want a hotfix release for this issue.
=> Visit SynTypar indent in AstTransformer.fs.

src/Fantomas.Tests/CommentTests.fs, src/Fantomas/AstTransformer.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs, src/Fantomas/TriviaTypes.fs
=> Add less and greater FsAstType types for SynExpr.TypeApp and SynTypeApp. 

src/Fantomas.Tests/ListTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs
Fixes #2055
Not totally sure, if this is the fix you had in mind, but could be a start.
=> Fix 2055: multiple if statements as list comprehension

src/Fantomas.Tests/IndexSyntaxTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs
=> Don't consider negative numbers as atomic.

src/Fantomas.Tests/MultilineBlockBracketsOnSameColumnRecordTests.fs, src/Fantomas.Tests/RecordTests.fs, src/Fantomas/AstTransformer.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs
=> Fix 2067: Comments in anonymous record values are deleted

src/Fantomas.Tests/TypeDeclarationTests.fs, src/Fantomas/CodePrinter.fs
=> Fix 2075: type declaration loses 'when' qualifier

src/Fantomas.Tests/AppTests.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs
=> Print trivia before named argument application. 

CONTRIBUTING.md
Fixes #2065.
Could you please review @Smaug123?
Thanks.
=> Add additional information about the style guide in CONTRIBUTING.md.

src/Fantomas.Tests/DotGetTests.fs, src/Fantomas/CodePrinter.fs
=> Print trivia for all lids in genLidsWithDots. 

CHANGELOG.md, src/Fantomas.Tests/RecordTests.fs, src/Fantomas.Tests/TypeDeclarationTests.fs
=> Add regression tests for lost comments after equals sign.

CHANGELOG.md, src/Fantomas.Tests/PatternMatchingTests.fs
=> Add regression test for comment after match keyword

CHANGELOG.md, src/Fantomas.Tests/LetBindingTests.fs
=> Add regression test for in keyword in SynExpr.LetOrUse. 

CHANGELOG.md, src/Fantomas.Tests/AttributeTests.fs, src/Fantomas/AstTransformer.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/TriviaTypes.fs
=> Print trivia of SynBinding prefix outside multiline check. 

CHANGELOG.md, src/Fantomas.Tests/ModuleTests.fs, src/Fantomas.Tests/TriviaTests.fs, src/Fantomas/AstTransformer.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs, src/Fantomas/TriviaTypes.fs
Fixes #2141.
Hey Colin, thanks for reporting this. This is quite annoying and I will publish a fix for this as soon as I can.
=> Use module or namespace as FsAstType. 

src/Fantomas.Tests/TypeDeclarationTests.fs, src/Fantomas/AstTransformer.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/TriviaTypes.fs
=> Print trivia for member keyword. 

CHANGELOG.md, src/Fantomas.Tests/CommentTests.fs, src/Fantomas/TokenParser.fs
=> Don't collect triple slash comment in LineComments active pattern.

build.fsx, docs/index.html
@baronfel something tells me you might have an idea for this in the future.
=> Don't upload benchmark result anymore to Azure

src/Fantomas.Tests/UnionTests.fs, src/Fantomas/AstTransformer.fs, src/Fantomas/CodePrinter.fs, src/Fantomas/SourceParser.fs, src/Fantomas/TriviaTypes.fs
=> Construct full range of SynUnionCase and SynEnumCase.

CHANGELOG.md, src/Fantomas.Tests/UnionTests.fs, src/Fantomas/CodePrinter.fs
=> Add newline if there is trivia after the bar in a union case.

src/Fantomas.Tests/LambdaTests.fs, src/Fantomas/CodePrinter.fs
=> Add parenthesis around lambda inside oneliner infix app

CHANGELOG.md, src/Fantomas.Tests/ModuleTests.fs, src/Fantomas/CodePrinter.fs
=> Remove a superfluous unindent for match lambda in AppWithLambda

src/Fantomas.FCS/Parse.fs
So we can use this in the online tool
=> Expose parse function from Fantomas.FCS.

.config/dotnet-tools.json, .git-blame-ignore-revs, build.fsx, src/Fantomas.Core.Tests/TestHelpers.fs, src/Fantomas.Core/CodeFormatterImpl.fs, src/Fantomas.Core/CodePrinter.fs, src/Fantomas.Core/Queue.fs, src/Fantomas.Core/Trivia.fs, src/Fantomas.Core/TriviaTypes.fs, src/Fantomas.Core/Utils.fs, src/Fantomas/Daemon.fs
Dogfooding the first release with the new FCS changes.
=> Eat your own tail!

.config/dotnet-tools.json, .git-blame-ignore-revs, build.fsx, src/Fantomas.Core.Tests/TestHelpers.fs, src/Fantomas.Core/CodeFormatterImpl.fs, src/Fantomas.Core/CodePrinter.fs, src/Fantomas.Core/Queue.fs, src/Fantomas.Core/Trivia.fs, src/Fantomas.Core/TriviaTypes.fs, src/Fantomas.Core/Utils.fs, src/Fantomas/Daemon.fs
Reverts fsprojects/fantomas#2235
=> Revert "Eat your own tail!"

CHANGELOG.md, src/Fantomas.Core.Tests/CommentTests.fs, src/Fantomas.Core.Tests/Fantomas.Core.Tests.fsproj, src/Fantomas.Core.Tests/IdentTests.fs, src/Fantomas.Core.Tests/OperatorTests.fs, src/Fantomas.Core/CodePrinter.fs, src/Fantomas.Core/SourceParser.fs
The recent FCS changes of https://github.com/fsprojects/fantomas/pull/2218 resolve a couple of problems:
Fixes #2164
Fixes #2167
Fixes #2212
Fixes #2116
Fixes #2034
Fixes #1842
Fixes #2186
=> Regression tests

README.md
Fixes #2220 
Very minor fix of the code example on the main `readme.md` page.
=> Fix main readme.md code example

CHANGELOG.md, src/Fantomas.Core.Tests/HashDirectiveTests.fs, src/Fantomas.Core/AstTransformer.fs, src/Fantomas.Core/CodePrinter.fs, src/Fantomas.Core/SourceTransformer.fs, src/Fantomas.Core/TriviaTypes.fs
=> Improve trivia handling for SynModuleSigDecl.

CHANGELOG.md, src/Fantomas.Core.Tests/ClassTests.fs, src/Fantomas.Core/CodePrinter.fs
=> Preserve override keyword in read property.

.config/dotnet-tools.json, CHANGELOG.md, src/Fantomas.Core.Tests/BlankLinesAroundNestedMultilineExpressions.fs, src/Fantomas.Core.Tests/ColMultilineItemTests.fs, src/Fantomas.Core.Tests/CommentTests.fs, src/Fantomas.Core.Tests/CompilerDirectivesTests.fs, src/Fantomas.Core.Tests/ComputationExpressionTests.fs, src/Fantomas.Core.Tests/ControlStructureTests.fs, src/Fantomas.Core.Tests/DotGetTests.fs, src/Fantomas.Core.Tests/IfThenElseTests.fs, src/Fantomas.Core.Tests/InterpolatedStringTests.fs, src/Fantomas.Core.Tests/KeepIndentInBranchTests.fs, src/Fantomas.Core.Tests/LetBindingTests.fs, src/Fantomas.Core.Tests/MultilineFunctionApplicationsInConditionExpressionsTests.fs, src/Fantomas.Core.Tests/OperatorTests.fs, src/Fantomas.Core.Tests/PatternMatchingTests.fs, src/Fantomas.Core.Tests/Stroustrup/FunctionApplicationDualListTests.fs, src/Fantomas.Core.Tests/Stroustrup/FunctionApplicationSingleListTests.fs, src/Fantomas.Core.Tests/Stroustrup/SynMatchClauseExpressionTests.fs, src/Fantomas.Core.Tests/SynLongIdentTests.fs, src/Fantomas.Core/AstTransformer.fs, src/Fantomas.Core/CodePrinter.fs, src/Fantomas.Core/Context.fs, src/Fantomas.Core/SourceParser.fs, src/Fantomas.Core/TriviaTypes.fs
Fixes #1881.
@dsyme could you review my PR comments please?
I have some questions in regards to https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-trywith-expressions.
=> Update style of SynExpr.TryWith with a single clause

CHANGELOG.md, src/Fantomas.Core.Tests/SynConstTests.fs, src/Fantomas.Core/SourceParser.fs
=> Remove superfluous space between negate and RationalConst

src/Fantomas.Core/AstTransformer.fs, src/Fantomas.Core/AstTransformer.fsi, src/Fantomas.Core/CodePrinter.fsi, src/Fantomas.Core/Context.fs, src/Fantomas.Core/Fantomas.Core.fsproj
Adding some signature files to the modules that have the smallest surface area.
=> Add signature files for AstTransformer and CodePrinter.

CHANGELOG.md, src/Fantomas.Core.Tests/CompilerDirectivesTests.fs, src/Fantomas.Core/Trivia.fs
=> Restore content after else/endif directives

CHANGELOG.md, src/Fantomas.Core.Tests/ComputationExpressionTests.fs, src/Fantomas.Core/SourceParser.fs
=> Extend NamedComputationExpr ap to capture SynExpr.TypeApp

docs/index.html
I tried to test this locally with `dotnet fsdocs watch`, but some of the styling assets wouldn't load. So I can't be sure that the carousel works 100% correctly.
=> Add a quote from Chet

src/Fantomas.Core/CodePrinter.fs, src/Fantomas.Core/Context.fs
=> introduce helper function indentSepNlnUnindent()

src/Fantomas.Core/CodePrinter.fs, src/Fantomas.Core/CodePrinter.fsi
It was only set once but never checked.
First stab at #2327
=> Remove the IsNakedRange field from the ASTContext type.

src/Fantomas.Core/CodePrinter.fs, src/Fantomas.Core/CodePrinter.fsi
=> Remove InterfaceRange

src/Fantomas.Core.Tests/ContextTests.fs, src/Fantomas.Core/CodePrinter.fs, src/Fantomas.Core/Context.fs
=> Reduce usage of custom operators (!+) (++) (+-) (!+-) (+~) (--)

CHANGELOG.md, src/Fantomas.Core.Tests/CompilerDirectivesTests.fs
regression test for #801
regression test for #1186
=> Add regression tests for 801, 1186

CHANGELOG.md, src/Fantomas.Core.Tests/IfThenElseTests.fs
=> Add regression test for 1775

CHANGELOG.md, src/Fantomas.Core.Tests/ClassTests.fs, src/Fantomas.Core/CodePrinter.fs
=> Consider trivia before And keyword in SynMemberDefn.GetSetMember.

docs/docs/contributors/FSharp.md, docs/docs/contributors/Index.md
Related to https://github.com/fsprojects/fantomas/issues/2330
=> Add initial F# information.

CHANGELOG.md, src/Fantomas.Core.Tests/Fantomas.Core.Tests.fsproj, src/Fantomas.Core.Tests/ShebangTests.fs, src/Fantomas.Core/Trivia.fs
=> Keep shebang directives intact

CHANGELOG.md, src/Fantomas.Core.Tests/TupleTests.fs, src/Fantomas.Core/CodePrinter.fs
=> Extract longExpression from genTuple into genTupleMultiline.

src/Fantomas.FCS/Fantomas.FCS.fsproj, src/Fantomas.FCS/Parse.fsi
This is in preparation for generating a reference assembly for Fantomas.FCS.
=> Add signature file to Fantomas.FCS.

docs/.style/fsdocs-custom.sass, docs/.style/global-config.sass, docs/.style/sidebar.sass, docs/.style/variables.sass, docs/_template.html
=> Force full height of `.doc-content`.

CHANGELOG.md, src/Fantomas.Core.Tests/UnionTests.fs, src/Fantomas.Core/CodePrinter.fs
=> Add new line when single case DU has xml doc.

CHANGELOG.md, src/Fantomas.Core.Tests/FunctionDefinitionTests.fs, src/Fantomas.Core/CodePrinter.fs, src/Fantomas.Core/SourceParser.fs
=> Add stars when all types in segment are SynTypes.

src/Fantomas.Core.Tests/PatternMatchingTests.fs, src/Fantomas.Core/CodePrinter.fs, src/Fantomas.Core/CodePrinter.fsi, src/Fantomas.Core/Context.fs, src/Fantomas.Core/SourceParser.fs
=> Remove IsInsideMatchClausePattern from ASTContext.

CHANGELOG.md, src/Fantomas.Core.Tests/TupleTests.fs
=> Add regression test for 2159

CHANGELOG.md, src/Fantomas.Core.Tests/RecordTests.fs, src/Fantomas.Core/CodePrinter.fs
=> use atCurrentColumnIndent for Records in genExprInMultilineInfixExpr

CHANGELOG.md, src/Fantomas.Core.Tests/PatternMatchingTests.fs
Regression test for #2289 so we can close the issue.
=> Add a regression test for 2289

docs/docs/contributors/Conditional Compilation Directives.md, docs/docs/contributors/Formatted Code.md
=> Add page about Conditional Compilation Directives.

.config/dotnet-tools.json, .git-blame-ignore-revs, src/Fantomas.Core/CodePrinter.fs, src/Fantomas.Core/SourceParser.fs, src/Fantomas.Core/SourceTransformer.fs
Reverts fsprojects/fantomas#2422
=> Revert "Bump fantomas"

docs/docs/end-users/FAQ.md, docs/docs/end-users/FormattingCheck.md
=> Check documentation

CHANGELOG.md, src/Fantomas.Core.Tests/ClassTests.fs, src/Fantomas.Core/AstTransformer.fs, src/Fantomas.Core/CodePrinter.fs, src/Fantomas.Core/TriviaTypes.fs
=> Print trivia for abstract keyword in AbstractSlot.

Directory.Build.props
=> Adding David as author 🎉

docs/.style/fsdocs-custom.sass
@alanlomeli, you'll need to rebase after this one.
=> Correct styling of headings.

src/Fantomas.Core.Tests/ListTests.fs
=> Minor: test that was missed being included in #2192

CHANGELOG.md, src/Fantomas.Core.Tests/OperatorTests.fs, src/Fantomas.Core/CodePrinter.fs
=> Print trivia for MatchLambda in multiline infix expression.

CHANGELOG.md, src/Fantomas.Core.Tests/CommentTests.fs, src/Fantomas.Core/Context.fs
=> Fix #2450 Trailing whitespace

CHANGELOG.md, src/Fantomas.Core.Tests/ComputationExpressionTests.fs, src/Fantomas.Core/CodePrinter.fs, src/Fantomas.Core/SourceParser.fs
=> Print trivia for SynExpr.ComputationExpr in named computation expression

CHANGELOG.md, src/Fantomas.Core.Tests/PatternMatchingTests.fs
=> Add regression test for 2044

.config/dotnet-tools.json, CONTRIBUTING.md, docs/_template.html, docs/content/webcomponents.js, docs/docs/contributors/Conditional Compilation Directives.md, docs/docs/contributors/FSharp.md, docs/docs/contributors/Formatted Code.md, docs/docs/contributors/Getting Started.md, docs/docs/contributors/How Can I Contribute.md, docs/docs/contributors/Index.md, docs/docs/contributors/Prepare Context.md, docs/docs/contributors/Print AST with Context.md, docs/docs/contributors/Solution Structure.md, docs/docs/end-users/Configuration.fsx, docs/docs/end-users/FAQ.md, docs/docs/end-users/FormattingCheck.md, docs/docs/end-users/GettingStarted.md, docs/docs/end-users/GitHooks.md, docs/docs/end-users/IgnoreFiles.md, docs/docs/end-users/Rider.md, docs/docs/end-users/StyleGuide.md, docs/docs/end-users/VSCode.md, docs/docs/end-users/VisualStudio.md, docs/docs/index.md, docs/index.html
@dawedawe could you review the new file `docs/docs/contributors/How Can I Contribute.md` please?
Fixes https://github.com/fsprojects/fantomas/issues/2329.
=> Contribution suggestions

README.md, docs/_template.html, docs/docs/contributors/Conditional Compilation Directives.md, docs/docs/contributors/FSharp.md, docs/docs/contributors/Prepare Context.md, docs/docs/index.md
Was verifying all documentation links, caught these.
=> Fix documentation links

docs/.style/fsdocs-custom.sass, docs/.style/sidebar.sass, docs/.style/variables.sass, docs/_menu-item_template.html, docs/_menu_template.html, docs/_template.html, docs/content/docs-setup.js
- Hide sidebar by default when on mobile
- Fix some overflows with some titles and codesnippets
=> Documentation fixes for mobile

CHANGELOG.md, src/Fantomas.Core.Tests/SignatureTests.fs, src/Fantomas.Core/CodePrinter.fs
=> Add additional newline after ModuleOrNamespace in signature file

CHANGELOG.md, README.md, docs-old/Daemon mode.md, docs/docs/end-users/FAQ.md, docs/docs/end-users/GettingStarted.md, docs/docs/end-users/Rider.md, docs/docs/end-users/VisualStudio.md, docs/index.html, fake-sample/.config/dotnet-tools.json
=> v5.0.0 stable

.config/dotnet-tools.json
﻿Please verify your pull request is respecting our [Pull request ground rules](https://fsprojects.github.io/fantomas/docs/contributors/Pull%20request%20ground%20rules.html).
You can find more information in our [Contributors documentation section](https://fsprojects.github.io/fantomas/docs/contributors/Index.html).
=> Bump Fantomas to v5.

CHANGELOG.md, src/Fantomas.Core.Tests/Stroustrup/SynBindingValueExpressionTests.fs, src/Fantomas.Core/SourceParser.fs
Closes #2508
This fixes the invalid output, but this issue also brought up the point I mention in https://github.com/fsharp/fslang-design/issues/706#issuecomment-1250128868 that I think the current output isn't the most correct 'Stroustrup' style.
=> Fix invalid output for anonymous record & copy expression

CHANGELOG.md, src/Fantomas.Core.Tests/RecordTests.fs, src/Fantomas.Core/CodePrinter.fs
=> Fix equality comparison with a record with a with expression

CHANGELOG.md, src/Fantomas.Core.Tests/Stroustrup/SynTypeDefnSimpleReprRecordTests.fs, src/Fantomas.Core/CodePrinter.fs
=> Fix invalid output for record with accessibility modifier & members

fantomas.sln
This just adds existing files to the `.sln` file for easier access from within Rider/Visual Studio.
I just chose the name `Solution Items` because I think that's a common convention in Visual Studio, but the name is purely arbitrary so if you would prefer a different name that's 100% fine by me haha.
=> Include solution items in .sln

CHANGELOG.md, src/Fantomas.Core.Tests/TypeDeclarationTests.fs
=> Add regression test for ML-style generic definitions

CHANGELOG.md, src/Fantomas.Core.Tests/Stroustrup/SynBindingFunctionExpressionTests.fs, src/Fantomas.Core.Tests/Stroustrup/SynMatchClauseExpressionTests.fs, src/Fantomas.Core/Context.fs, src/Fantomas.Core/Fantomas.Core.fsproj, src/Fantomas.Core/SourceTransformer.fs
=> Prevent stroustrup formatting when trivia is present before

docs/.style/fsdocs-custom.sass, docs/content/webcomponents.js, docs/docs/end-users/Configuration.fsx
The current anchors on the [settings page](https://fsprojects.github.io/fantomas/docs/end-users/Configuration.html) are not that nice due to the icon web component:
This PR addresses this.
=> Update generated setting anchors.

src/Fantomas.Core/CodePrinter.fs, src/Fantomas.Core/CodePrinter.fsi
=> Remove IsUnionField from ASTContext.

CHANGELOG.md, src/Fantomas.Core.Tests/AppTests.fs, src/Fantomas.Core/CodePrinter.fs, src/Fantomas.Core/SourceParser.fs
=> Update style for function call with parenthesis around function name.

CHANGELOG.md, src/Fantomas.Core.Tests/IndexSyntaxTests.fs, src/Fantomas.Core/CodePrinter.fs
=> Don't add a space for prefixed new index syntax

src/Fantomas.Core/CodePrinter.fs, src/Fantomas.Core/CodePrinter.fsi
=> Remove IsFirstTypeParam from ASTContext.

src/Fantomas.Core.Tests/ClassTests.fs, src/Fantomas.Core.Tests/CommentTests.fs, src/Fantomas.Core.Tests/CompilerDirectivesTests.fs, src/Fantomas.Core.Tests/Fantomas.Core.Tests.fsproj, src/Fantomas.Core.Tests/InterfaceTests.fs, src/Fantomas.Core.Tests/KeepIndentInBranchTests.fs, src/Fantomas.Core.Tests/LambdaTests.fs, src/Fantomas.Core.Tests/MultiLineLambdaClosingNewlineTests.fs, src/Fantomas.Core.Tests/NewlineBetweenTypeDefinitionAndMembersTests.fs, src/Fantomas.Core.Tests/NumberOfItemsRecordTests.fs, src/Fantomas.Core.Tests/RecordTests.fs, src/Fantomas.Core.Tests/SignatureTests.fs, src/Fantomas.Core.Tests/TypeAnnotationTests.fs, src/Fantomas.Core.Tests/TypeDeclarationTests.fs, src/Fantomas.Core/CodePrinter.fs
Following up on https://github.com/fsharp/fslang-design/issues/708.
Please review @dsyme.
=> Multiline type annotations

CHANGELOG.md, src/Fantomas.Core.Tests/AppTests.fs
Here's the regression test in order to close #1869
=> Add regression test for 1869

src/Fantomas.Core/AstExtensions.fs, src/Fantomas.Core/AstExtensions.fsi, src/Fantomas.Core/AstTransformer.fs
=> Remove unused type extensions.

docs/docs/contributors/Glossary.md, docs/docs/contributors/Pull request ground rules.md
Here's a first stab at a glossary to fix #2493 
I'm not sure about the scope we should cover with this.
Opinions?
=> First stab at a glossary

src/Fantomas.Core.Tests/SignatureTests.fs, src/Fantomas.Core/CodePrinter.fs, src/Fantomas.Core/SourceParser.fs
Found during local regression testing of dotnet/fsharp.
=> Fix internal constructor signature.

CHANGELOG.md, Directory.Build.props, src/Fantomas.Core.Tests/ASTTransformerTests.fs, src/Fantomas.Core.Tests/SynLongIdentTests.fs, src/Fantomas.Core/AstTransformer.fs, src/Fantomas.Core/CodePrinter.fs, src/Fantomas.Core/Selection.fs, src/Fantomas.Core/SourceParser.fs, src/Fantomas.Core/TriviaTypes.fs, src/Fantomas.FCS/Parse.fs
Update FCS to https://github.com/dotnet/fsharp/commit/7d115d56cde12006dd26a3c5babd702df451b8e8
=> Update FCS to 'TypeDefn and NamespaceOrModule leading trivia'

CHANGELOG.md, src/Fantomas.Core.Tests/TypeDeclarationTests.fs, src/Fantomas.Core/CodePrinter.fs
=> Fix format of self identifier line with AlternativeLongMemberDefinitions

docs/docs/end-users/Rider.md
I think this is currently affecting quite some users (@edgarfgp, @aklefdal, ...) , so let's document it.
=> Document the behaviour of Rider regarding default settings

.config/dotnet-tools.json, .git-blame-ignore-revs, src/Fantomas.Client/FantomasToolLocator.fs, src/Fantomas.Client/LSPFantomasService.fs, src/Fantomas.Client/LSPFantomasServiceTypes.fs, src/Fantomas.Core.Tests/CodePrinterHelperFunctionsTests.fs, src/Fantomas.Core.Tests/DefinesTests.fs, src/Fantomas.Core.Tests/TriviaTests.fs, src/Fantomas.Core/AstExtensions.fs, src/Fantomas.Core/AstTransformer.fs, src/Fantomas.Core/CodeFormatterImpl.fs, src/Fantomas.Core/CodePrinter.fs, src/Fantomas.Core/Context.fs, src/Fantomas.Core/Defines.fs, src/Fantomas.Core/Selection.fs, src/Fantomas.Core/SourceParser.fs, src/Fantomas.Core/SourceTransformer.fs, src/Fantomas.Core/Trivia.fs, src/Fantomas.Core/Validation.fs, src/Fantomas.FCS/Parse.fs, src/Fantomas.Tests/Integration/DaemonTests.fs, src/Fantomas/Format.fs, src/Fantomas/Program.fs
=> Bump fantomas

CHANGELOG.md, src/Fantomas.Core.Tests/IndexSyntaxTests.fs, src/Fantomas.Core/CodePrinter.fs, src/Fantomas.Core/SourceParser.fs
=> Extend IndexWithoutDotExpr with the range of the ArrayOrList to fix 2611

CHANGELOG.md, src/Fantomas.Core.Tests/InterfaceTests.fs, src/Fantomas.Core/CodePrinter.fs
=> Stricter check for default interface member consumption in object expression

CHANGELOG.md
=> Add release notes for 5.1.1

CHANGELOG.md, src/Fantomas.Core.Tests/UnionTests.fs, src/Fantomas.Core/CodePrinter.fs
=> Handle idempotency problem with anon types in unions.

build.fsx
=> Add runIfOnlySpecified for PushClient pipeline.

CHANGELOG.md, docs/docs/contributors/Pull request ground rules.md, docs/docs/contributors/Releases.md
Added some notes of things I do when I release a new version.
=> Add notes for releases.

docs/docs/end-users/Configuration.fsx, docs/docs/end-users/GeneratingCode.fsx
The scripts in the documentation are broken.
In `Configuration.fsx` one sample did not have valid input code.
The AST changed in `GeneratingCode.fsx` that needed a minor update as well.
=> Update scripts in documentation.

docs/docs/contributors/Getting Started.md, src/Fantomas.FCS/Fantomas.FCS.fsproj
@baronfel, this worked for me though I can't really tell whether I'm hooking this before the right target. Any thoughts?
=> Add target to download FCS files

CHANGELOG.md, src/Fantomas.Core.Tests/ClassTests.fs, src/Fantomas.Core/CodePrinter2.fs
=> call genAttributes for ExplicitCtor node

src/Fantomas.Core.Tests/DallasTests.fs, src/Fantomas.Core/CodePrinter2.fs, src/Fantomas.Core/SyntaxOak.fs
Alternate take to resolve https://github.com/fsprojects/fantomas/issues/2594.
=> Indent/newline short paren argument with trivia before it.

src/Fantomas.Core.Tests/MultiLineLambdaClosingNewlineTests.fs, src/Fantomas.Core/CodePrinter2.fs
This is my first attempt at solving #2642.
Though the solution might be a little bit less conventional, I do think this does the job quite nicely.
Let me know what you think @dawedawe.
=> Include closing parenthesis in single lambda body newline check.

CHANGELOG.md, src/Fantomas.Core.Tests/DallasTests.fs, src/Fantomas.Core.Tests/LambdaTests.fs, src/Fantomas.Core/CodePrinter2.fs, src/Fantomas.Core/SyntaxOak.fs
Fixes https://github.com/fsprojects/fantomas/issues/2646
Fixes https://github.com/fsprojects/fantomas/issues/2648
Fixes https://github.com/fsprojects/fantomas/issues/2649
Fixes https://github.com/fsprojects/fantomas/issues/2650
=> Panmona fixes to Dallas

src/Fantomas.Core.Tests/TypeDeclarationTests.fs
=> Add regression test for comment between empty constructor.

src/Fantomas.Core.Tests/OperatorTests.fs, src/Fantomas.Core/Fangorn.fs
=> Collect same infix applications when position on the right side.

Directory.Build.props, src/Fantomas.Core.Tests/ContextTests.fs, src/Fantomas.Core.Tests/TestHelpers.fs, src/Fantomas.Core/Context.fs, src/Fantomas.Core/Context.fsi, src/Fantomas.Core/Fantomas.Core.fsproj, src/Fantomas.Core/ISourceTextExtensions.fsi, src/Fantomas.Core/RangeHelpers.fs, src/Fantomas.Core/RangeHelpers.fsi, src/Fantomas.Core/Utils.fs, src/Fantomas.Core/Utils.fsi, src/Fantomas.Core/Validation.fs, src/Fantomas.Core/Validation.fsi, src/Fantomas.Tests/TestHelpers.fs
Some more signature files, some more dead code removal.
=> More signature files

src/Fantomas.Core/ASTTransformer.fs, src/Fantomas.Core/SyntaxOak.fs
=> Remove implicitCtor in TypeDefnExplicitNode.

CHANGELOG.md, src/Fantomas.Core.Tests/DotGetTests.fs, src/Fantomas.Core/CodePrinter.fs
=> Print argument in short type app function identifier.

src/Fantomas.Tests/Integration/IgnoreFilesTests.fs, src/Fantomas/Program.fs
Stumbled upon these while working on the logging stuff
=> Remove some superfluous code

.config/dotnet-tools.json, CHANGELOG.md, build.fsx, src/Fantomas/IgnoreFile.fs
5.2.0-beta-001 is unlisted now.
=> Format using v5.2 alpha 11

CHANGELOG.md, src/Fantomas.Core.Tests/OpenTypeTests.fs, src/Fantomas.Core/CodePrinter.fs
=> Add genNode for OpenTargetNode.

CHANGELOG.md, src/Fantomas.Core.Tests/TypeDeclarationTests.fs, src/Fantomas.Core/ASTTransformer.fs
=> Process non-typed SynSimplePat.Attrib

.github/workflows/regressions.yml
There was invalid yaml, who would have thought it 🙈
=> Fix regressions.yml

.github/workflows/regressions.yml
=> No space in job name.

.github/workflows/regressions.yml
=> Download FCS files explicitly.

CHANGELOG.md, src/Fantomas.Core.Tests/ModuleTests.fs, src/Fantomas.Core/CodePrinter.fs
=> Fix problem with empty nested module generation

README.md
See https://github.com/badges/shields/issues/8671
=> Update github action shield link.

src/Fantomas.Core.Tests/AlignedMultilineBracketStyleTests.fs, src/Fantomas.Core.Tests/CrampedMultilineBracketStyleTests.fs, src/Fantomas.Core.Tests/Fantomas.Core.Tests.fsproj, src/Fantomas.Core.Tests/RecordTests.fs, src/Fantomas.Core.Tests/Stroustrup/DotIndexedSetExpressionTests.fs, src/Fantomas.Core.Tests/Stroustrup/DotSetExpressionTests.fs, src/Fantomas.Core.Tests/Stroustrup/KeepIndentInBranchExpressionTests.fs, src/Fantomas.Core.Tests/Stroustrup/LambdaExpressionTests.fs, src/Fantomas.Core.Tests/Stroustrup/LetOrUseBangExpressionTests.fs, src/Fantomas.Core.Tests/Stroustrup/LongIdentSetExpressionTests.fs, src/Fantomas.Core.Tests/Stroustrup/MultiLineLambdaClosingNewlineExpressionTests.fs, src/Fantomas.Core.Tests/Stroustrup/NamedArgumentExpressionTests.fs, src/Fantomas.Core.Tests/Stroustrup/SetExpressionTests.fs, src/Fantomas.Core.Tests/Stroustrup/SynBindingFunctionExpressionTests.fs, src/Fantomas.Core.Tests/Stroustrup/SynBindingFunctionLongPatternExpressionTests.fs, src/Fantomas.Core.Tests/Stroustrup/SynBindingFunctionWithReturnTypeExpressionTests.fs, src/Fantomas.Core.Tests/Stroustrup/SynBindingValueExpressionTests.fs, src/Fantomas.Core.Tests/Stroustrup/SynExprAndBangExpressionTests.fs, src/Fantomas.Core.Tests/Stroustrup/SynMatchClauseExpressionTests.fs, src/Fantomas.Core.Tests/Stroustrup/YieldOrReturnBangExpressionTests.fs, src/Fantomas.Core.Tests/Stroustrup/YieldOrReturnExpressionTests.fs, src/Fantomas.Core/CodePrinter.fs, src/Fantomas.Core/SyntaxOak.fs
This is to update to match what's currently in the docs proposal.
=> Update output for copy-and-update expression for Stroustrup

CHANGELOG.md, src/Fantomas.Core/CodeFormatter.fs, src/Fantomas.Core/CodeFormatter.fsi, src/Fantomas.Core/SyntaxOak.fs
=> Expose SyntaxOak API

.config/dotnet-tools.json, build.fsx, docs/docs/end-users/FAQ.md, docs/docs/end-users/GeneratingCode.fsx, docs/docs/end-users/UpgradeGuide.md
A first stab at https://github.com/fsprojects/fantomas/issues/2757
=> Upgrade guide

CHANGELOG.md, src/Fantomas.Core.Tests/TupleTests.fs, src/Fantomas.Core/CodePrinter.fs
Closes #2771 
﻿Please verify your pull request is respecting our [Pull request ground rules](https://fsprojects.github.io/fantomas/docs/contributors/Pull%20request%20ground%20rules.html).
You can find more information in our [Contributors documentation section](https://fsprojects.github.io/fantomas/docs/contributors/Index.html).
=> Fixes comma breaking with lambda in tuple, #2771

src/Fantomas.Core.Tests/AlignedMultilineBracketStyleTests.fs, src/Fantomas.Core.Tests/CrampedMultilineBracketStyleTests.fs, src/Fantomas.Core.Tests/Stroustrup/SynTypeDefnSigReprSimpleTests.fs, src/Fantomas.Core.Tests/Stroustrup/SynTypeDefnSimpleReprRecordTests.fs, src/Fantomas.Core/CodePrinter.fs
=> Fix record type generation for stroustrup types with members

docs/docs/end-users/FAQ.md
fixes #2754 by adding an FAQ entry
=> add a FAQ entry about the effects of the new indexing syntax on older code

CHANGELOG.md, src/Fantomas.Core.Tests/Stroustrup/SynBindingValueExpressionTests.fs, src/Fantomas.Core.Tests/Stroustrup/SynMatchClauseExpressionTests.fs, src/Fantomas.Core/Context.fs
=> Don't apply stroustrup when WriteBeforeNewline is not empty.

CHANGELOG.md, Directory.Build.props, src/Fantomas.Core/ASTTransformer.fs
Update to [ba6647ebf5b94823c4d6fafd1e7d5f806d915ee0](https://github.com/dotnet/fsharp/commit/ba6647ebf5b94823c4d6fafd1e7d5f806d915ee0)
=> Update FCS to 'Add parser recovery for incomplete named pat pair'

CHANGELOG.md, src/Fantomas.Core.Tests/TupleTests.fs, src/Fantomas.Core/CodePrinter.fs
=> extend genTuple to wrap the rhs of an infixapp in parens if needed

CHANGELOG.md, src/Fantomas.Core.Tests/SpaceBeforeColonTests.fs, src/Fantomas.Core/CodePrinter.fs
=> honor Config.SpaceBeforeColon in genReturnTypeBinding

docs/.style/sidebar.sass, docs/_template.html
This allows the sidebar (blue) menu to scroll down automatically when the page is long ([example]( https://fsprojects.github.io/fantomas/reference/fsharp-compiler-syntaxtreeops.html))
=> Add position sticky to the sidebar.

.github/workflows/main.yml, build.fsx
This would automate the release process.
=> Automate releases

CHANGELOG.md, src/Fantomas.Core.Tests/Stroustrup/SynTypeDefnSimpleReprRecordTests.fs, src/Fantomas.Core/CodePrinter.fs
=> Fix stroustrup formatting issue with trivia

CHANGELOG.md, src/Fantomas.Core.Tests/CommentTests.fs, src/Fantomas.Core/CodePrinter.fs
=> add a newline after the operator in SameInfix applications to let comment be printed

CHANGELOG.md, src/Fantomas.Core.Tests/SynConstTests.fs, src/Fantomas.Core/ASTTransformer.fs, src/Fantomas.Core/CodePrinter.fs, src/Fantomas.Core/SyntaxOak.fs
fixes #2931 and #2937 
To fix the other block comment issues another round of range additions is needed in the AST.
=> fix 2931 and 2937 by generating child nodes for the numerator and for the minus

CHANGELOG.md, Directory.Build.props, src/Fantomas.Core.Tests/SynConstTests.fs, src/Fantomas.Core/ASTTransformer.fs, src/Fantomas.Core/CodePrinter.fs, src/Fantomas.Core/SyntaxOak.fs
=> Fix 2934, 2935, 2936 by using newly provided ranges from the AST

.config/dotnet-tools.json, Directory.Packages.props, src/Fantomas.Benchmarks/packages.lock.json, src/Fantomas.Client.Tests/EndToEndTests.fs, src/Fantomas.Client.Tests/packages.lock.json, src/Fantomas.Client/FantomasToolLocator.fs, src/Fantomas.Client/LSPFantomasService.fs, src/Fantomas.Client/packages.lock.json, src/Fantomas.Core.Tests/CodePrinterHelperFunctionsTests.fs, src/Fantomas.Core.Tests/InterpolatedStringTests.fs, src/Fantomas.Core.Tests/OperatorTests.fs, src/Fantomas.Core.Tests/packages.lock.json, src/Fantomas.Core/ASTTransformer.fs, src/Fantomas.Core/CodePrinter.fs, src/Fantomas.Core/MultipleDefineCombinations.fs, src/Fantomas.Core/packages.lock.json, src/Fantomas.FCS/packages.lock.json, src/Fantomas.Tests/IgnoreFileTests.fs, src/Fantomas.Tests/Integration/ConfigTests.fs, src/Fantomas.Tests/Integration/ForceTests.fs, src/Fantomas.Tests/packages.lock.json, src/Fantomas/Program.fs, src/Fantomas/packages.lock.json
Also add missing `%X` annotations in interpolated strings.
=> Update analyzer packages

Directory.Build.targets
Sorry, missed the verbosity flag change...
=> fix analyzers verbosity flag

.config/dotnet-tools.json, Directory.Build.targets, Directory.Packages.props, src/Fantomas.Benchmarks/packages.lock.json, src/Fantomas.Client.Tests/packages.lock.json, src/Fantomas.Client/packages.lock.json, src/Fantomas.Core.Tests/packages.lock.json, src/Fantomas.Core/packages.lock.json, src/Fantomas.FCS/packages.lock.json, src/Fantomas.Tests/packages.lock.json, src/Fantomas/packages.lock.json
bump Ionide.Analyzers to 0.9.0
bump fsdocs-tool to 20.0.0
bump fsharp-analyzers tool to 0.25.0
=> bump Analyzers and tools

.github/dependabot.yml, Directory.Packages.props, src/Fantomas.Benchmarks/packages.lock.json, src/Fantomas.Client.Tests/packages.lock.json, src/Fantomas.Client/packages.lock.json, src/Fantomas.Core.Tests/packages.lock.json, src/Fantomas.Core/packages.lock.json, src/Fantomas.FCS/packages.lock.json, src/Fantomas.Tests/packages.lock.json, src/Fantomas/packages.lock.json
=> Add dependabot

CHANGELOG.md, src/Fantomas.Core.Tests/DynamicOperatorTests.fs, src/Fantomas.Core/CodePrinter.fs
fixes #2998
Sorry, I should have checked the issue backlog and solve them in one PR.
=> Fix another exn in (|UppercaseExpr|LowercaseExpr|)

CHANGELOG.md, src/Fantomas.Core.Tests/DotLambdaTests.fs, src/Fantomas.Core/CodePrinter.fs
fixes #3097 and makes a release
=> Fix dot lambda regression reported in 3097

.github/workflows/push-client.yml, build.fsx
I hope this can push the client package, I no longer gave the nuget key locally...
=> Add pipeline to push client

CHANGELOG.md, src/Fantomas.Core.Tests/InterpolatedStringTests.fs, src/Fantomas.Core/CodePrinter.fs
fixes #3162 
I think we have enough for a new release.
=> Fix anonymous records in interpolated strings
